### ISSUE TITLE
Feature request: Merge tags

### ISSUE THREAD

**Issue by walle89** [maizzle/framework#1]
When I build templates that needs to be localized, I put all texts and URLs into variables at the ESP (Email service provider).

Example:
```
<h1>{l10n.introduction.header}</h2>
{l10n.introduction.text}
```
I could add the tags directly into the template, but it's problematic to have these during development and layout testing. Ideally I want to use front matter to populate the variables with test data and let it use that for development and stage builds.

Example:
```
---
l10n.introduction.header: Header 1 test
l10n.introduction.text: "<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Eam si varietatem diceres, intellegerem, ut etiam non dicente te intellego; Itaque hic ipse iam pridem est reiectus; Huius ego nunc auctoritatem sequens idem faciam. Id enim volumus, id contendimus, ut officii fructus sit ipsum officium. Nondum autem explanatum satis, erat, quid maxime natura vellet.</p><p>Duo Reges: constructio interrete. Et certamen honestum et disputatio splendida! omnis est enim de virtutis dignitate contentio.</p>"
---
{% block template %}
<h1>{% __(l10n.introduction.header) %}</h2>
{% __(l10n.introduction.text) }
{% endblock %}
```
It would be nice to also include to exclude ESP specific code. Like:
```
{% mergetags %}
    {if (profile.data.vip = 'true')}
{% endmergetags%}

{# HTML code for VIP customers   #}

{% mergetags %}
    {/if}
{% endmergetags %}
```
Let me know if you have any question for my suggestion.

**Comment by cossssmin** [comment]
Not sure I understand, so please correct me if I'm mistaken.

So, if you had this:

```yaml
---
l10n.introduction.header: Header 1 test
l10n.introduction.text: "<p>Lorem ipsum dolor sit amet....</p>"
---
```

You can access it in the template under the `page` object:

```nunjucks
{% block template %}
  <h1>{{ page.l10n.introduction.header }}</h1>
  <div>{{ page.l10n.introduction.text }}</div>
{% endblock %}
```

I understand your ESP is using `{` and `}` for pulling in variables, i.e. `{ myVariable }` ?

If that's what you need, then this should work:

```nunjucks
{% block template %}
  <h1>{ {{ page.l10n.introduction.header }} }</h1>
  <div>{ {{ page.l10n.introduction.text }} }</div>
{% endblock %}
```

I don't understand the `{% mergetags %}` part.

**Comment by walle89** [comment]
About {% meretags %}, the closest thing to this is `@env('production')` for the PHP version. I only want ESP code when I do production build. If I have ESP specific code during development it will mess up the template. 
The issue with environment blocks is that it's not flexible, sometimes I need to test the stage build at the ESP with the ESP code. In order to do that,  I need to either create a new configuration for a new environment, or modify the production configuration to be more like the stage build. I think it's better it's a config setting rather a new config file.

About your suggestion, given your example how can I in developer builds let it generate HTML like this:
```
  <h1>Header 1 test</h1>
  <div><p>Lorem ipsum dolor sit amet....</p></div>
```
And if I do a production build of the exact same template, generate HTML like this:
```
  <h1>{{ page.l10n.introduction.header }}</h1>
  <div>{{ page.l10n.introduction.text }}</div>
```
I guess that's currently not possible out of the box? Also I can't always prefix the variables with `page.`, I need to access variables from the ESP with ESP specific variables like getting the first name of the subscriber `profile.firstname` or the post address `profile.fullPostAddress`. To be able to have real test data while developing and test the template makes it much easier.

For the PHP version I did my own implementation of it. I took the freedom to make it more readable and simplify it a but compared with my solution. This code isn't functional, but if you want me to I can provide you that.

```
<?php
$bladeCompiler->directive('s', function ($var) {
    if($page->mergeTags->enabled AND $page->{$var}) {
          $result = $page->{$var};
    } else {
         $result = $page->mergeTags->print->pre . $var . $page->mergeTags->print->suf;
    }
    return $result;
}

```
Config:
```
<?php
[
    'mergeTags' => [
        'enabled' => true,
        // Syntax for print variable
        'print' => [
            'pre' => '{',
            'suf' => '}',
        ],
]
```
Template usage based on your example:
```
  <h1>@s(l10n.introduction.header)</h1>
  <div>@s(l10n.introduction.text)</div>
```
If mergeTags->enabled is set to true, I will use the `page.` variable, or if it's false or the page varaible dosen't exists, it will print the ESP code like:
```
  <h1>{l10n.introduction.header}</h1>
  <div>{l10n.introduction.text}</div>
```

**Comment by cossssmin** [comment]
> I only want ESP code when I do production build.

Thanks, I understand now. Would making the env available in the `page` variable be enough? 

You could then do something like:

```nunjucks
{% if page.env == 'production' %}
  This shows only when running `maizzle build production`
{% endif %}
```

**Comment by walle89** [comment]
A better solution in my opinion that is more flexible would be something like this:
```
{% if page.mergetag == true %}
  This shows if I have configured merge tags to true
{% endif %}
```
Or just, if possible: 

```
{% mergetags %}
  This shows if I have configured merge tag to true
{% endmergetags %}
```
It's far more flexible and if you want merge tags both for production and stage or any other environment you may want this.

**Comment by cossssmin** [comment]
You can have `page.mergetag` by simply adding it to your environment config file:

```js
// config.production.js

module.exports = {
  mergetag: true,
  // ... the rest of the config
}
```

Then you can use it in your template:

```nunjucks
{% if page.mergetag %}
  This will only show when building for production
{% endif %}
```

**Comment by walle89** [comment]
Yes, I understand. I may have been a bit unclear what I'm asking for. If I put it in a different way:

Is there a way to create a custom function that can be used in the new framework, something similar how to a directive in the PHP version? Or is this what you meant by " This will be added in the next release"?

If you don't think merge tags shouldn't be included as a out-of-the-box feature, I could at least recreate features similar to such as `@s(l10n.introduction.text)`.

**Comment by cossssmin** [comment]
I see. If you don't want to use the config approach, then this would require the ability to write and register your own, custom Nunjucks tags. This isn't possible at the moment, but I'm open to it. 

Ideally, you could add your own Nunjucks tags definitions somewhere, each in its own file. Maizzle would just register them all. Since custom Nunjucks tags aren't that straightforward to write, maybe a base tag would also be provided, as boilerplate.

**Comment by walle89** [comment]
> If you don't want to use the config approach, then this would require the ability to write and register your own, custom Nunjucks tags. 

Just to be clear so that are no misunderstanding, I do want to use a directive (aka Nunjucks tags ) with config.

I want to instead of write this:
```django
{% if page.mergetag %}
  This will only show when building for production
{% endif %}
{% if (page.mergetag) AND (page.l10n.introduction.header) %}
<h1>{{ page.l10n.introduction.header }}</h1>
{% else %}
<h1>{l10n.introduction.header}</h1>
{% endif %}
{% if (page.mergetag) AND (page.l10n.introduction.text) %}
<div>{{ page.l10n.introduction.text }}</div>
{% else %}
<div>{l10n.introduction.text}</div>
{% endif %}
```
It's much easier if that can be replaced to something like this instead
```django
{% if page.mergetag %}
  This will only show when building for production
{% endif %}
<h1>{% mergetag "l10n.introduction.header" %}</h1>
<div>{% margetag "l10n.introduction.text" %}</div>
```
Or if custom filters can be used:
```django
{% if page.mergetag %}
  This will only show when building for production
{% endif %}
<h1>{{ "l10n.introduction.header"|mergetag }}</h1>
<div>{{ "l10n.introduction.text"|mergetag }}</div>
```
The important part is that Nunjucks tags (and/or custom filters) have access to the page variable if it's possible.

**Comment by cossssmin** [comment]
#71 allows adding custom filters and extensions.
