### ISSUE TITLE
[Question] How do I pass custom Tokens when Building email

### ISSUE THREAD

**Issue by Blake32p** [maizzle/framework#100]
Hi, I am trying to create some email templates for Marketo. Marketo uses tokens in this format {{ Token }}. For example, the unsubscribe token is `<a href="{{system.unsubscribeLink}}" target="_blank" class="mktNoTrack">`. When I run **Maizzle build** the href is left blank `<a href target="_blank" class="mktNoTrack">`

How do I pass the token through? Looking through the docs I see how to do it for CSS tags, but I wasn't sure about tokens used in HTML.

**Comment by cossssmin** [comment]
Hi there,

You need to use the `{% raw %}` tag (see [docs](https://mozilla.github.io/nunjucks/templating.html#raw)) and place your `{{ }}` inside it, so that Nunjucks doesn’t try to compile it.

Will publish a tutorial for this soon, it’s probably one of the most asked questions.

**Comment by Blake32p** [comment]
Oh perfect. It makes sense that it was in Nunjucks, I didn't think to look there. Foundation Emails Panini uses {{{{raw}}}} so I should have thought that was the way to go. Thanks for the quick reply, I'm a big fan of Maizzle!

**Comment by cossssmin** [comment]
Added to the docs instead:

https://maizzle.com/docs/templates/#tag-conflicts
