### ISSUE TITLE
Incorrect value for "UI External"

### ISSUE THREAD

**Issue by fabswt** [maizzle/framework#1012]
- Maizzle Version: 4.4.5
- Node.js Version: v19.8.1

I'm new to Maizzle (big fan of Tailwind, so this is exciting!)

`npm run dev` gives me this:

```
✔ Re-built 2 templates in 0.191s
[Browsersync] Access URLs:
 ------------------------------------
       Local: http://localhost:3002
    External: http://172.20.10.2:3002
 ------------------------------------
          UI: http://localhost:3003
 UI External: http://localhost:3003
 ------------------------------------
[Browsersync] Serving files from: build_local
```

I believe that "UI External" is incorrect, it should be: http://172.20.10.2:3003

**Comment by cossssmin** [comment]
It's an issue in BrowserSync, waiting for it to be patched. See here:

https://github.com/BrowserSync/browser-sync/issues/1969

**Comment by cossssmin** [comment]
Closing this for now and we'll just update Browsersync the moment they merge that fix. However it is extremely likely that the next version of Maizzle will stop using Browsersync and migrate to a custom dev server instead.

**Comment by cossssmin** [comment]
https://github.com/maizzle/framework/pull/1122

It got fixed upstream, will be available in the next release 👍
