### ISSUE TITLE
Parse HTML string to tailwind components in email

### ISSUE THREAD

**Issue by paulmbw** [maizzle/framework#1030]
- Maizzle Version: "@maizzle/framework": "^4.4.6"
- Node.js Version: 19.3.0

Hi there,

To start off, this is not so much an issue but more of a feature request. Perhaps I may need to set this as a discussion rather than an issue? Forgive me!

Moving on, the TL;DR: is there a way to parse HTML using Maizzle? I have a frontend application that allows you to customise a newsletter (change the border, font, flex/grid, add images/ videos) all using tailwind. Once you're done, the app sends the html result (using `renderToStaticMarkup`) via http to an endpoint in my backend service. The service accepts the content and builds a html file which I intend on sending the newsletter via email.

The only thing is, as expected, the raw HTML is being displayed in the html file that is generated by maizzle as shown below:
<img width="878" alt="Screenshot 2023-07-05 at 16 39 26" src="https://github.com/maizzle/framework/assets/9769730/b5847809-8fbf-4fbf-84f9-bb3618899e0b">

Is there a way to parse the above string and render the html with all the styles?

**Comment by paulmbw** [comment]
Discussion may continue [here](https://github.com/orgs/maizzle/discussions/1031), will close this as it's not so much an issue

**Comment by cossssmin** [comment]
Toggling an issue like that won’t earn you any favors. Locked.
