### ISSUE TITLE
Cannot use `unescapeDelimiters`

### ISSUE THREAD

**Issue by heychazza** [maizzle/framework#1045]
Hi all,

When setting the `unescapeDelimiters` to `["{!!", "!!}"]` (For PHP blade), I get the following error:
```
⚠ <css input>:2:5: Unknown word
```

Which means that the template fails to compile. How can I fix this? 

- Maizzle Version: 4.4.7
- Node.js Version: 16.20.1

**Comment by cossssmin** [comment]
If you need the compiled HTML email to render a string like `Hello, {!! $name !!}.`, you don't need to add this setting.

You're getting that error because you probably forgot to update your usage of the unescapeDelimiters somewhere - most likely you forgot to change `{{{ page.css }}}` to `{!! page.css !!}` in `src/layouts/main.html`.

But again, what you set in this option is what Maizzle will look for to compile, if you just need to output the string as-is for Blade to later process, there's no need for this as it does not clash with Maizzle's default `{{{ }}}`.

**Comment by heychazza** [comment]
> If you need the compiled HTML email to render a string like `Hello, {!! $name !!}.`, you don't need to add this setting.
> 
> You're getting that error because you probably forgot to update your usage of the unescapeDelimiters somewhere - most likely you forgot to change `{{{ page.css }}}` to `{!! page.css !!}` in `src/layouts/main.html`.
> 
> But again, what you set in this option is what Maizzle will look for to compile, if you just need to output the string as-is for Blade to later process, there's no need for this as it does not clash with Maizzle's default `{{{ }}}`.

Ahh really! Thank you, I was following the tutorial at https://blog.yottahq.com/how-to-send-e-mails-in-laravel-with-tailwind-css-using-maizzle-2a06db1b572c for this, which showed needing to set it.

So I wouldn't need to touch this option?

**Comment by cossssmin** [comment]
Think that author misunderstood what they're for, you can see he never uses `{!! !!}` anywhere in the template. 

`unescapeDelimiters` are only for Maizzle to handle, you'd only change them if they conflict with some other compiler you'll use afterwards. `{!! !!}` is not evaluated by Maizzle, so you can just write it out like any string and it will be kept as-is.

**Comment by heychazza** [comment]
> Think that author misunderstood what they're for, you can see he never uses `{!! !!}` anywhere in the template.
> 
> `unescapeDelimiters` are only for Maizzle to handle, you'd only change them if they conflict with some other compiler you'll use afterwards. `{!! !!}` is not evaluated by Maizzle, so you can just write it out like any string and it will be kept as-is.

Thanks for such a quick response! That's superb then, I will remove the escape config option. Looking forward to finally using Maizzle in a project :)

Do you have any way that I can donate? Spectacular job on building this. I'll DM you on Twitter regarding something too.

**Comment by cossssmin** [comment]
You're welcome, happy to help :)
