### ISSUE TITLE
Closing tags inside <outlook> outputs empty

### ISSUE THREAD

**Issue by julzmon** [maizzle/framework#1050]
- Maizzle Version: 4.5.0
- Node.js Version: 16.20.0

I'm having issues with closing tags inside <outlook> tag. Seems like any closing tag that I put inside the <outlook> tag

```
<outlook></td></tr></table></outlook>
```
The dev/build output is always empty
```
<!--[if mso]><![endif]-->
```

**Comment by cossssmin** [comment]
Yeah, unfortunately you can’t use the outlook tags like that, they only work with conplete opened/closed tag pairs.
