### ISSUE TITLE
Typescript Typings

### ISSUE THREAD

**Issue by gaurishhs** [maizzle/framework#1052]
I'm willing to write the types for Typescript support. Just let me know, If you're ok with it or should i create a separate package.

_Originally posted by @gaurishhs in https://github.com/maizzle/framework/issues/1051#issuecomment-1685079377_

**Comment by gaurishhs** [comment]
I have written the types btw, https://github.com/maizzle/framework/commit/c509b316031d6ae1d6406100194058e6ead0e5c9 

Waiting for your approval to open a PR

**Comment by cossssmin** [comment]
Would be awesome to get help with that, yes! Please do open a PR and let's continue the conversation there, thanks! 

BTW, would be really useful to add types [like in Tailwind](https://tailwindcss.com/docs/configuration), so that we get suggestions in the config files too 🫣
