### ISSUE TITLE
Cannot get same output for local and production

### ISSUE THREAD

**Issue by hteumeuleu** [maizzle/framework#1056]
- Maizzle Version: 4.5.0
- Node.js Version: 18.16.0

I'd like to get the exact same code output for local and production builds. What I did:

1. `npx degit maizzle/maizzle my-project`
2. In `config.js`, add the following lines taken from `config.production.js`:

```js
  inlineCSS: true,
  removeUnusedCSS: true,
  shorthandCSS: true,
  prettify: true,
```

If I run `npm run dev`,  the output in `build_local` looks like the following excerpt:

```html
<style>
    .w-\[552px\] {
      width: 552px
    }
</style>
<h1 class="sm: sm:" style="margin: 0 0 16px; font-size: 36px; color: #fff">
     Lorem ipsum dolor
</h1>
```

If I run `npm run build`, the output in `build_production` looks like the following excerpt:

```html
<style>
    .hover-text-indigo-500:hover {
      color: #6366f1 !important
    }
    .hover-important-text-decoration-underline:hover {
      text-decoration: underline !important
    }
</style>
<h1 class="sm-text-3xl sm-leading-10" style="margin: 0 0 16px; font-size: 36px; color: #fff">
     Lorem ipsum dolor
</h1>
```

I would like the local build to be the exact same as the production build. Is that possible?

**Comment by cossssmin** [comment]
Hey yup, it's `safeClassNames` that only runs when not developing locally:

https://maizzle.com/docs/transformers/safe-class-names

You need to add it to your `config.js`:

```diff
inlineCSS: true,
removeUnusedCSS: true,
shorthandCSS: true,
prettify: true,
+ safeClassNames: true,
```

I'll try to make that more clear in the docs, thanks for bringing it up!

**Comment by hteumeuleu** [comment]
Thank you!
