### ISSUE TITLE
spinner.warn: glob is not a function (outdated dependencies)

### ISSUE THREAD

**Issue by stenreijers** [maizzle/framework#1069]
- Maizzle Version: latest
- Node.js Version: latest

# Description
When using maizzle in workspace mode, different versions of `glob` give issues since the export signature of `glob` changed over time. The package `glob-promise` in `@maizzle/framework` is too old and will throw an error in that case.

# Output
```
⚠ glob is not a function
✔ Built 0 templates in 0.183s
```

# Result
No templates are built at all. 

# Resolve
To resolve the issue is very easy, maizzle should bump `glob-promise` to ^6.0.0, since 4.1.0 (currently in package.json) is extremly old.

# Thoughts
Perhaps it makes sense to update other dependencies too, since some are quite old.

**Comment by stenreijers** [comment]
List of outdated dependencies:

```
Package                           Current  Wanted  Latest  Location                                       Depended by
color-shorthand-hex-to-six-digit    3.1.0   3.1.0  5.0.13  node_modules/color-shorthand-hex-to-six-digit  maizzle-framework
email-comb                          5.2.1   5.3.1  7.0.17  node_modules/email-comb                        maizzle-framework
fs-extra                           10.1.0  10.1.0  11.1.1  node_modules/fs-extra                          maizzle-framework
glob-promise                        4.2.2   4.2.2   6.0.5  node_modules/glob-promise                      maizzle-framework
html-crush                          4.2.0   4.2.0  6.0.15  node_modules/html-crush                        maizzle-framework
is-url-superb                       5.0.0   5.0.0   6.1.0  node_modules/is-url-superb                     maizzle-framework
ora                                 5.4.1   5.4.1   7.0.1  node_modules/ora                               maizzle-framework
query-string                        7.1.3   7.1.3   8.1.0  node_modules/query-string                      maizzle-framework
string-remove-widows                2.1.0   2.1.0  4.0.17  node_modules/string-remove-widows              maizzle-framework
string-strip-html                   8.5.0   8.5.0  13.4.3  node_modules/string-strip-html                 maizzle-framework
xo                                 0.39.1  0.39.1  0.56.0  node_modules/xo                                maizzle-framework
```

**Comment by cossssmin** [comment]
`glob-promise` 6.x doesn’t support Node 14, so that would require a major version release in Maizzle. I reckon that’s the issue with workspaces?

The other packages you mentioned are now ESM only on their latest versions, and Maizzle is not ESM, yet. This is more complicated to do as it requires a major rewrite of the framework, so it’ll be a while until we get there I think.

**Comment by holy1crab** [comment]
![image](https://github.com/maizzle/framework/assets/939332/55902c4d-52d9-45c9-a92d-bea15c73070b)

My issue is related. I get this error after updating to version `4.6.0`. As mentioned above `string-strip-html` is outdated and actually doesn't have exports of interfaces. And yes - latest versions are pure ESM packages of this library, but the author has back-ported changes in version `8.5.0` (this version exports interfaces). 

https://github.com/codsen/codsen/blob/main/packages/string-strip-html/CHANGELOG.md

```
8.5.0 (2023-05-14)
Features
back-porting the latest v13.4.0 to CJS and releasing as non-pure ESM (no type: module in package.json).
```
also this
```
11.2.0 (2022-08-12)
Features
export types ([11b5fb9](https://github.com/codsen/codsen/commit/11b5fb936ce20e0a77c3a09806773e1cd7695c50))
```

for now I resolved this by adding a line to `package.json`:
```
"overrides": {
    "string-strip-html": "^8.5.0"
  },
```

**Comment by cossssmin** [comment]
@holy1crab you should be getting `string-strip-html@8.5.0` in Maizzle 4.6.0, as we're pinning a minor release version:

https://github.com/maizzle/framework/blob/63011308ca1c58e203ba0b29e0903bcd9192486b/package.json#L77

<img width="404" alt="image" src="https://github.com/maizzle/framework/assets/1656595/9a252fa8-68cd-42fa-b5c9-35f5ba5e5f82">

**Comment by holy1crab** [comment]
@cossssmin Ah, ok, looks like I messed up with dependencies. 

Also, I noticed that current types do not cover actual options. For example:
```
function render(html: string, options?: RenderOptions): Promise<RenderOutput>;
```
`maizzle.filters` is required, but actually it's possible to leave empty
`tailwind.confid` accepts only `string`, but should be an `object` option as well
This is just a couple of examples I noticed from my code, I haven't inspected it completely.

Thanks for the library :)

**Comment by cossssmin** [comment]
Working on improving types, thank you! :)

**Comment by harrybawsac** [comment]
I'm still running into the issue of no production builds.

```
⚠ glob is not a function
✔ Built 0 templates in 0.183s
```

Is there a solution?

**Comment by stenreijers** [comment]
I guess with maizzle 5.0 most issues are fixed, since the repo changed to esm.
