### ISSUE TITLE
Using maizzle.config.js as a config file

### ISSUE THREAD

**Issue by tylermmorton** [maizzle/framework#1077]
Hello, I'm integrating maizzle into a monorepo project with many different config files in the root directory. It would be great to be able to use `maizzle.config.js` as the config name to align with other tool configs like tailwind.config.js but I can't seem to figure out how.

 I'm using the CLI to trigger the build:
```
npx maizzle build
```

Currently, in a directory with many configs:
```
/Brewfile
/config.js // <- maizzle config
/Dockerfile
/tailwind.config.js
/go.mod
/package.json
```

I hit an error when renaming the config to `maizzle.config.js` : 

```
⠋ Building emails...⠙ No template sources defined in `build.templates`, check your config.js file
/node_modules/@maizzle/framework/src/generators/output/to-disk.js:37
      throw new Error(`No template sources defined in \`build.templates\`, check your ${configFileName} file`)
```

Is there a CLI flag or environment variable I can use to set the config path? `npx maizzle build --help` doesn't have any details.

If this isn't something thats currently possible I'm happy to open a pull if you can point me in the right direction.

Thank you!

**Comment by cossssmin** [comment]
Yes we should have a flag for the CLI in @maizzle/cli for this, maybe something like  `maizzle build —config [filepath]`. 

Using file names like that would look pretty weird considering the file name and CLI-command relationship, ie it would mean having `maizzle.config.production.js` etc. Plus it’d be a breaking change or we’d have to support both until v5 which may be confusing.

Feel free to start a PR if you want, and we can work together from there. Just a heads up I’ll be offline for a few days, moving houses so it’ll take a few days before I’m back to it 😇
