### ISSUE TITLE
how to pass different attributes for dev environment and production environment

### ISSUE THREAD

**Issue by Ankitb09** [maizzle/framework#1078]
### Discussed in https://github.com/orgs/maizzle/discussions/1068

<div type='discussions-op-text'>

<sup>Originally posted by **Ankitb09** September 14, 2023</sup>
Hello All,

Could you please help me to pass different attributes for dev environment and production environment, for example:-

I have a very simple spacer component:-

```
<tr>
  <td>
        <hr attributes class="border-0 text-white min-h-full" />
  </td>
</tr>
```
this is how i am consuming this:-
` <x-spacer class="{variables.spacer}" />`

But i want to pass a class name for example "margin-top-x2" for dev environment and a variable for production environment:-
for Dev i need `<x-spacer class="DESIRED_CLASSNAME_HERE" />` and
for Prod i need ` <x-spacer class="{variables.spacer}" />`

Could you guys please help me with this?</div>

**Comment by cossssmin** [comment]
Let's keep the discussion in Discussions please, replied there.
