### ISSUE TITLE
Code between <!--[if mso]> <![endif]--> is not processed

### ISSUE THREAD

**Issue by rrowinskiflaconi** [maizzle/framework#1088]
- Maizzle Version: 4.6.0
- Node.js Version: 16.20.2

If I wrap the code in mso specific if/endif it is excluded by plugins such as inlineCSS. How to overcome this? I'm trying to make buttons that stretch to full width on Outlook

**Comment by cossssmin** [comment]
`<!--[if mso]>...<![endif]-->` is a string in HTML, the transformers like the CSS inliner need real HTML tags to work with. The only option there is to manually write your inline styles in the comment.
