### ISSUE TITLE
Templates SubFolder support

### ISSUE THREAD

**Issue by shahbazkrispx** [maizzle/framework#1089]
- Maizzle Version: Latest
- Node.js Version: 20

**Comment by cossssmin** [comment]
Can you elaborate, please? You can already use nested folders in your templates source.

**Comment by shahbazkrispx** [comment]
Yes i can use the nested folder in templates but i need to define them in config.js file then it will build files from that folder. 
Explanation:
 src/templates/promotion  then in config.js file i just define 
 `templates: {
      source: 'src/templates/**/*.html',
      destination: {
        path: 'build_local',
      },
      assets: {
        source: 'src/templates/**/images',
        destination: 'images',
      },
    },`

**Comment by cossssmin** [comment]
`source` must be a directory path, not a glob with a file extension. It'll automatically watch and build templates in nested folders there. Read the docs: https://maizzle.com/docs/configuration/templates#source

**Comment by cossssmin** [comment]
That being said, I think we should move towards supporting globs in there.

For the next major release (v5), I'm looking into making this (breaking) change:

```diff
module.exports = {
  build: {
    templates: {
-      source: 'src/templates',
-      filetypes: 'html'
+      source: 'src/templates/**/*.{html,...}',
    }
  }
}
```

Makes more sense and it's like what Tailwind CSS does (i.e. their `content` config key).

Not planning on doing this for v4.x though, so I'll go ahead and close the issue if you don't mind.

**Comment by shahbazkrispx** [comment]
That will be great. Thanks 👍
