### ISSUE TITLE
DeprecationWarning: The `punycode` module is deprecated. Please use a userland alternative instead.

### ISSUE THREAD

**Issue by happysalada** [maizzle/framework#1094]
- Maizzle Version: 4.6.1
- Node.js Version: 21.2.0

The warning is probably happening with node 20.x too

The warning in the issue gets displayed when running maizzle build production.

I'm just letting you know about the warning, it doesn't bother me.

Thanks a lot for maizzle!

**Comment by cossssmin** [comment]
Can you run `npm list punycode` in a Maizzle project and let me know what you get?

This is what I'm getting (though on Node v18.12.1):

```
$ npm list punycode
maizzle@ F:\DEV\open-source\maizzle\maizzle
└── (empty)
```

**Comment by happysalada** [comment]
I'm using pnpm but the command you suggested didn't return anything.
here is a bit more output
```
❯ : maizzle --version
Framework v4.6.1
CLI v1.5.7
email-templates on  master via  via ❄  impure (devshell-env) on ☁  (auto)
❯ : build

> @ build /Users/raphael/dev/email-templates
> maizzle build production

⠋ Building emails...(node:34352) [DEP0040] DeprecationWarning: The `punycode` module is deprecated. Please use a userland alternative instead.
(Use `node --trace-deprecation ...` to show where the warning was created)
✔ Built 19 templates in 3.986s
```

**Comment by cossssmin** [comment]
Might have to do with pnpm, Maizzle doesn’t use that dependency, I’ll have to look into it.

**Comment by happysalada** [comment]
It could be a pnpm issue, let me close this then. Thank you for your quick response !

**Comment by cossssmin** [comment]
https://nodejs.org/api/punycode.html

One of our dependencies must be using it without listing it as a dependency since it's bundled in Node. It's deprecated starting with Node 21, thus the deprecation warning.

**Comment by happysalada** [comment]
Ah interesting !
Im happy to test again and report if you have any updates on this.
Thanks for taking a look !
