### ISSUE TITLE
Installation BUG

### ISSUE THREAD

**Issue by priyangsubanerjee** [maizzle/framework#1127]
- Maizzle Version: `latest`
- Node.js Version: 20.5.1

- command: `npx degit maizzle/maizzle . `

**Error:** 

```
! could not fetch remote https://github.com/maizzle/maizzle
! could not find commit hash for HEAD
```

Screenshot

<img width="552" alt="Screenshot 2024-01-05 at 9 46 02 AM" src="https://github.com/maizzle/framework/assets/78071484/43be17fa-3d7a-4fa5-96ea-39379a8d8da2">

**Comment by cossssmin** [comment]
It works fine, must be a local issue. Maybe have a look here, it's not to do with Maizzle itself:

https://github.com/Rich-Harris/degit/issues/37
