### ISSUE TITLE
Starter: Yarn Needs More Dependencies

### ISSUE THREAD

**Issue by tim-elam** [maizzle/framework#1161]
- Maizzle Version: 4.7.3
- Node.js Version: 18.12.1
- Yarn Version: 4.0.2

Maizzle starter (when installed via Yarn) needs these explicit dependencies.

```
    "glob": "^8",
    "postcss": "latest",
    "posthtml": "latest",
    "tailwindcss": "latest",
``` 

Glob needs to be explicitly specified to ^8, because glob-promise only specifies it as a peerDependency and cannot handle the breaking changes in Glob v9.

See also:
https://github.com/ahmadnassri/node-glob-promise/issues/204#issuecomment-1912674298

**Comment by cossssmin** [comment]
Sounds like this needs to be fixed upstream in `glob-promise` though?

**Comment by tim-elam** [comment]
In glob v9, the API was rewritten to use Promises instead of callbacks, so I think you _should_ be able to replace 
```
const glob = require('glob-promise')
```
with
```
const {glob} = require('glob')

```
in `to-disk.js` and replace the `glob-promise` dependency with a dependency or  peerDependency on `glob >= 9`.

That's what Storybook did, anyway: https://github.com/storybookjs/storybook/commit/ac16a384dee834ac20659b0f3de8ce07cc75e21f#diff-2863b3fa2d25f11b17809621643879a0efe0d28b9512def8fd6708b6a5eb3875L3

**Comment by cossssmin** [comment]
Moving to `fast-glob` instead, already using that for the fure Maizzle 5.

Will release a patch today, do let me know how it works for you 👍

**Comment by cossssmin** [comment]
Released `v4.7.5`:

https://github.com/maizzle/framework/releases/tag/v4.7.5

**Comment by tim-elam** [comment]
Works like a charm. Thank you!

**Comment by cossssmin** [comment]
Thanks! 😊
