### ISSUE TITLE
maizzle new [project] installs v0.8, not v0.9

### ISSUE THREAD

**Issue by Joobs** [maizzle/framework#117]
Framework v0.8.0
CLI v0.5.0

What's the process for updating/installing a new project to the latest version of Maizzle?

I'm trying to use the new markdown features, but my `<markdown>` tags are being ignored (literal tag is displayed in the html).

It seems my Framework is stuck on 0.8.0, shouldn't `maizzle new [project]` install version 0.9.1?

I deleted my `package.lock.json` and increased the version in `package.json` and did a new `npm install` to get the latest version.

**Comment by cossssmin** [comment]
> I deleted my `package.lock.json` and increased the version in `package.json` and did a new `npm install` to get the latest version.

Yup, just as with any Node.js package, to update dependencies, you just need to: 

- update the version of the dependency in `package.json` (in our case, `@maizzle/framework)
- run `npm install`

Still, [`package-lock.json`](https://github.com/maizzle/maizzle/blob/master/package-lock.json) has Maizzle at `0.8.0` so I'll bump it in the starter asap. Thanks!

**Comment by cossssmin** [comment]
Fixed in https://github.com/maizzle/maizzle/pull/20, `maizzle new` should now install the latest framework version 👍

I've also configured Dependabot to check and bump dependency versions weekly, it was set to monthly (think that's the default).

**Comment by cossssmin** [comment]
By the way, the new Markdown plugin we're now using still has some [issues](https://github.com/OzymandiasTheGreat/posthtml-markdown/issues?q=is%3Aissue+is%3Aclosed) - mostly concerning code blocks. We're working together with PostHTML to fix them, and will most likely transition to [`posthtml-md2html`](https://github.com/posthtml/posthtml-md2html) once they're fixed.
