### ISSUE TITLE
Pass data to components inside other components

### ISSUE THREAD

**Issue by dagadbm** [maizzle/framework#119]
I would like to know if its possible to pass data values to other components like so:

```
// on component a.njk
{% component "src/components/common/spacer.njk", {
  spacing: "{{ data.spacing }}"
} %} {% endcomponent %}
```

```
// on component that uses a.nnjk
{% component "src/a.njk", {
 spacing: "pt-16"
} %} {% endcomponent %}

This doesnt work however.

Is there a way to do it?

**Comment by cossssmin** [comment]
The second argument that you pass to the `component` tag is an object, so it should work, yes.

However you're passing a string there in `a.njk`, try this:

```nunjucks
{% component "src/components/common/spacer.njk", {
  spacing: data.spacing
} %} {% endcomponent %}
```

**Comment by dagadbm** [comment]
thx!

I ended up refactoring a bit but its good to know it works.
i think these kind of "development patterns" are missing to be documeted
