### ISSUE TITLE
Gmail strips style tags due to no-commas color functions

### ISSUE THREAD

**Issue by justinlettau** [maizzle/framework#1192]
- Maizzle Version: 4.7.6
- Node.js Version: 20.11.0

It seems Gmail strips out the style tag for any element if it contains any no-commas color functions ([see here](https://stackoverflow.com/a/72691910/6693291)). Maizzle's default production config appears to output this snytax (exmaple: `background-color: rgb(248 250 252 / 1)`). Any chance Maizzle could output the more compatiable syntax by default?

For now, I've added [`postcss-preset-env`](https://github.com/csstools/postcss-plugins/tree/main/plugin-packs/postcss-preset-env) via the following to my `config.production.js`. This works to correctly output a more compatiable syntax (exmaple: `background-color: rgba(248, 250, 252, 1)`). Note, [`postcss-color-rgb`](https://github.com/dmarchena/postcss-color-rgb) did _not_ work.

```diff
module.exports = {
  build: {
    postcss: {
      plugins: [require('postcss-preset-env')()],
    },
    // ...
  },
  // ...
};
```

Thanks!

**Comment by cossssmin** [comment]
Are you using the [`tailwind.config.js`](https://github.com/maizzle/maizzle/blob/master/tailwind.config.js) we provide? [We explicitly disable color opacity plugins](https://github.com/maizzle/maizzle/blob/ca65ef84e4b1eb22e673c2d0e7d3ddc238e40ecc/tailwind.config.js#L124-L131) so that Tailwind outputs HEX colors, you don't need to add any other plugins.

```js
/** @type {import('tailwindcss').Config} */
module.exports = {
  // theme: { ... },
  corePlugins: {
    preflight: false,
    backgroundOpacity: false,
    borderOpacity: false,
    divideOpacity: false,
    placeholderOpacity: false,
    textOpacity: false,
  },
  // plugins: [...]
}
```

**Comment by justinlettau** [comment]
Yes, I am using the provided `tailwind.config.js`. However, upon further looking ... it does seem the Maizzle starter correctly output the HEX colors. I'm trying to use Maizzle in a monorepo, with other apps and tailwind configs; So I'm thinking there might just be something conflicting/overriding in my repo. Thanks.
