### ISSUE TITLE
Using props as arbitrary values

### ISSUE THREAD

**Issue by de-don** [maizzle/framework#1262]
- Maizzle Version: 4.8.5
- Node.js Version: 18.18.2

If I am using my component props inside template to combine arbitrary class, like `max-w-[200px]` it not generates tailwind class for that :(

```html
<script props>
  module.exports = {
    width: props.width || "632px",
  };
</script>

<div class="container mx-auto max-w-[{{ width }}]"></div>
```

It compiles to:
```html
<div class="container mx-auto max-w-[632px]"></div>
```
but without related styles

**Comment by cossssmin** [comment]
Tailwind needs to see the entire class name in order to generate the CSS:

https://tailwindcss.com/docs/content-configuration#dynamic-class-names
