### ISSUE TITLE
Transformer "removeUnusedCSS" add unwanted line break in large build file

### ISSUE THREAD

**Issue by Frolipon** [maizzle/framework#1305]
- Maizzle Version: 4.4.4
- Node.js Version: 16.15.0

I found that when using the transformer `removeUnusedCss` on very large files (several thousands lines of code in the build file), some unwanted line-breaks does appear in the middle of lines.
Weirdly, the line-break does not appear at the same line for my colleague (but it does appear). For me it's around line 5455, and for hime around line 5980).
I tried adding a few lines or a few characters, but the problem still does appear at the same position in code (so a few lines down). 
The project has a lot of components.
If I switch the position of the components where the problem appears (let's call it `component A`) with another component (let's call it `component B`), then the problem appears in `component B`
![Capture d'ecran 2024-07-24 a 13 46 43](https://github.com/user-attachments/assets/b05ba797-ed30-4107-8df3-f0ea9fdd3d2e)

I didn't enable `prettify`

**Comment by Frolipon** [comment]
I don't think so.

If I have something like:

```
<component_a />
<component_b />
<component_c />
<component_d />
```

The problem will appear in the build file somewhere in the code of `<component_d />`

But if I write this:

```
<component_d />
<component_b />
<component_c />
<component_a />
```

then the problem will show in `<component_a /> `

So I my best guess is that there is a point where there is too much characters and a line-break is inserted, but I could be wrong.

And about Maizzle 5, that's mean. Now I'm super excited about it and can't wait to try it 🤩

**Comment by cossssmin** [comment]
Might be worth [opening an issue](https://github.com/codsen/codsen/issues?q=sort%3Aupdated-desc+is%3Aissue+is%3Aopen) with `email-comb`, though it's a pretty rare scenario so I wouldn't get my hopes up too high... nothing we can really do about it on our side, sorry.
