### ISSUE TITLE
Error when integrating into existing monorepo 

### ISSUE THREAD

**Issue by juds-lee** [maizzle/framework#1340]
- Node.js Version: 18.20.4
- Maizzle Version: 4.8.7
Hi there! I am trying to integrate maizzle into an existing monorepo project. When running `npx maizzle serve` i  get the error
```
throw new Error(`No template sources defined in \`build.templates\`, check your ${configFileName} file`)^
Error: No template sources defined in `build.templates`, check your config.js file 
```
and when I tried running `npx maizzle serve maizzle.config.js` I get  
```
throw new Error(`Failed to load config file for \`${env}\` environment, do you have one of these files in your project root?\n\n${modulesToTry.join('\n')}`)
Error: Failed to load config file for `maizzle.config.js` environment, do you have one of these files in your project root?

./maizzle.config.maizzle.config.js.js
./maizzle.config.maizzle.config.js.cjs
./config.maizzle.config.js.js
./config.maizzle.config.js.cjs
```
I have maizzle.config.js in my root and my build.templates.source defined. 
I am not sure how to move forward with this and would appreciate any direction.

**Comment by cossssmin** [comment]
Can you share (even privately) a repo that reproduces the issue? I have no experience with monorepos but we'll get it sorted somehow. Would the `--bin` flag work for you?

https://maizzle.com/docs/cli#bin-flag

**Comment by juds-lee** [comment]
I've added you as a collaborator, thank you so much. 
I was not able to get it working with the `--bin` flag.`

**Comment by cossssmin** [comment]
Thanks for adding me, noticed the issue.

You have `"type": "module",` in `package.json` but Maizzle 4.x is CJS only so it won't work (it will with Maizzle 5 though).

If you remove it (and make sure you have Maizzle installed as a dependency - not seeing it there either) you'll see it works.

**Comment by juds-lee** [comment]
This resolved the errors. Thank you very much!
