### ISSUE TITLE
Preview in the browser does not get updated even after beforeCreate is being called

### ISSUE THREAD

**Issue by ASHFAQPATWARI** [maizzle/framework#1344]
- Maizzle Version: 5.0.0-beta.23
- Node.js Version: v20.9.0

I am trying to add i18next to the maizzle config.
I have added a translations.json file and added it to server watch array. My code to add i18next looks like this

    import i18next from "i18next";
       
      /** @type {import('@maizzle/framework').Config} */
      export default {
        t: i18next.t,
        lang: "en",
        build: {
          content: ["src/templates/**/*.html"],
          static: {
            source: ["src/images/**/*.*"],
            destination: "images",
          },
        },
        server: {
          port: 8080,
          reportFileSize: true,
          watch: ["./src/images/translations.json"],
        },
        async beforeCreate({ config }) {
          try {
            // TODO: setting config should work from here as expected. Commenting code here as config is coming as undefined
            // config.language = process.env.TEMPLATELANGUAGE || "en";
            console.log(
              "------------------------------------- running beforecreate --------------------------------"
            );
            
          const translations = await import("./src/images/translations.json", {
            assert: { type: "json" },
          });
          const lang = process.env.TEMPLATELANGUAGE || "en";
          // Await is important here to not let build advance before i18next has had time to finish initialization.
          await i18next.init({
            lng: lang,
            fallbackLng: "en",
            debug: false,
            resources: translations.default,
          });
        } catch (error) {
          console.log("error in config.js beforeCreate", error);
        }
      },
      async beforeRender({ html, config, matter }) {
        console.log("process.env ", process.env.TEMPLATELANGUAGE);
        config.language = process.env.TEMPLATELANGUAGE || "en";
      },
    };
    
**ISSUE 1** - However on changing the translations file, preview in browser is not refreshed not even on refresh. I need to start the server again to see the changes.
**ISSUE 2** - config in beforeCreate function is coming as undefined therefore we cant add anything to it

**Comment by ASHFAQPATWARI** [comment]
@cossssmin Can you suggest a better approach for doing localization in Maizzle.

**Comment by cossssmin** [comment]
`beforeCreate` runs only once, try dynamically importing the JSON in `beforeRender`. I'll look into issue 2, thanks for letting me know 👍
