### ISSUE TITLE
Outlook tag is not working properly

### ISSUE THREAD

**Issue by ivanpajon** [maizzle/framework#1362]
- Maizzle Version: 4.8.9
- Node.js Version: 22.4.1

I think <outlook> tag has some weird behavior. When using legacy comments like `<!--[if (gte mso 9)|(IE)]><![endif]-->` content inside that comments are rendered properly in browser. But when I switch to <outlook> tag the content of some of them are rendered outside the comment and breaks the html tree.

Code with legacy comments:
```html
<!-- Sections -->
<table class="mobile:w-10/12 w-[540px]" border="0" cellpadding="0" cellspacing="0" role="presentation">
  <tbody>
    <!-- Section 1 -->
    <tr>
      <td class="py-5 [font-size:0px]" align="center" valign="top" dir="rtl">
        <!--[if (gte mso 9)|(IE)]>
        <table cellpadding="0" cellspacing="0" border="0" role="presentation" style="width: 100%;">
          <tr>
            <td valign="top" style="width: 255px;">
        <![endif]-->

        <div class="inline-block align-top">
          Some text
        </div>

        <!--[if (gte mso 9)|(IE)]>
            </td><td valign="top" style="width:285px;">
        <![endif]-->

        <div class="inline-block align-top">
          Some image
        </div>

        <!--[if (gte mso 9)|(IE)]>
            </td>
          </tr>
        </table>
        <![endif]-->
      </td>
    </tr>

    <!-- Section 2 -->
    <tr>
      <td class="py-5 [font-size:0px]" align="center" valign="top">Section 2</td>
    </tr>

    <!-- Section 3 -->
    <tr>
      <td class="py-5 [font-size:0px]" align="center" valign="top" dir="rtl">Section 3</td>
    </tr>
  </tbody>
</table>
```

Rendered html in browser (good):
![image](https://github.com/user-attachments/assets/d78a9015-302e-4380-96a5-c53bdbfd51ea)

Code with outlook tags:
```html
<!-- Sections -->
<table class="mobile:w-10/12 w-[540px]" border="0" cellpadding="0" cellspacing="0" role="presentation">
  <tbody>
    <!-- Section 1 -->
    <tr>
      <td class="py-5 [font-size:0px]" align="center" valign="top" dir="rtl">
        <outlook gte="2000">
        <table cellpadding="0" cellspacing="0" border="0" role="presentation" style="width: 100%;">
          <tr>
            <td valign="top" style="width: 255px;">
        </outlook>

        <div class="inline-block align-top">
          Some text
        </div>

        <outlook gte="2000">
            </td><td valign="top" style="width:285px;">
        </outlook>

        <div class="inline-block align-top">
          Some image
        </div>

        <outlook gte="2000">
            </td>
          </tr>
        </table>
        </outlook>
      </td>
    </tr>

    <!-- Section 2 -->
    <tr>
      <td class="py-5 [font-size:0px]" align="center" valign="top">Section 2</td>
    </tr>

    <!-- Section 3 -->
    <tr>
      <td class="py-5 [font-size:0px]" align="center" valign="top" dir="rtl">Section 3</td>
    </tr>
  </tbody>
</table>
```

Rendered html in browser (bad):
![image](https://github.com/user-attachments/assets/e45d081d-aed0-48c8-857d-f24b3ae3e5d0)

And also would be nice to have posibility to specify IE in outlook tag.

**Comment by cossssmin** [comment]
Unfortunately for now it can’t work like that, the parser in PostHTML doesn’t support not closing tags out of the box, it’ll close them automatically. That’s why we don’t have such examples in the tag’s docs.

The outlook tag was originally meant only for wrapping text or HTML elements (with tags properly closed), but if we can find a way to make it work as you described, I’d be more than happy to do it :)

**Comment by cossssmin** [comment]
> And also would be nice to have posibility to specify IE in outlook tag.

What would be the use case? All Outlooks that support MSO conditionals (2006-2021) work with the current `if mso` statement.

**Comment by ivanpajon** [comment]
> 
> What would be the use case? All Outlooks that support MSO conditionals (2006-2021) work with the current `if mso` statement.

I'm not an expert in html emails, but most examples I found use `<!--[if (gte mso 9)|(IE)]>` but I don't know if it is really necessary the "IE".
