### ISSUE TITLE
5.x: Option to define different front matter for dev and prod

### ISSUE THREAD

**Issue by maxgratz** [maizzle/framework#1373]
- Maizzle Version: 5.0.0-beta.26

I just recently started using Maizzle - **my workflow for creating a transactional email template is as following:**

1. Create a template in Maizzle with example data in the front matter of the template to be able to view an example email result in the browser when using `maizzle serve`
2. When I'm satisfied with my template, I first replace all my front matter in the template manually with e.g. `user_surname: '@{{user_surname}}'` to have an HTML file in the end with placeholders that I can replace dynamically in my email sending service.
3. I run `maizzle build production` and copy the resulting HTML file to my email sending service.

The email sending service then reads the HTML from the copied file, replaces all placeholders with a regex and sends the email.

**What would be my ideal workflow:**
- Define separate front matter in my template for development (example data) and production (placeholders)
-> No need to manually replace the front matter when moving to production

Maybe I am missing something, but I didn't find anything regarding this in the documentation.
If this is somehow possible, please show me how. If not, this would make a terrific feature in my opinion.

**Comment by cossssmin** [comment]
Front Matter can only be defined once at the top of a Template, so you could define them in a structure:

```yaml
---
user_surname:
  local: 'Smith'
  production: '{{ user_surname }}'
---
```

Then you could use them like this:

```hbs
{{ page.env === 'local' ? page.user_surname.local : page.user_surname.production }}
```

Or, with Maizzle 5 [`<env>` tags](https://next.maizzle.com/docs/tags#env):

```html
<env:local>{{ page.user_surname.local }}</env:local>
<env:production>{{ page.user_surname.production }}</env:production>
```

When developing locally with `maizzle serve`, the `page.env` variable is `local`. See [Environments](https://next.maizzle.com/docs/environments) docs.

Also, now in Maizzle 5 you don't need to do `@{{ }}` to not parse expressions/preseve the curly braces - as long as what's inside isn't defined, [it will be output as-is](https://next.maizzle.com/docs/expressions#undefined-variables).

If possible though, it would be much easier if you define these in your `config.*.js` files, so they're organized per environment/build command 👍

**Comment by maxgratz** [comment]
Thank you for the quick answer, that works for me! ☺️
