### ISSUE TITLE
prevent-widows affecting class names while using maizzle serve

### ISSUE THREAD

**Issue by Sgouws** [maizzle/framework#1375]
- Maizzle Framework Version: v4.8.9
- Maizzle CLI Version: v1.5.8
- Node.js Version: v18.20.4

`prevent-widows` is adding a `nbsp;` between class name declarations within a link nested within a paragraph tag, when using `maizzle serve`.
To replicate:
```
<p class="p-0 m-0 text-gray text-left text-base leading-6 font-sans" prevent-widows>
    <a href="https://www.example.com" class="underline font-bold">
        Example Window Test
    </a>
</p>
```

This results in:
```
<p class="p-0 m-0 text-gray text-left text-base leading-6 font-sans" style="margin:0em;padding:0em;text-align:left;font-family:-apple-system,BlinkMacSystemFont,'Segoe UI',Arial,Helvetica,sans-serif;font-size:1em;line-height:1.5em;color:#4a4b4a;"> 
     <a href="https://www.example.com" class="underline&nbsp;font-bold"> 
         Example Window&nbsp;Test 
     </a>
</p>
```

**Comment by cossssmin** [comment]
Add it to the `<a>` tag if possible, it's an issue with the [library](https://github.com/codsen/codsen/tree/main/packages/string-remove-widows) we're using. I'll consider moving away from that in Maizzle 5 and handle this through a PostHTML transformer instead.

**Comment by cossssmin** [comment]
You could also try using the [`minWordCount`](https://maizzle.com/docs/transformers/widows#minwordcount) option, but the way the library tokenizes strings means that you'd need to set it to `5`, which wouldn't really help in your case I think...

**Comment by cossssmin** [comment]
Alright, we now use [`posthtml-widows`](https://github.com/posthtml/posthtml-widows) in Maizzle [v5.0.0-beta.28](https://github.com/maizzle/framework/releases/tag/v5.0.0-beta.28), I'll port it to v4.x once we get v5 out 👍

**Comment by Sgouws** [comment]
Amazing, thanks for the detailed explanation too!
