### ISSUE TITLE
5.x: Current template info in "beforeRender" when using "maizzle serve"

### ISSUE THREAD

**Issue by rikzwarthoff** [maizzle/framework#1384]
- Maizzle Version: v5.0.0-beta.32
- Node.js Version: v22.11.0

I was trying out the v5, current template is missing from build config in "beforeRender" on "maizzle serve". I wanted to parse a json file base on the template name in "beforeRender" to apply to the template. I believe in v4 the current template is available in "beforeRender" when using "maizzle serve". Works fine when running "maizzle build".

https://next.maizzle.com/docs/templates#current-template

**Comment by cossssmin** [comment]
Will have a look and fix it, thanks!

**Comment by cossssmin** [comment]
Found the issue and fixed it, will be available in the next beta release - thanks again.

**Comment by cossssmin** [comment]
Published [v5.0.0-beta.33](https://github.com/maizzle/framework/releases/tag/v5.0.0-beta.33), let me know how it goes 👍

**Comment by rikzwarthoff** [comment]
I've tested it out, it only works on re-render, not initial render.

When I go to the page of the template the first time it's empty, if i do make a change and save it. Then it's available.
But if I then go to a different template, the old template path is there.

So in short it's only correct on re-render at the moment.

**Comment by cossssmin** [comment]
Ah right, I've only added it to when a file that is being previewed is re-rendered:

https://github.com/maizzle/framework/blob/596f4b2d907f926744ca531fe073248719bfe69a/src/server/index.js#L59-L72

Will add it to the initial render as well 👍

**Comment by cossssmin** [comment]
Should be fine now in v5.0.0-beta.35

**Comment by rikzwarthoff** [comment]
Works fine now!
