### ISSUE TITLE
Dynamic class name/value missing in production when set to string 'outer'

### ISSUE THREAD

**Issue by montemartin** [maizzle/framework#139]
- Maizzle Version: 
Framework v0.9.1
CLI v0.5.0

### Description:
My production builds are losing width values when using dynamic class names.

I'm using a Nunjucks variable to post create a dynamic class name in a layout. The class is `.w-col-outer` or `.w-col-inner`. The values are defined in tailwind.config.js as "660px" and "550px" respectively. 

In my layout I'm using a wrapper table and several cells opened like so: `<td class="w-col-{{page.classes.columnWidth}}">`. In the template file I define `columnWidth: outer | inner` in the frontmatter.

When I run a production build, templates with `columnWidth: outer` generate wrapper cells without inline widths, width attributes. or the original class-name. They do however have inlined values from reset.css.

Templates with `columnWidth: inner` work fine. The class name is removed and replaced with inline width and width attribute with the expected value.

It also works fine if I change the layout to `<td class="{{page.classes.columnWidth}}">` and use `columnWidth: w-col-outer` in the template. It's an easy workaround, so this isn't a horrible issue in this case.  

I've checked my config files. The only thing I that seemed a potential issue was `applySizeAttribute: {width: ["TABLE", "TD"]}` but changing that seems to have no effect.

**Comment by cossssmin** [comment]
`columnWidth: outer | inner` assigns a `'outer | inner'` string value to that variable - Nunjucks doesn't work in Front Matter, you need to do it in the template.

I don't see any condition in your code, based on which one class or the other should be output. 

Here's a [purgeable HTML](https://tailwindcss.com/docs/controlling-file-size#writing-purgeable-html)/Nunjucks example for your use-case:

```nunjucks
<td class="{{ 'w-col-outer' if variable else 'w-col-inner' }}">
```

... where `variable` is a `boolean` - see [Nunjucks templating docs](https://mozilla.github.io/nunjucks/templating.html#if-expression).

**Comment by montemartin** [comment]
Perhaps my statement wasn't entirely clear. I'm assigning either `outer` or `inner` in each template. The point is it works when I use `inner` but is stripped when I use `outer`.

**Comment by montemartin** [comment]
Ah, that makes sense and is good to know. 

I was under the impression that PurgeCSS ran on the compiled templates after Nunjucks processed them. I realize now that's what the docs mean by "When not developing locally, postcss-purgecss is used to do a first pass over the compiled Tailwind CSS - this happens before CSS is injected into the HTML". I might adjust that to clarify that it runs on templates, not processed HTML. Might be as easy as adding "by Nunjucks" to the end of that statement.

The reason I wasn't having issues with `'inner'` in frontmatter is `w-col-inner` is used elsewhere in my code. `w-col-outer` was not.

I do have columnWidth nested under classes in my frontmatter. I have a wrapper variable on each block in the layout so I can pass any classes I need up the chain. The nested convention helps keep it more organized.

**Comment by cossssmin** [comment]
Awesome, happy to hear that solved it. I should probably rephrase that section about purgecss in the docs 🤔
