### ISSUE TITLE
Autoprefixer

### ISSUE THREAD

**Issue by jsbrain** [maizzle/framework#140]
Hi, I'm searching for config option for autoprefixer.

I'm using Maizzle to generate html templates that get included into pages, not for actual emails. So I want to include autoprefixer and I saw that this is already in the Maizzle package so I guess this is interally used already and availlable in the build process? If not, would there be a workaround for me?

Thanks in advance!

**Comment by cossssmin** [comment]
Hey, so `autoprefixer` is there because it's a Tailwind dependency, but Maizzle doesn't actually use it. Right now you can't configure PostCSS, but I'm planning on adding support for that in v1.0.0 (which will land in about a month or so).
