### ISSUE TITLE
how can i directly use htmls string within the template

### ISSUE THREAD

**Issue by ramachandranvenkat** [maizzle/framework#150]
- Maizzle Version: v0.9.1
- Node.js Version: v12.13.0

### Description:
I have dynamic HTML string comes from an API service, I need to include those HTML directly into the template. 

give me some examples if this is possible?

**Comment by cossssmin** [comment]
Are you looking to compile a string? You can do that with the `render()` method - [see docs](https://maizzle.com/docs/nodejs/).

Note that you are not forced to use Nunjucks templating - you can simply compile an HTML document. 

For Tailwind to work though, you _will_ need to output the CSS in your `<head>`, so in this case at the very minimum you need to have:

```html
<!DOCTYPE html>
<html>
<head>
  {% if css %}<style>{{ css }}</style>{% endif %}
</head>
<body>
  <!-- your HTML here... -->
</body>
```

**Comment by cossssmin** [comment]
Hmm after reading your description again, I might have misunderstood.

So if all you have is your API and you don't know how to get the data in Maizzle, check out [Events](https://maizzle.com/docs/events/) - I'd probably use [beforeCreate](https://maizzle.com/docs/events/#beforecreate) to store the data coming from the API in the config, and then use it in my template.

If you need a hands-on example, the [WordPress to email tutorial](https://maizzle.com/guides/wordpress-api-posts-email-newsletter/) uses this approach.

**Comment by ramachandranvenkat** [comment]
@cossssmin thanks for your response.
here is my use case, 
JSON data has an HTML string in it. how it can be rendered?


```js
{
"text":"Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut",
"style":{
    "font": "Arial",
    "size": 15.0,
},
"html": "<p>Lorem ipsum dolor sit amet, <strong>consectetur adipiscing</strong> elit,<i> sed do </i> eiusmod <sub>tempor</sub> incididunt ut.<sup>1<sup>"
}
```
is there any other way it can be done?

**Comment by cossssmin** [comment]
Since [Nunjucks autoescaping](https://mozilla.github.io/nunjucks/templating.html#autoescaping) is set to `false` in Maizzle, you'd display it in your loop like this:

```
{{ row.html  }}
```

P.S.: you have a typo on your `<table>` - it says `widht` instead of `width`.

**Comment by ramachandranvenkat** [comment]
thanks @cossssmin
