### ISSUE TITLE
Tailwind base import

### ISSUE THREAD

**Issue by jsbrain** [maizzle/framework#195]
- Maizzle Version: 1.0.9
- Node.js Version: 12.16.2

After hours of searching I noticed that if I include base styles from tailwind:

```css
// main.css

/**
 * This injects Tailwind's base styles and any base styles registered by
 * plugins.
 */
@import 'tailwindcss/base';
```

that the build command will crash with: 

```sh
$ maizzle build production
✖ Failed to compile build_production/accordion.html
(node:7733) UnhandledPromiseRejectionWarning: CssSyntaxError: <css input>:273:1: Unclosed comment
    at Input.error (/Users/macpro/Code/newschrott/starter-amp4email/node_modules/postcss/lib/input.js:130:16)
    at unclosed (/Users/macpro/Code/newschrott/starter-amp4email/node_modules/postcss/lib/tokenize.js:50:17)
    at Object.nextToken (/Users/macpro/Code/newschrott/starter-amp4email/node_modules/postcss/lib/tokenize.js:240:15)
    at Parser.parse (/Users/macpro/Code/newschrott/starter-amp4email/node_modules/postcss/lib/parser.js:49:30)
    at parse (/Users/macpro/Code/newschrott/starter-amp4email/node_modules/postcss/lib/parse.js:17:12)
    at new LazyResult (/Users/macpro/Code/newschrott/starter-amp4email/node_modules/postcss/lib/lazy-result.js:60:16)
    at Processor.<anonymous> (/Users/macpro/Code/newschrott/starter-amp4email/node_modules/postcss/lib/processor.js:138:12)
    at Processor.process (/Users/macpro/Code/newschrott/starter-amp4email/node_modules/postcss/lib/processor.js:117:23)
    at process (/Users/macpro/Code/newschrott/starter-amp4email/node_modules/posthtml-safe-class-names/lib/index.js:29:86)
    at traverse (/Users/macpro/Code/newschrott/starter-amp4email/node_modules/posthtml/lib/api.js:105:26)
(node:7733) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 3)
(node:7733) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

This was just working fine back in version 0.9.1 and it actually also works with `maizzle watch` but the production build will always fail, no matter what.

As you do not include base styles in any of your starters/examples I guess you already know about this? Is there any way around this or how to fix this?

PS: I actually tested a few versions, I think it's all from 1.0 and up as it seems to be a posthtml/postcss problem?!

**Comment by cossssmin** [comment]
The error actually tells you what’s wrong:

```
CssSyntaxError: <css input>:273:1: Unclosed comment
```

Specifically, it’s failing because you have a syntax error on line 1: `// main.css` is invalid CSS.

**Comment by cossssmin** [comment]
We’re not using Tailwind’s base reset styles not because it would fail, but because it contains resets tailored to web, not email development (which can ultimatey break your email layout in some clients, or are simply unnecessary in email and they’d just bloat it).

**Comment by jsbrain** [comment]
> The error actually tells you what’s wrong:
> 
> ```
> CssSyntaxError: <css input>:273:1: Unclosed comment
> ```
> 
> Specifically, it’s failing because you have a syntax error on line 1: `// main.css` is invalid CSS.

Nah sorry this was just to show which file I'm in. Not very clear, I know. This line is actually not included in my file.

I should also mention that I'm using Maizzle also for web purposes, to build custom elements that can be injected into pages. Not intended for this use but Maizzle turned out to be very useful for the job.

So the build command definitely fails because of the `tailwind/base` import. What I did is to just manually minify the base style and include it myself via `custom/my-base.css`. It's just weird why it fails, somehow some commend in that file makes problems and I thought it's maybe worth pointing out as it could lead to a potential yet undiscovered bug in the postcss module I guess?!

**Comment by jsbrain** [comment]
> > The error actually tells you what’s wrong:
> > ```
> > CssSyntaxError: <css input>:273:1: Unclosed comment
> > ```
> > 
> > 
> > Specifically, it’s failing because you have a syntax error on line 1: `// main.css` is invalid CSS.
> 
> Nah sorry this was just to show which file I'm in. Not very clear, I know. This line is actually not included in my file.
> 
> I should also mention that I'm using Maizzle also for web purposes, to build custom elements that can be injected into pages. Not intended for this use but Maizzle turned out to be very useful for the job.
> 
> So the build command definitely fails because of the `tailwind/base` import. What I did is to just "manually" minify the base style to stripe out all comments and include the file via `custom/my-base.css` instead of `tailwind/base`. It now works as intended. It's just weird why it fails, somehow some commend in that file makes problems and I thought it's maybe worth pointing out as it could lead to a potential yet undiscovered bug in the postcss module I guess?!

**Comment by jsbrain** [comment]
So if the stack error is correct it fails here:

<img width="910" alt="Screenshot 2020-05-28 12 28 07" src="https://user-images.githubusercontent.com/20225909/83130520-b484b000-a0de-11ea-9c6f-208990e886db.png">

which I see no reason why...

**Comment by cossssmin** [comment]
Hmm, looks like it's actually PostCSS in [`posthtml-safe-class-names`](https://maizzle.com/docs/code-cleanup/#safeclassnames) that is choking on something inside that `base.css` file - from the looks of it, since we're walking the CSS inside `<style>` line-by-line, it will inevitably choke on multi-line CSS comments.

Until I find a way to fix that, a solution would be to trick it and use the 'local' environment to build the production emails: instead of `maizzle build production` just run `maizzle build` - it will use `config.js` settings, so make sure you update that file with any production-specific settings. Downside is it might be a tad slower when developing with `maizzle serve`, since it uses the same settings that would now tell it to run more transformations.

**Comment by cossssmin** [comment]
Added a way of disabling `safeClassNames` in c686dde - will be available in the next feature release.

**Comment by jsbrain** [comment]
> Hmm, looks like it's actually PostCSS in [`posthtml-safe-class-names`](https://maizzle.com/docs/code-cleanup/#safeclassnames) that is choking on something inside that `base.css` file - from the looks of it, since we're walking the CSS inside `<style>` line-by-line, it will inevitably choke on multi-line CSS comments.
> 
> Until I find a way to fix that, a solution would be to trick it and use the 'local' environment to build the production emails - `safeClassNames` runs only when `env` is not `local`.
> 
> So instead of `maizzle build production` just run `maizzle build` - it will use `config.js` settings, so make sure you update that file with any production-specific settings. Downside is it might be a tad slower when developing with `maizzle serve`, since it uses the same settings that would now tell it to run more transformations.

I came actually to a same idea but realized that not all production settings work in local. For example purgeCSS and I think removeUnusedCSS as well. It even says so in the [docs](https://maizzle.com/docs/code-cleanup/#purgecss) 😃

**Comment by cossssmin** [comment]
Ah, you're right, forgot about those... Looks like if we apply `safeClassNames` at a later stage in the transformations process, it works just fine. Need to understand why, maybe you won't even need to disable it.

**Comment by cossssmin** [comment]
Found the issue, looks like PostCSS chokes on this line in the `posthtml-safe-class-names` plugin:

https://github.com/tailwindcss/tailwindcss/blob/50ce88ab373a76e3666173dc317d0f4ab6d86412/src/plugins/css/preflight.css#L76

The problem is that `<details>` tag inside the comment.

I imagine PostCSS has some API that tells you when it's walking inside a comment, so perhaps we can fix this in the plugin itself, since it isn't caused by Maizzle itself.

In the meanwhile, a solution on Maizzle's side would be to use `safeClassNames` after the inlining process - inlining removes all comments by default, so we could avoid this issue. I'll test this and perhaps add it in, just need to make sure it doesn't break something else.

**Comment by jsbrain** [comment]
Oh wow! The question is if this is the intended behavior of PostCSS?!

**Comment by cossssmin** [comment]
Looks like the `Declaration` object that PostCSS returns when you walk over declarations doesn't include any of the comment lines.

I'm not sure what it does or why it fails like that when `walk`ing declarations, but it feels odd that it would do that - why would it care about an HTML tag inside a comment?

I'll investigate further, thanks for opening the issue over in PostCSS!

**Comment by cossssmin** [comment]
Found the issue and will push a fix for the `posthtml-safe-class-names` plugin in a bit. Thanks for reporting the issue!

**Comment by cossssmin** [comment]
Published [posthtml-safe-class-names@1.0.3](https://github.com/posthtml/posthtml-safe-class-names/releases), will update it in Maizzle and make it part of the upcoming feature release (which I hope to publish next week).

Thanks again for reporting this issue!

**Comment by jsbrain** [comment]
Amazing! You're a beast! 😄👌
My pleasure, I'm always happy to help with this amazing project! 😇

**Comment by cossssmin** [comment]
Thanks, I actually went ahead and added the features for `v1.1.0` and released it:

https://github.com/maizzle/framework/releases/tag/v1.1.0
