### ISSUE TITLE
deleting id="whatever" - when compiling?

### ISSUE THREAD

**Issue by FrederikGejl** [maizzle/framework#201]
- Maizzle Version: 1.0.3
- Node.js Version: 14.3.0
deleting id="whatever" - when compiling?

<amp-selector id="menu2" layout="container"  hidden>

When you compile id="menu" is deleted - is maizzle suppose to do that?

Great framework really appreciate it.

**Comment by FrederikGejl** [comment]
For example: <amp-selector id="menu2" layout="container"  hidden>

id is out in build.

**Comment by FrederikGejl** [comment]
`<amp-accordion animate expand-single-section hidden id="menu1">`

Wipes id="menu1"

**Comment by cossssmin** [comment]
It's email-comb cleaning up unused selectors in both CSS and the HTML. You need to whitelist it if you don't have any styles defined for `#menu1` - see the [docs](https://maizzle.com/docs/code-cleanup/#removeunusedcss).

**Comment by FrederikGejl** [comment]
ah ok - sorry about that. Thx for reply!

**Comment by FrederikGejl** [comment]
It's in config.production.js right?

I tried a few things writing menu. (. as all catch) and menu*

whitelist: ['.amp*','menu1','menu2','menu3'],

Doesn't seem to work. Still wipes my ID="menu1" etc

`  removeUnusedCSS: {
    enabled: true,
     removeHTMLComments: false,
    whitelist: ['.amp*','menu1','menu2','menu3'],
  },
}
`

**Comment by cossssmin** [comment]
> It's in config.production.js right?

Yes, it's best to add it in the config file that you're using to build the production-ready emails - by default, that's `config.production.js`.

> ` removeUnusedCSS: { enabled: true, removeHTMLComments: false, whitelist: ['.amp*','menu1','menu2','menu3'], }, }`

For ids, you need the `#` in front. You can have it preserve all ids like this:

```js
removeUnusedCSS: {
  enabled: true,
  whitelist: ['#*'],
  // ...
}
```

See the [email-comb docs](https://www.npmjs.com/package/email-comb#options---optswhitelist) for more info.

**Comment by FrederikGejl** [comment]
appreciate it! 

Working :)
