### ISSUE TITLE
Possible to have multiple target build directories?

### ISSUE THREAD

**Issue by connecteev** [maizzle/framework#207]
I am just trying maizzle to see if it will save me time (moving over from mjml templates, I'm also a fan of tailwindcss). 

One question I have is, is it possible to have multiple target build directories?

[starter-litmus](https://github.com/maizzle/starter-litmus/tree/master/src/templates) has templates for ceej and slate, and upon build,  both get saved to different subfolders within the destination folder (build_local, for example). But can you specify different destination folders that are **not** within the same parent build_local?

Here's my use-case:
1. project_1 folder contains: unique header and footer, other unique email templates
2. project_2 folder contains: unique header and footer, other unique email templates
3. common folder contains: common components (to both projects)

I have all files in 
- template files in maizzle/src/templates/project_1 and maizzle/src/templates/project_2
- component files (header and footer) in maizzle/src/components/project_1, maizzle/src/components/project_2 and maizzle/src/components/common

I would like my compiled / built email templates to go into ~/home/project_1/emails and ~/home/project_2/emails

Is this possible with the config?

**Comment by connecteev** [comment]
@cossssmin Thanks for the tips. I didnt know about the permalink key for each template....but it's not quite what I'm trying to do, since the permalink frontmatter doesn't let me add global variables (right now, I cannot have multiple templates, especially as they grow to 40-50, to use the same root permalink).

Can I suggest that we try to have multiple build directories (original suggestion)? It could be very similar to what you've done for [assets](https://maizzle.com/docs/build-config/#assets)

If you've structured your emails inside the base templates folder, say like this:
- src/templates/project_1/emails
- src/templates/project_2/emails

The config would change from:
```
destination: {
  path: 'build_local',
},
```

To something like this:
```
destinations: {
  [
   source: 'src/templates',
   destination: 'buid_local',
  ],
  [
   source: 'src/templates/project_1',
   destination: 'C:/Users/Cosmin/project_1',
  ],
  [
   source: 'src/templates/project_2',
   destination: 'C:/Users/Cosmin/project_2',
  ],
},
```
All files within src/templates/project_1' will get built in C:/Users/Cosmin/project_1
All stray files within src/templates (that are not within the other source specified, like 'src/templates/project_1', 'src/templates/project_3') will get built in buid_local.

so you could have multiple destinations or target build directories..

For simple use-cases you'd just do:
```
destinations: {
  [
   source: 'src/templates',
   destination: 'buid_local',
  ],
},
```

**Comment by cossssmin** [comment]
Sounds good and I’m all for it, but:

1. `destination`. Plural is a breaking change. 
2. Simple use case would not use an array, it would just be as it is today. 

I’ll start playing around with this for the next feature release, thanks!

**Comment by cossssmin** [comment]
Actually just re-read and it would be breaking nonetheless. Will have to think about structuring it, but if we do it will most likely have to be in v2.0

**Comment by connecteev** [comment]
@cossssmin How about this to prevent a breaking change:

Default stays the same for simple use-cases:
```
destination: {
  path: 'build_local',
},
```

For multiple target builds, something like this (optional, would be added in addition to the destination config). It would be almost identical to the assets config.

```
destinations: {
  [
   source: 'src/templates/project_1',
   destination: 'C:/Users/Cosmin/project_1',
  ],
  [
   source: 'src/templates/project_2',
   destination: 'C:/Users/Cosmin/project_2',
  ],
},
```

**Comment by cossssmin** [comment]
It would still be a breaking change, we’re defining template sources elsewhere now. And it also confusing to have such similar key names, I wouldn’t want it like that tbh. I’ll think about it though, as it’s an useful feature to have.

**Comment by connecteev** [comment]
That makes sense...look forward to using this as soon as it becomes available.

**Comment by cossssmin** [comment]
We could probably get rid of `build.destination` and use something like this:

```js
module.exports = {
  build: {
    templates: [
      {
        root: 'src/templates/project-1',
        filetypes: 'html',
        destination: {
          path: 'build_local',
          extension: 'html'
        },
      },
      {
        root: 'src/templates/project-2',
        filetypes: 'html',
        destination: {
          path: '~/project-2/mailables',
          extension: 'blade.php'
        },
      }
    ],
  }
}
```

A single source would then look like this:

```js
module.exports = {
  build: {
    templates: {
      root: 'src/templates/project-1',
      filetypes: 'html',
      destination: {
        path: 'build_local',
        extension: 'html'
      },
    }
  }
}
```

I've also renamed [`extensions`](https://maizzle.com/docs/build-config/#extensions) to `filetypes` in the examples above (it used to be named like that previously), so that it doesn't create confusion with [`extension`](https://maizzle.com/docs/build-config/#extension), now that they'd be added under the same key.

**Comment by connecteev** [comment]
This is very intuitive to me.

For single source, I imagine you could still do ```root: 'src/templates'``` (without requiring files to be in a subfolder like ```root: 'src/templates/project-1'```) - this would make it easier for people that dont have a complex config.

> I've also renamed extensions to filetypes in the examples above (it used to be named like that previously), so that it doesn't create confusion with extension, now that they'd be added under the same key.
Makes sense to me.

**Comment by connecteev** [comment]
This is a nitpick so feel free to reject this idea, but maybe 'source' instead of 'root' is more intuitive and pairs nicer with "destination".

**Comment by cossssmin** [comment]
> this would make it easier for people that dont have a complex config

Yes of course.

> This is a nitpick so feel free to reject this idea, but maybe 'source' instead of 'root' is more intuitive and pairs nicer with "destination".

You're probably right, it'll be a breaking change anyway...

**Comment by connecteev** [comment]
thanks for the consideration. Look forward to using this.

**Comment by cossssmin** [comment]
Added in 4400f93. Required workarounds for unexpected issues, like Browsersync compatibility, but it should be good now. Will be part of `v2.0` next month if it doesn't break anything else 😂

**Comment by connecteev** [comment]
@cossssmin awesome, thank you. And your timing could not be better.....just hope it can be checked into the master / release branch because i'm putting other features on hold to re-explore maizzle this weekend.

**Comment by connecteev** [comment]
can we merge this baby in? can't wait to use it ♡

**Comment by cossssmin** [comment]
Going to merge soon, taking care of a few extra touches, thanks

**Comment by cossssmin** [comment]
@connecteev v2.0.0 is live, see #291 for details and update to give it a spin 👍

**Comment by connecteev** [comment]
@cossssmin exciting..thank you! 👍  I'm going to give this a a spin very soon (this week most likely). I'll have some feedback for you soon on how it goes!

**Comment by connecteev** [comment]
@cossssmin I spent some time re-familiarizing myself with maizzle (it had been a few months) - this works great right out of the box, and is highly flexible + configurable. 👍

I'll start a thread on this, but I am struggling with passing variables into components, not sure if it's user-error or a regression.

**Comment by cossssmin** [comment]
Sure thing, thanks! Do also check the docs for that in case you haven’t already: 

https://maizzle.com/docs/components/#variables

**Comment by connecteev** [comment]
@cossssmin thank you, I got the variable-passing to work (I previously had the "brilliant" idea of using ```<!---``` and ```-->``` to wrap the frontmatter, because I was trying to remove the preheader. I could have just removed the preheader instead, the <!-- comments were breaking the variable passing (no surprise there).
