### ISSUE TITLE
Parsing value from variable inside 'class' tag doesn't work, but it works with i.e. 'for' and 'id'

### ISSUE THREAD

**Issue by jrtderonde** [maizzle/framework#212]
- Maizzle Version: ^1.0.0
- Node.js Version: #.#.#

**What worked**

```
<fetch url="">
   <each loop="product in response.products">
      <label 
         for="product{{ product.id }}"
         on="tap:fakeCheck{{ product.id }}.toggleClass(class='bg-red-50')"
         role="button"
         tabindex="{{ product.id }}"
         class="no-outline font-bold font-base no-border">
      {{ product.title }} / &euro; {{ product.price }}
      </label>
   </each>
</fetch>
```

**What didn't work**

```
<fetch url="">
   <each loop="product in response.products">
      <label 
         for="product{{ product.id }}"
         on="tap:fakeCheck{{ product.id }}.toggleClass(class='bg-red-50')"
         role="button"
         tabindex="{{ product.id }}"
         class="no-outline font-bold font-base no-border bg-deals-{{ product.type }}">
      {{ product.title }} / &euro; {{ product.price }}
      </label>
   </each>
</fetch>
```

Product return a lowercase string that matched the term `weekend`, `deal--{{ product.type }}` should then parse `deal--weekend` which it didn't. For some reason though this method worked for the id and for field.

**Comment by cossssmin** [comment]
You need to whitelist such dynamically built classes, they're removed at build time if they don't exist in your CSS.

https://maizzle.com/docs/code-cleanup/#removeunusedcss

**Comment by jrtderonde** [comment]
I'll look into this tomorrow, thanks :-)

**Comment by cossssmin** [comment]
@jrtderonde did you get it working?

**Comment by cossssmin** [comment]
Feel free to reopen if you're still experiencing the issue after whitelisting the classes as advised 👍
