### ISSUE TITLE
external engine variables break urlParameters

### ISSUE THREAD

**Issue by jaddison** [maizzle/framework#213]
- Maizzle Version: 1.1.1
- Node.js Version: 13.8.0

I'm trying to generate production emails containing `jinja2` template conditionals and variables that I can later populate in a transactional scenario (order, welcome, password reset, etc emails).

With this example:
```
---
urlParameters:
  utm_source: transactional email
  utm_campaign: order confirmed
---
...
Click here to <a href="{{{ page.SHOP_SITE_URL }}}/@{{ order.id }}">view current order status</a>
```

it generates the following:
```
Click here to <a href="https://store.example.ca/{{ order.id }}" style="color: #5850ec;">view current order status</a>
```

But it should generate this:

```
Click here to <a href="https://store.example.ca/{{ order.id }}?utm_campaign=order confirmed&utm_medium=email&utm_source=transactional email" style="color: #5850ec;">view current order status</a>
```

config.js:
```
  ...
  urlParameters: {
    _options: {
      qs: {
        encode: false
      },
    },
    utm_medium: 'email'
  },

  SHOP_SITE_URL: 'https://store.example.ca',
```

To be clear, other links in the same email work fine, as long as they don't have `@{{ variable_name }}` syntax embedded in the href.

Is it possible to address this as a maizzle fix - or is there a standard way to deal with this in my templates?

**Comment by jaddison** [comment]
Guessing that it's related to [these lines in `posthtml-url-parameters`](https://github.com/posthtml/posthtml-url-parameters/blob/master/lib/index.js#L16-L20)?

**Comment by jaddison** [comment]
Ideally, I could insert external template engine variables throughout `href` links: 

`https://@{{ domain}}/orders/@{{ order.id }}?customer_id=@{{ customer.id }}`

But right now, only the following will work:

`https://example.com/orders/ord_5ghd783D?customer_id=@{{ customer.id }}`

With the fix mentioned in the linked `posthtml-url-parameters` (see above), we can achieve this though:

`https://example.com/orders/@{{ order.id }}?customer_id=@{{ customer.id }}`

Not sure how to achieve a subdomain external variable as well?

**Comment by cossssmin** [comment]
Thanks, will work on it an communicate in https://github.com/posthtml/posthtml-url-parameters/issues/2 since it's an issue with that package 👍

**Comment by jaddison** [comment]
> Thanks, will work on it an communicate in posthtml/posthtml-url-parameters#2 since it's an issue with that package 👍

Sounds good. Closing this here then.
