### ISSUE TITLE
Trying to fetch config.preheader from docs sample code

### ISSUE THREAD

**Issue by jrtderonde** [maizzle/framework#220]
- Maizzle Version: 1.0.3
- Node.js Version: 13.11.0

I'm trying to prefetch the sample JSON from the docs

```
events: {
    async beforeRender(config) {
      const url = 'https://baconipsum.com/api/?type=all-meat&sentences=1&start-with-lorem=1'
      config.preheader = await axios('url').then(result => result.data).catch(error => 'Could not fetch preheader, using default one.')
    },    
  }
```

But when I try to parse it inside my `layouts/master.html` I'm being returned `Could not fetch preheader, using default one.`. When I visit the URL from my browser however I'm being returned the correct JSON. 

If I swap around the request url with a different JSON location, it still catches the error. 

Does anyone know what might be going wrong here? I'm looking to fetch some data before building that requires me to pass along some credentials.

**Comment by jrtderonde** [comment]
Ah, `axios('url')` should be `axios(url)`

**Comment by cossssmin** [comment]
Thanks for noticing, just pushed a fix for this - https://github.com/maizzle/docs/commit/6647ca2e8532f2e8290896939c497c73e653f5fc
