### ISSUE TITLE
if condition is breaking variable access in a component (production build only)?

### ISSUE THREAD

**Issue by jaddison** [maizzle/framework#222]
- Maizzle Version: 1.1.1
- Node.js Version: 14.4.0

This feels like a pretty weird one. Much of the following is snipped for brevity:

**src/templates/order-refund.html**
```
---
refunded: true
---

<extends src="src/layouts/customers/transactional.html">
  <block name="transactional-content">
    <component src="src/components/order-detail.html" />
  </block>
</extends>
```

**src/components/order-detail.html**
```
  <if condition="page.refunded">
    <div class="text-right" colspan="2">Total Refund {{ page.seller.currency }}</div>
  </if>
```

The above will error out when performing `build production` with the following (not that `serve` works fine):
```
maizzle build production
✖ Failed to compile build_production/customers/orders/refunded.html
(node:23675) UnhandledPromiseRejectionWarning: ReferenceError: seller is not defined
(Use `node --trace-warnings ...` to show where the warning was created)
(node:23675) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:23675) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

If I comment out the `<if ...>` clause in the component, like the follow, it will `build production` successfully:
```
<!--  <if condition="page.refunded">-->
    <div class="text-right" colspan="2">Total Refund {{ page.seller.currency }}</div>
<!--  </if>-->
```

**Comment by cossssmin** [comment]
Do you have `seller` defined somewhere, like in the config? It’s trying to compile `page.seller.currency` but it can’t find a `seller` variable on the global `page` object. 

Not to say that there’s no issue here, it should still error out if you remove the if tag...

**Comment by jaddison** [comment]
Yes. `page.seller.currency` is defined.

**Comment by cossssmin** [comment]
Tested it out and it works fine, see the repo here: https://github.com/cossssmin/issue-222

Is there anything else in your setup that you omitted in the example?

**Comment by jaddison** [comment]
Sorry for the delay in responding - my code has changed such that this isn't a problem anymore. Closing.
