### ISSUE TITLE
Cannot change src folder

### ISSUE THREAD

**Issue by nodeg** [maizzle/framework#227]
- Maizzle Version: 1.1.1
- Node.js Version: 14.4.0

I am not able to change the `src` directory of Maizzle. I adjusted `path` and `root` inside my `config.js` to point to `mvc/view/html` but Maizzle somehow applies its own structure after my settings:

```bash
(node:13728) UnhandledPromiseRejectionWarning: Error: ENOENT: no such file or directory, open '/home/dom/git/beta-emails-maizzle/mvc/view/html/layouts/src/layouts/master.html'
```

Is it not possible to change the `src` folder at all or am I missing something here?

**config.js:**
```js
module.exports = {
  build: {
    browsersync: {
      directory: true,
      notify: false,
      open: true,
      port: 3000,
      tunnel: false,
      ui: {port: 3001},
      watch: [],
    },
    assets: {
      source: 'mvc/view/html/assets/images',
      destination: 'images',
    },
    destination: {
      path: 'mvc/view/html/build_local',
    },
    tailwind: {
      css: 'mvc/view/html/assets/css/main.css',
    },
    templates: {
      root: 'mvc/view/html/pages',
    },
    components: {
        root: 'mvc/view/html/components',
    },
    layouts: {
        root: 'mvc/view/html/layouts/',
    }
  },
}
```

```bash
$ maizzle serve
✖ Failed to compile mvc/view/html/build_local/testing/testing.html
(node:13728) UnhandledPromiseRejectionWarning: Error: ENOENT: no such file or directory, open '/home/dom/git/beta-emails-maizzle/mvc/view/html/layouts/src/layouts/master.html'
    at Object.openSync (fs.js:461:3)
    at Object.readFileSync (fs.js:364:35)
    at /home/dom/git/beta-emails-maizzle/node_modules/posthtml-extend/lib/extend.js:84:39
    at /home/dom/git/beta-emails-maizzle/node_modules/posthtml-extend/node_modules/posthtml/lib/api.js:91:45
    at traverse (/home/dom/git/beta-emails-maizzle/node_modules/posthtml-extend/node_modules/posthtml/lib/api.js:105:26)
    at Array.match (/home/dom/git/beta-emails-maizzle/node_modules/posthtml-extend/node_modules/posthtml/lib/api.js:90:7)
    at handleExtendsNodes (/home/dom/git/beta-emails-maizzle/node_modules/posthtml-extend/lib/extend.js:78:16)
    at /home/dom/git/beta-emails-maizzle/node_modules/posthtml-extend/lib/extend.js:42:16
    at /home/dom/git/beta-emails-maizzle/node_modules/posthtml/lib/index.js:215:14
    at tryCatch (/home/dom/git/beta-emails-maizzle/node_modules/posthtml/lib/index.js:298:12)
(Use `node-default --trace-warnings ...` to show where the warning was created)
(node:13728) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 3)
(node:13728) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

**Comment by cossssmin** [comment]
The `root` you set for basically anything in Maizzle, is relative to your project root (where you keep Maizzle's `config.js` files).  So in your example it errors out because it can't find a `master.html` layout to extend, in `/home/dom/git/beta-emails-maizzle/mvc/view/html/layouts/`.

**Comment by nodeg** [comment]
And exactly that is what I am wondering about. The file `master.html` is inside `/home/dom/git/beta-emails-maizzle/mvc/view/html/layouts/`. I did not change anything iside `src` other than renaming `template` to `pages`. Then I copied everything over from `src`, adjusted the configuration files and after that the error occured. Before that everything worked fine.

**Comment by cossssmin** [comment]
OK, how are you referencing the layout file in your template with the `<extends>` tag? Would be easier if you could share a repository that I could look at, if possible.

**Comment by nodeg** [comment]
@cossssmin: Thanks for the quick reply. The `<extends>` tag was indeed the problem for the error. It works now. Sorry for trouble and thanks again for the help!

**Comment by cossssmin** [comment]
No problem, happy to hear it's working for you now 🙂

I'll go ahead and close this, but feel free to reopen if you encounter further issues.

**Comment by lepaliscot** [comment]
Hi @cossssmin, I need your help. I'm trying to run Maizzle inside a Laravel project that is already using tailwind, locating the src folder inside my resources/views folder and replacing the directory name from src to maizzle, and also having a dedicated tailwind config file for maizzle.

So the structure looks like:
- resources
-- views
--- maizzle
config.js
tailwind.maizzle.config.js

I also update the config.js file to reflect this path changes. Then build the template. My final result is compiling the layout, template and components without problem, except it is not taking into account the tailwind classes :(. So it is taking in account the paths changes but no the tailwind classes.

I did another test, following a clean installation process described at https://maizzle.com/docs/installation and keep all config except, change src for src1 and updating the paths, and the behavior is the same, it can find the layout and components but is not taking into account the tailwind classes. You can see the behavior in [this short video](https://share.getcloudapp.com/lludEgez) I recorded.

I'm using the latest version of maizzle. This is my package.json

```
{
  "private": true,
  "scripts": {
    "dev": "maizzle serve",
    "build": "maizzle build production"
  },
  "dependencies": {
    "@maizzle/framework": "latest",
    "tailwindcss-box-shadow": "^2.0.0",
    "tailwindcss-email-variants": "^2.0.0",
    "tailwindcss-mso": "^1.3.0"
  }
}
```

And this my config.js
```
module.exports = {
  build: {
    browsersync: {
      watch: [
        'src/**/*.*',
        'tailwind.maizzle.config.js',
      ],
    },
    components: {
      root: 'src/components',
    },
    layouts: {
      root: 'src/layouts',
    },
    templates: {
      source: 'src/templates',
      destination: {
        path: 'build_local',
        extension: 'html'
      },
    },
    tailwind: {
      css: 'src/css/tailwind.css',
      config: 'tailwind.maizzle.config.js'
    }
  },
  prettify: true,
  inlineCSS: false,
}
```

I hope you can help me.
