### ISSUE TITLE
Brakets in the title breaks Maizzle

### ISSUE THREAD

**Issue by nodeg** [maizzle/framework#268]
- Maizzle Version: v1.3.1
- Node.js Version: v14.6.0
---

I am not able to use special characters (`[ ]`) in the title section of my template the following way:

`title: [ANNOUNCE] New Framework available`

That will break Maizzle somehow. If I escape the brakets with `-` like the following, it works:

`title: -[ANNOUNCE]- New Framework available`

Is there a way to properly escape the brakets? I want to use the brakets only without any dash (`-`) for example. Backslash doesn't work either.

**Comment by cossssmin** [comment]
Try using quotes so that Front Matter interprets it as a proper string:

```
title: "[ANNOUNCE] New Framework available"
```

**Comment by nodeg** [comment]
This works. Thank you!
