### ISSUE TITLE
Maizzle as microservice

### ISSUE THREAD

**Issue by j-mori** [maizzle/framework#280]
Hi @cossssmin i m working to a maizzle microservice version and i would like to know if you like the idea.

**The Idea**
It'run a nodejs server(with [expressjs](https://expressjs.com/) probably) and listen for an http request.
The request should have the following data:
- Template to compile (path)
- Configs to apply

It merge the server config file with request config param and return a compiled template ready to be sent.

**How i would implement it**

https://github.com/maizzle/framework/blob/master/src/index.js will'exports a new method `server`, it will'accept an env, like the method "build" does, and will create the server that will listen for an http request like described above.
on request it' ll read the requested file and will compile it with `toString` method and then return it in as json response.
The config file will' accept some new parameter like server listening port and probably something else.
Ideally the server would be run by a CLI command like `maizzle server <env>` but i will need a bit of help for that.

Let me know if you think that would be a nice feature to add to the repo and if you like the way i would implment it or if you notice some issue about it.

Thanks you.

**Comment by cossssmin** [comment]
Hi, we already use Browsersync for this purpose, why would this be better?

**Comment by cossssmin** [comment]
I see, thanks for the explanation. I think this would make for a good SaaS, it's not something that I would add to core since it can already be done via either config variables, or [events](https://maizzle.com/docs/events/) that fetch data from APIs and make it available to the config.

Regarding compiling a single template, there is #247 which will cover this exact need once we firgure it out.

**Comment by j-mori** [comment]
Yes but not, SaaS oriented would mean that maizzle.com would be the server accomplishing the task, i would prefer have the possibility to build up my own hosted maizzle server compiling my own template.

You are right, at the moment you can compile with custom data via config (or events) but the hard (and slow) task is trigger the compilation on another external software need. 
Without adding an http listener to the core the only way to achive the same result that i can figure out is to create a new nodejs server that on http request:
- Generate a config file with data passed in the http request
- Run the "build" CLI command
- Read and return the generated template

But this is pretty slow and not much integrated with maizzle itslef because require a lot of useless read and write on disk

**Comment by cossssmin** [comment]
Sorry, I understand but I have no plans on going in that direction at the moment. Maybe we'll revisit this in the future, like in a major release, but not for now.

**Comment by j-mori** [comment]
ok, thanks for your prompt reply, anyway i'll work on my own solution because it's a feature i really need, if you are interested i can fork the repo and in the next days i can push the branch otherwise i ll go for the external and slower solution
