### ISSUE TITLE
<raw> inside <component>s

### ISSUE THREAD

**Issue by richardhj** [maizzle/framework#282]
Hi!
I wanted to note the following issue. The issue was not fixed by #193. I am using raw, because I use twig syntax.

`<raw>` is not working inside header.html, which is included via `<component src="src/components/header.html"></component>`. The result is the same as described above. Is it the same issue?

_Originally posted by @richardhj in https://github.com/maizzle/framework/issues/193#issuecomment-645368208_

**Comment by richardhj** [comment]
Somehow, the issue is fixed now :-)

**Comment by cossssmin** [comment]
Can you please let me know the framework version (`maizzle -v`) and what your component looks like?

I tested this and it worked fine, `{{ page.env }}` was not evaluated:

src/templates/template.html

```html
<extends src="src/layouts/master.html">
  <block name="template">
    <component src="src/components/example.html">
      {{ page.env }}
    </component>
  </block>
</extends>
```

src/components/example.html

```html
<raw>
  {{ page.env }}
</raw>
<content></content>
```

What's inside the raw tag was output correctly (`{{ page.env }}`) and for content that you pass to the component, you don't need `<raw>` (unless you're manually passing posthtml-expressions to the components object in your [config](https://maizzle.com/docs/components/#configuration)).

**Comment by richardhj** [comment]
Maybe my local`maizzle` was outdated because it works now on my new machine.

**Comment by cossssmin** [comment]
OK, thanks for letting me know :)

**Comment by richardhj** [comment]
Thank you for your efforts in creating Maizzle 💯
