### ISSUE TITLE
Indenting URL Parameters in VS Code

### ISSUE THREAD

**Issue by Blake32p** [maizzle/framework#285]
- Maizzle Version: 1.3.1
- Node.js Version: v13.10.1

Sorry if this is more of a VS Code question, but it relates to Maizzle so I thought I would ask it here.

I am wondering if there is a way to disable formatting front matter in VS Code? I like to use URL parameters in my emails but it requires indenting the UTM tags. When I save the file the indents are automatically removed, so the URL Parameters are not added to links during the build. In the past I believe I unchecked "Format on Save" but that doesn't seem to be working for me today. I tried also tried searching for anything Prettier related that might help but I haven't been able to find anything.

**Comment by cossssmin** [comment]
Check the plugins you have installed, VS Code doesn’t do this by default.
