### ISSUE TITLE
Best practices for passing variables into components on different environments

### ISSUE THREAD

**Issue by connecteev** [maizzle/framework#293]
- Maizzle Version: #.#.# 2.0
- Node.js Version: #.#.# 12

For local testing, I know Maizzle expects variables to be in this format: ```{{ page.env }}```
Is this (below) the best way to add variables to Maizzle templates, so that both local and production builds are accounted for?
```
      <if condition="page.env === 'local'">
        <p>We are on env: {{ page.env }}</p>
        <p>{{ page.varName }}</p>
      </if>
      <elseif condition="page.env === 'production'">
        <p><raw>{{ $varName }}</raw></p>
      </elseif>
      <else>
        <p>Invalid env: {{ page.env }}</p>
      </else>
```

**Comment by connecteev** [comment]
This gets tricky when you need to use <raw> with an href. Is this the best way to do the following?

```
<if condition="page.env === 'local'">
<a
    href="{{ page.resetPasswordUrl }}"
    style="display:inline-block; background:#000000; color:#ffffff; " target="_blank">
    Reset your Password
</a>
</if>
<else>
    <raw>
        <a
        href="{{ $resetPasswordUrl }}"
        style="display:inline-block; background:#000000; color:#ffffff;" target="_blank">
        Reset your Password
        </a>
    </raw>
</else>
```

**Comment by cossssmin** [comment]
> This gets tricky when you need to use <raw> with an href. Is this the best way to do the following?

Use `@{{ }}` just like in Laravel - it's described in the [docs](https://maizzle.com/docs/templates/#curly-brace-conflicts).

I'm not sure I understand the first question, what are you trying to achive there? Is that a component, or...?

**Comment by connecteev** [comment]
@cossssmin that's very useful, thanks...I had missed ```@{{ }}``` in the documentation (btw, your docs are excellent).

I now have this in a component:
```
                          <if condition="page.env === 'local'">
                            <a
                              href="{{ page.resetPasswordUrl }}"
                              style="display:inline-block; background:#000000; color:#ffffff; font-family:Ubuntu, Helvetica, Arial, sans-serif; font-size:16px; font-weight:500; line-height:120%; margin:0; text-decoration:none; text-transform:none; padding:10px 25px; mso-padding-alt:0px; border-radius:5px;" target="_blank">
                              Reset your Password
                            </a>
                          </if>
                          <else>
                              <a
                                href="@{{ $resetPasswordUrl }}"
                                style="display:inline-block; background:#000000; color:#ffffff; font-family:Ubuntu, Helvetica, Arial, sans-serif; font-size:16px; font-weight:500; line-height:120%; margin:0; text-decoration:none; text-transform:none; padding:10px 25px; mso-padding-alt:0px; border-radius:5px;" target="_blank">
                                Reset your Password
                              </a>
                          </else>

```
and my first question was basically whether there was a simpler way to do the above for local / production environments and boil this down further so I dont have a conditional for every link that I add to an email.

**Comment by cossssmin** [comment]
I think the simplest way to do it is to define it as a variable in your Maizzle config files:

```js
// config.js

module.exports = {
  resetPasswordUrl: 'https://example.com',
 // rest of the config...
}
```

```js
// config.production.js

module.exports = {
  resetPasswordUrl: '@{{ $resetPasswordUrl }}',
}
```

You can then use it in your HTML like this:

```html
<a href="{{ page.resetPasswordUrl }}">Reset your Password</a>
```

When running `maizzle build` or `maizzle serve`, this will output:

```html
<a href="https://example.com">Reset your Password</a>
```

... and when running `maizzle build production`:

```html
<a href="{{ $resetPasswordUrl }}">Reset your Password</a>
```

**Comment by connecteev** [comment]
@cossssmin thanks for the detailed response as always. Another neat thing about Maizzle I did not know...

Defining variables in the Maizzle config files seem like an interesting approach, though it would scatter the variables from many templates into the config, which isn't ideal. It would 100% make sense for variables that are shared across multiple templates, though....so this is another feature that is useful. Please feel free to close this issue if you think it makes sense to do so...

PS. One idea (as a feature request for future consideration) would be to never have to add variables to the config file, or have  conditionals for links in the templates. 
You would always render variables like so:
```
<a href="{{ $resetPasswordUrl }}">Reset your Password</a>
```
If resetPasswordUrl is defined in the frontmatter, it would just work! In other words, you you would use the same blade syntax ```{{ $resetPasswordUrl }}``` instead of ```{{ page.resetPasswordUrl }}``` to render template variables **and** frontmatter.

Btw, I appreciate the amount of attention you've put into this framework - it really is a hidden gem and deserves more attention.

**Comment by cossssmin** [comment]
Changing the namespacing (removing `page.`) would be a breaking change, and I don't think I even want to do it.

Ideally, I think [posthtml-expressions](https://github.com/posthtml/posthtml-expressions), the PostHTML plugin we use for evaluating expressions, should not parse stuff inside quotes in a ternary. At first I thought about handling it like this:

```html
<a href="{{ page.env === 'local' ? page.resetPasswordUrl : '{{ $resetPasswordUrl }}' }}">Link</a>
```

... however `{{ $resetPasswordUrl }}` is parsed there and you get a `SyntaxError: Invalid or unexpected token`. Even if you try to escape it - i.e. `'@{{ $resetPasswordUrl }}'` - you still get the same error.

I've brought this up with one of the maintainers, maybe we can fix it there, we'll see.

**Comment by connecteev** [comment]
@cossssmin that makes a lot of sense, and the format you shared (with the ability to add styles etc, below) would be great so the code is not repeated.
```<a href="{{ page.env === 'local' ? page.resetPasswordUrl : '{{ $resetPasswordUrl }}' }}" 
style="display:inline-block; background:#000000; color:#ffffff;"
>Link</a>```

I defer to your judgment on this and whether it can be done without a breaking change.

**Comment by cossssmin** [comment]
```js
// config.js 

module.exports = {
  resetPasswordUrl: 'https://example.com',
}
```

```js
// config.production.js 

module.exports = {
  resetPasswordUrl: '@{{ $resetPasswordUrl }}',
}
```

```html
<!-- template -->

<extends src="src/layouts/master.html">
  <block name="template">
    <a href="{{ page.resetPasswordUrl }}">Link</a>
  </block>
</extends>
```

Or you could even define a 'top-level' variable (since [v2.5.0](https://github.com/maizzle/framework/releases/tag/v2.5.0)), so you don't need to use the `page` object: 

```js
// config.js 

module.exports = {
  locals: {
    resetPasswordUrl: 'https://example.com',
  }
}
```

```js
// config.production.js 

module.exports = {
  locals: {
    resetPasswordUrl: '@{{ $resetPasswordUrl }}',
  }
}
```

```html
<!-- template -->

<extends src="src/layouts/master.html">
  <block name="template">
    <a href="{{ resetPasswordUrl }}">Link</a>
  </block>
</extends>
```

In both cases:

```sh
maizzle serve

# <a href="https://example.com">Link</a>
```

```sh
maizzle build production

# <a href="{{ $resetPasswordUrl }}">Link</a>
```

Hope this helps, feel free to reopen if this is still an issue for you.

**Comment by seyfer** [comment]
@cossssmin I have only one problem - special symbols.

```
  "website_url": "@{{ $page->website_url }}",
```
turns into
```
<a href="{{ $page-&gt;website_url }}"
```

and 
```
  "website_url": "@{{ $page['website_url'] }}",
```
turns into
```
<a href="{{ $page[&#039;website_url&#039;] }}"
```

How can I prevent it?
