### ISSUE TITLE
Integrating Maizzle with Laravel framework to share tailwind.config.js

### ISSUE THREAD

**Issue by connecteev** [maizzle/framework#294]
- Maizzle Version: #.#.# 2.0
- Node.js Version: #.#.# 12
- Laravel Version: #.#.# 7 (soon to be 8.*)

I have tried Maizzle as a standalone repo, it works really well..but the whole point of moving to Maizzle was to use Tailwind, so I could share the same tailwind config (and styles). 

How do you integrate Maizzle into a Laravel app, so that the *same* tailwind.config.js file can be shared?

Context and use-case: I am using Laravel as a framework for my backend, which also does email sending. I am currently using MJML's native app to create emails visually, export the HTML, and paste it into the file...variables and all are added to MJML in this format: ```{{ $varName }}``` and are preserved during export. The problem with MJML is that I can't re-use my tailwindcss config or styles...so the emails don't look "on-brand". So, I am trying to move all my templates from MJML over to Maizzle.

**Comment by cossssmin** [comment]
You can define the path to the Tailwind config file you want Maizzle to use: https://maizzle.com/docs/build-config/#tailwind

Though, I would advise against doing that, since the default Tailwind config is meant for web development, and many things won't work in email clients (i.e. flex, text/bg opacity, rem units...)

**Comment by connecteev** [comment]
That's a good point, @cossssmin - I am basically looking for a way to re-use 2-3 things in my webapp's tailwind.config.js:
- colors
- fonts and typography
- spacing
- tailwindUI

So I am wondering if any of these could work:
1. Re-use the webapp's tailwind.config file and not use / ignore the styles for flex, text/bg opacity, rem units

2. maybe there's a way to build a tailwind config re-using just those bits (colors, fonts and typography, spacing, tailwindUI) from the webapp's tailwind config.

Not sure if you have explored any of these before...if not or if I'm getting off-topic, let me know! But if I solve this, it'll make my web + email development workflow quite streamlined 💪

**Comment by cossssmin** [comment]
You could `require` your web `tailwind.config.js`, merge it with a custom Tailwind config object that does overrides for email, and then pass this new objecty to `build.tailwind.config` in Maizzle's `config.js`:

```js
// config.js

const { merge } = require('lodash')

const twconfig = merge(
  require('path/to/your/web/tailwind.config.js'),
  {
    theme: {
      extend: {
        spacing: {
          full: '100%',
          64: '64px'
        }
      }
    },
    corePlugins: {
      animation: false,
      backgroundOpacity: false,
      borderOpacity: false,
      divideOpacity: false,
      placeholderOpacity: false,
      textOpacity: false,
    }
  }
)

module.exports = {
  build: {
    tailwind: {
      config: twconfig
    }
  }
}
```

So this way you don't need two `tailwind.config.js` files, you're just adapting your web config to email, right inside the `config.js` which you already use. And you don't need to disable utilities like `flex`, just don't use them.

Note that `spacing.full` is used with `@apply` in `src/assets/css/custom/reset.css` so you need to define it or the build will fail.

**Comment by connecteev** [comment]
@cossssmin Thank you, this is brilliant - I didnt know you could do this with lodash this way! I am going to try this approach (and different permutations of it) and report back what I find.

**Comment by cossssmin** [comment]
Feel free to reopen ✌

**Comment by seyfer** [comment]
@connecteev how do you pass data from Laravel to Maizzle template? Let's say you want to fetch some User model and then you have some data array as `['name => $user->name, ... etc]`. How do you pass it to Maizzle?

**Comment by vesper8** [comment]
@connecteev @seyfer I also would like to know more about how to use Maizzle with Laravel blade templates where you access data passed to the Mailable and do Laravel Blade loops and ifs and all that good stuff

I understand previously there was https://github.com/maizzle/maizzle-php to handle this but that's been archived now.. is there a new best practice guide or demo lying around?

**Comment by connecteev** [comment]
@seyfer @vesper8 I apologize but I've completely put coding on pause for now...going through some life events. I would try to answer but I dont recall and wouldnt be able to without digging deeper.

**Comment by seyfer** [comment]
hey guys, I solved it.
@vesper8 @connecteev what I do, I put Laravel escaped template functions in Maizzle template

when Maizzle build, I have 2 build targets - HTML and blade.html
In HTML I have variables resolved to values, so I can develop and test in browser
for blade.html build I put there Laravel blade constructs instead of values, like `{{ $user->name }}` and then I just copy-paste generated blade.html to a proper place in Laravel app and use it in email.

**Comment by cossssmin** [comment]
@seyfer you can also have Maizzle output it for you in your Laravel app directory instead of copy-pasting it - see the `build.destination` option.

**Comment by bretto36** [comment]
> hey guys, I solved it. @vesper8 @connecteev what I do, I put Laravel escaped template functions in Maizzle template
> 
> when Maizzle build, I have 2 build targets - HTML and blade.html In HTML I have variables resolved to values, so I can develop and test in browser for blade.html build I put there Laravel blade constructs instead of values, like `{{ $user->name }}` and then I just copy-paste generated blade.html to a proper place in Laravel app and use it in email.

Any chance you can elaborate further on how you made it work with blade??

**Comment by vesper8** [comment]
It would be so amazing to have a Medium (or other) tutorial explaining how to get the newly released Maizzle v4 to work with Laravel blade templates with the use of variables such as `{{ $user->name }}` inside the template.

**Comment by cossssmin** [comment]
For that you just need to ignore expressions:

https://maizzle.com/docs/templates#ignoring-expressions

Or you could configure PostHTML to use different delimiters:

https://maizzle.com/docs/configuration/posthtml#options
