### ISSUE TITLE
Recommended tools / workflow for creating Responsive HTML emails before bringing them into Maizzle?

### ISSUE THREAD

**Issue by connecteev** [maizzle/framework#295]
- Maizzle Version: #.#.# 2.0
- Node.js Version: #.#.# 12

@cossssmin last one for today, I promise. Sorry for the barrage of tickets today, I dedicated this weekend to migrating all my emails over to Maizzle. 
I am looking for a recommendation for creating responsive HTML emails that work across most (if not all) email-clients: Gmail, Outlook being the primary ones. Tools like MJML hide all this complexity from you using MJML tags, which is nice...but when using raw HTML for Maizzle, you have to deal with code like this:
```
    <table align="center" border="0" cellpadding="0" cellspacing="0" role="presentation" style="width:100%;">
      <tbody>
        <tr>
          <td style="direction:ltr; padding:20px 0; text-align:center;">
            <!--[if mso | IE]>
              <table role="presentation" border="0" cellpadding="0" cellspacing="0">
                <tr>
                  <td class="" style="vertical-align:top;width:600px;">
            <![endif]-->
```
(the above was generated by MJML - manually editing and maintaining the mso | IE snippets, tables with cellpadding and cellspacing etc are just incredibly frustrating)

The migration thus far has been incredibly painful and time-consuming, so I'd love your recommendation - what tools and workflow do you use to create beautiful, HTML5 responsive emails that are cross-platform? Do you start in another tool and export into Maizzle,manually replacing all inline styles with Tailwindcss classes? That's what I've been doing so far and it's been a time-consuming, hair-tearing experience.

Any thoughts you could share? Thanks!

**Comment by cossssmin** [comment]
I just write HTML myself and style it with Tailwind, not using any other tools. Maizzle doesn't offer markup abstractions like MJML or Foundation for Emails, so if you need something like that I'd recommend just using those instead.

**Comment by connecteev** [comment]
Thanks @cossssmin that makes sense. I'm sure once I create a few email templates, the rest will be quicker to create (perhaps even copy-paste). It's always the tables and outlook / IE-specific stuff that trip me up :)
