### ISSUE TITLE
Plaintext doesn't seem to be outputting

### ISSUE THREAD

**Issue by TreyBastian** [maizzle/framework#299]
- Maizzle Version: ^2.1.0
- Node.js Version: 10.19.0

I followed along with the documentation to enable plaintext output on template creation via Front matter and it doesn't seem to generate the txt files to go along with the generated html.

**Comment by cossssmin** [comment]
Thanks for spotting this, fixed in [`v2.1.1`](https://github.com/maizzle/framework/releases/tag/v2.1.1) 👍
