### ISSUE TITLE
Production minification not working without customizing html-crush

### ISSUE THREAD

**Issue by Sgouws** [maizzle/framework#307]
- Maizzle Version: 2.1.2
- Maizzle CLI Version: 1.0.4
- Node.js Version: 13.10.1

Adding the `minify` option to `config.production.js` does not minify the final code when building for production.

```
minify: {
    enabled: true,
  },
```

It requires that you customize your html-crush options before minification works. 
Perhaps I'm misinterpreting the docs, but my understanding is that adding that option should get minification working, albeit with defaults.

**Comment by cossssmin** [comment]
Indeed, `removeLineBreaks` is `false` by default in html-crush, so it won't minify unless you also manually set that to `true`.

Thanks for flagging this, I agree it should just work when you enable minifying. I'll add a PR that fixes this in a moment 👍
