### ISSUE TITLE
Escaping baseImageURL prepending for 1 specific URL

### ISSUE THREAD

**Issue by paambaati** [maizzle/framework#327]
- Maizzle Version: latest
- Node.js Version: latest

I have a template where I use a [Content-ID embedded image](https://sendgrid.com/blog/embedding-images-emails-facts/), so it will look like this —

```html
<img src="cid:my-image.jpg"/>
```

How do I prevent Maizzle from prepending the `baseImageURL` to this specific `img` tag?

**Comment by cossssmin** [comment]
You can only disable it for an entire template, not on an ing tag basis:

https://maizzle.com/docs/base-image-url/#disabling

**Comment by paambaati** [comment]
That's unfortunate. I tried rewriting the `src` tag using `extraAttributes`, but that didn't work either.

What would you recommend I do?

**Comment by cossssmin** [comment]
I’d stay away from embedded images in the first place, they don’t work everywhere and increase the email size. It’s old tech for old desktop clients. 

But if you still want to go through with it, maybe try having the src attribute named something else originally, then rename it with `replaceStrings`:

https://maizzle.com/docs/code-cleanup/#replacestrings

**Comment by paambaati** [comment]
@cossssmin Thanks, the `replaceStrings` technique worked!

For anyone else stumbling upon this issue, here's what I did —

1. Set up the `img` tag with a custom tag **instead** of `src`.

    ```html
    <img data-custom-cid="">
    ```

2. Set up config to replace the custom tag with the `src` of your CID.

    ```js
    replaceStrings: {
        '\\s?data-custom-cid=""': ' src="cid:my-inline-image.jpg"',
    }
    ```
