### ISSUE TITLE
Color differences after removing your color scheme

### ISSUE THREAD

**Issue by ju5t** [maizzle/framework#337]
- Maizzle Version: 2.3.0
- Node.js Version: 14.13.1

I read that you use your own color scheme. I removed it from the tailwind config but the color difference is still there compared to a website running on tailwind. It's like everything shifted a tint down, e.g. bg-green-500 is nearly the same color in maizzle as bg-green-400 is on our website.

I even copied the entire color stub from tailwind into the maizzle config, that didn't make a difference either.

I must be doing something wrong myself. Any suggestions?

Very, very cool project by the way. Thanks for all the effort you put into this!

**Comment by cossssmin** [comment]
Maizzle `extend`s Tailwind's colors by replacing them with the ones from Tailwind UI (which are a bit more vibrant). If you remove the `colors` key in `tailwind.config.js`, it will simply use whatever defaults Tailwind comes with.

If it's different from other projects you use Tailwind in, those other projects might use different colors or a different Tailwind version that has different colors. Maizzle 2.3.0 will install the latest 1.8.x Tailwind version.

P.S.: starting with Tailwind 2.0, Maizzle will not include the `colors` key in `tailwind.config.js` anymore - it'll just use the defaults.

**Comment by ju5t** [comment]
@cossssmin I found it. We're using @tailwindcss/ui. This comes with different colors. I didn't know it did and once I found out, I enabled it in Maizzle and everything's good to.

Thanks for the quick reply!
