### ISSUE TITLE
Unexpected curly bracket cut in production build

### ISSUE THREAD

**Issue by slavarazum** [maizzle/framework#347]
- Maizzle Version: 2.3.1
- Node.js Version: 12.18.1

Let's take example:
```html
<raw>
  <div style="background-image: url('{{ $some }}')">
    Some test
  </div>
</raw>
```

it transpiles correctly in `local` build mode:
```html
<div style="background-image: url('{{ $some }}')">
  Some test
</div>
```

and we got this in production build:

```html
<div style="background-image: url('{{ $some}')">
  Some test
</div>
```

One closing bracket is missing.

Also, we can make raw expression with this syntax and will take the same result:

```html
<div style="background-image: url('@{{ $some }}')">
  Some test
</div>
```

**Comment by cossssmin** [comment]
It's an issue with [`mergeLongHand`](https://maizzle.com/docs/css-inlining/#mergelonghand), specifically this line is wrong and `mergeLongHand` will always be enabled:

https://github.com/maizzle/framework/blob/9da0028c98ee7ca678fc294755bf33bad0cbe94f/src/transformers/inline.js#L36

I'll push a fix soon so you can actually disable it as explained in the docs linked above.

PostCSS is causing this issue, it's tripping on that `{{ }}` in the value. Until we can get a fix in [`posthtml-postcss-merge-longhand`](https://github.com/posthtml/posthtml-postcss-merge-longhand), the only way around it will be to disable `mergeLongHand` (which will actually work in the next Maizzle release).

**Comment by cossssmin** [comment]
@slavarazum published [`v2.3.2`](https://github.com/maizzle/framework/releases/tag/v2.3.2), disabling `mergeLongHand` now works (and it's disabled by default); the curly braces are output correctly now, please update and give it a try.

**Comment by slavarazum** [comment]
Great, now it works as expected!
Thank you for quick response.

**Comment by cossssmin** [comment]
Thanks for confirming. I'll go ahead and close the issue since it's not affecting Maizzle by default anymore, and will try to fix it in that PostHTML plugin 👍

**Comment by cossssmin** [comment]
Fixed the plugin (https://github.com/posthtml/posthtml-postcss-merge-longhand/commit/523935f1e5ad45ffdaf24bf9113a7908245f6e00), there was a loose regex that was catching the second `}` in `{{ }}`. You should now be able to safely use `mergeLonghand: true` in your `inlineCSS` options, in order to keep the old behavior of shorthanding inlined CSS.

I think I'll keep `mergeLonghand` disabled by default, so that the HTML output is what you'd expect.
