### ISSUE TITLE
Ability to move node_modules folder from root directory

### ISSUE THREAD

**Issue by slavarazum** [maizzle/framework#351]
Starting from the 1.0 version Maizzle requires to install all dependencies in the same directory with `src` folder.

It forces us to have 2 different `package.json` files in one project if we use Maizzle with another frameworks like Laravel. As a result 2 `node_modules` folders. It's harder to support.

Before 1.0 version this script worked for me:

```json
"scripts": {
    "build-emails": "cd resources/maizzle; ../../node_modules/.bin/maizzle build",
}
```

Now we have error:

```
Error: Cannot find module './node_modules/@maizzle/framework/src'
```

As I understood it related with `importCwd` usage.

**Comment by cossssmin** [comment]
Hmm, might be the same reason behind maizzle/cli/issues/44

Can you show me how you have it setup in Laravel?

**Comment by slavarazum** [comment]
This is example how I have solved it in earlier versions: https://github.com/slavarazum/laravel-maizzle

Just added scripts and changed destination config: https://github.com/slavarazum/laravel-maizzle/commit/7d26d2aa761a8174677962873aaba6ed20ee3687

Run: `npm run build-emails` or `npm run build-emails-prod` from root directory.

**Comment by cossssmin** [comment]
So you could get it working with a `bootstrap.js` file in your project root, sort of like we had it in the past.

Here's how you'd do it:

1. First, install the latest Maizzle framework and CLI:

```diff
# package.json

"dependencies": {
-  "@maizzle/cli": "0.1.2",
-  "@maizzle/framework": "0.3.1", 
+  "@maizzle/cli": "^1.0.4",
+  "@maizzle/framework": "^2.6.0",
 }
```

2. Inside `laravel-maizzle/resources/maizzle`, create `bootstrap.js`:

```js
// build for development by default
const env = process.env.NODE_ENV || 'local'

require('@maizzle/framework').build(env)
```

3. Update your `npm` script to look like this:

```diff
# package.json

"scripts": {
-  "build-emails": "cd resources/maizzle; ../../node_modules/.bin/maizzle build",
+  "build-emails": "cd resources/maizzle; cross-env NODE_ENV=production node bootstrap",
```

Tested it and it works fine from the Laravel project root.

---

As far as the CLI goes, I think we could do a try/catch that first checks for a `bootstrap.js` (like we did in the past), with a fallback to importing the bin relative to the current working directory (like today).

**Comment by cossssmin** [comment]
Added a `--bin` option in [CLI v1.2.0](https://github.com/maizzle/cli/releases/tag/v1.2.0) - that could work too :)

**Comment by slavarazum** [comment]
Wow, great solution! I have already tried it and it's working as expected 👍 
I'm really appreciated for your support. I think that the easier Maizzle is to integrate into existing projects with own structure, the more popular it will be.
