### ISSUE TITLE
Problem with background-color and border-color in gmail after testing with litmus

### ISSUE THREAD

**Issue by schirliuradu** [maizzle/framework#371]
- Maizzle Version: 2.6.2
- Node.js Version: 12.19.0

Hi Cosmin, 

When trying to test my new templates with Litmus, i noticed there is an issue with gmail. The problem is that there are no backgrounds, border colors and even text-colors. 

After debugging a little bit, i figured out that it is a problem related to some transformers (i think). When you have "bg-orange-500" or even a border "border-orange-500", and you build for production (using production config), you'll have in the compiled final file something like this:

(example of tag with bg color or border color)
```
<table style="border:1px solid;--bg-opacity:1;background-color:#ffffff;background-color:rgba(255,255,255,var(--bg-opacity));--border-opacity:1;border-color:#e2e8f0;border-color:rgba(226,232,240,var(--border-opacity));border-radius:4px;width:100%;" bgcolor="rgba(255, 255, 255, var(--bg-opacity))" cellpadding="0" cellspacing="0" role="presentation">
```

As you can note, there is background-color 2 times, and second one that gmail doesn't like (background-color:rgba(255,255,255,var(--bg-opacity));). Is there a transformer that fixes this? I have a default ``config.production`` file, with just added bgColor as extra attribute. 

Thank you.

**Comment by cossssmin** [comment]
Those are the color opacity utilities from Tailwind, disable them in your Tailwind config like we do in the [starter](https://github.com/maizzle/maizzle/blob/master/tailwind.config.js#L250:L257).

**Comment by schirliuradu** [comment]
Ok, thank's. This worked for me. My fault i thought i had the default config file but it was a bit different. 

Noticed another issue with classes, and it could regard css inlining also. After testing on litmus noticed that i had some columns without "width" property in inlined css. 

When you have for example 3 columns, one beside the other, and you give them class ``w-1-3 sm-table sm-w-full``, it should keep just classes needed for responsiveness, and inline only ``width`` property (in this case). Noticed that there wasn't ``width`` property (in this case) after css inliner passed, and every column takes automatically the width of its content, and this is wrong (at least in my use case). 

Noticed that this happens only with width classes that have to be inlined in float width values. For example: ``w-1-3`` will be ``33.333%`` and this doesn't work, as ``w-2-3`` and many others. If you have ``w-1-5`` that is equivalent to ``20%`` works fine. 

You don't notice this during development because there's no css inlining and you have right width classes

**Comment by cossssmin** [comment]
I'm not able to reproduce this, I just tested `w-1/3` on a table and table cell and they both work fine:

- `<td class="w-1/3 sm:w-full">` => `<td class="sm-w-full" style="width: 33.333333%;">`
- `<table class="w-1/3 sm:w-full">` => `<table class="sm-w-full" style="width: 33.333333%;">`

Maizzle has options to [duplicate inline sizes as attributes](https://maizzle.com/docs/css-inlining/#applywidthattributes), as well as [preferring size attributes](https://maizzle.com/docs/css-inlining/#keeponlyattributesizes), make sure they're not configured in such a way that both are removed.
