### ISSUE TITLE
Can't see changes in emails templates unless I close server and run it again

### ISSUE THREAD

**Issue by SlimBN** [maizzle/framework#386]
- Maizzle Framework Version: 3.0.1
- CLI Version: v1.2.0
- Node.js Version: 15.0.1
- Environment : Mac OSX Catalina

`✔ Built 2 templates in 2443 ms.
[Browsersync] Access URLs:
 -------------------------------------
       Local: http://localhost:3000
    External: http://192.168.1.13:3000
 -------------------------------------
          UI: http://localhost:3001
 UI External: http://localhost:3001
 -------------------------------------
[Browsersync] Serving files from: build_local`

**Comment by cossssmin** [comment]
Could be because of some dependency incompatibility with Node 15, we haven't tested for that yet.

**Comment by cossssmin** [comment]
Feel free to reopen if this still an issue with `v3.1.0`.
