### ISSUE TITLE
How to deal with single quotes in locals?

### ISSUE THREAD

**Issue by raphaelgoetter** [maizzle/framework#389]
- Maizzle Version: 3.0.1
- Node.js Version: 14

Hello,

I need to display single quotes in my locals values (in my screenshot `Villeneuve d'Ascq`) , but json refuses them (even when escaped).

Do you have a solution?

<img width="603" alt="Capture d’écran 2021-01-06 à 09 37 29" src="https://user-images.githubusercontent.com/491029/103751998-66874180-5009-11eb-9733-009bcbf46784.png">

**Comment by cossssmin** [comment]
You could replace the single quote with an HTML entity, like `&rsquo;` or `&apos;`:

```html
<component locals='{
    "mediaPlace": "Stade Pierre Mauroy, Villeneuve d&rsquo;Ascq"
  }'>Réserver</component>
```

When using HTML entities, your component should use triple curly braces for outputting variables:

```diff
- {{ mediaPlace }}
+ {{{ mediaPlace }}}
```

**Comment by raphaelgoetter** [comment]
Could work, thank you 👍

**Comment by raphaelgoetter** [comment]
> When using HTML entities, your component should use triple curly braces for outputting variables:

Also, is there a documentation for this? Didn't find it.

**Comment by cossssmin** [comment]
You're right, missed it, need to add it to our docs as well. 

https://github.com/posthtml/posthtml-expressions#unescaped-locals

**Comment by cossssmin** [comment]
Added:

https://maizzle.com/docs/templates/#unescaping-variables
