### ISSUE TITLE
Markdown-it issue when parsing blockquotes passed as variables

### ISSUE THREAD

**Issue by jbtheard** [maizzle/framework#391]
- Maizzle Version: 3.0.1
- Node.js Version: 15.4.0

Hi! and thanks A LOT for bringing this awesome tool to us.

I'm new to it and face an issue when parsing markdown quotes fetched remotely.

The following quote, directly inserted as text in the tag
```html
<md>
 > Blockquote
</md>
```
will be transformed successfully as block quote:
```html
<blockquote>
<p>Blockquote</p>
</blockquote>
```

But when I try to pass markdown as a page variable; it won't
```html
<md>{{page.data.markdown}}</md>
```
will result in
```html
<p>> Blockquote</p>
```

Note that other markdown properties will work OK but these quotes won't. 

Am I missing something in the config perhaps?

**Comment by cossssmin** [comment]
Hi,

Can you share how you're setting `page.data.markdown`?

I tried this:

```js
// config.js
module.exports = {
  data: {
    markdown: "> Blockquote"
  }
}
```

```html
<md>
  Page markdown: {{ page.data.markdown }}
</md>
```

And it correctly rendered this:

```html
<p>Page markdown: &gt; Blockquote</p>
```

It might also be because of Node 15, which we haven't tested with yet - I've seen a few other libraries that we use are not yet compatible with Node 15 (i.e. Browsersync).

**Comment by cossssmin** [comment]
You'll need to use `{{{ }}}` to output your `page.data.markdown`:

```html
<md>
  {{{ page.data.markdown }}}
</md>
```

Added a test (7b05e40) to prove this works.

Assuming `page.data.markdown` is equal to `> Blockquote`, note that this won't work, as it's not considered a blockquote in markdown:

```html
<md>
  Test: {{{ page.data.markdown }}}
</md>
```

Same thing if you have text before the `>` in a variable:

```js
// config.js
module.exports = {
  data: {
    markdown: "Example: > Blockquote" // outputs 'Example: &gt; Blockquote'
  }
}
```

**Comment by cossssmin** [comment]
Added a note on unescaping data: https://maizzle.com/docs/templates/#unescaping-variables

Feel free to reopen if you're still encountering issues.
