### ISSUE TITLE
Error message at build since update v3.1.1

### ISSUE THREAD

**Issue by sdelon** [maizzle/framework#395]
- Maizzle Version: 3.1.1
- Node.js Version: 12.18.3

Hi, on a fresh install, I can't build emails. When I run "maizzle build production", I keep having this error message 
`
× Failed to compile template: transactional.html
‼ arrayiffy__default.default is not a function  
√ Built 0 templates in 4713 ms.
`
Thanks for your help !

**Comment by cossssmin** [comment]
Do you have anything custom in your config?  Or are you using any Tailwind plugins?

**Comment by sdelon** [comment]
No Cosmin, I didn't changed anything in the config and don't use any Tailwind plugins. Everything worked great until this morning. So I tried a fresh new install with "Maizzle new" and right away run "Maizzle build production". I still get the same error message. 
While trying to find the reason behind this error message, I saw that the package arrayiffy-if-string has upated yesterday. Could it be the reason ?

**Comment by cossssmin** [comment]
Hmm, could be, since we don’t lock dependencies... let me get home and look into it tonight, thanks for the heads-up!

**Comment by sdelon** [comment]
Of course Cosmin :-) ! Thank you for your quick reply !

**Comment by cossssmin** [comment]
(closed by mistake, sorry)

Found the issue, it was a breaking change in an `email-comb` dependency that probably didn't respect semver and got installed as a minor release. Basically, it breaks only if you have `removeUnusedCSS` enabled. 

Working on a hotfix right now...

**Comment by cossssmin** [comment]
On this note, think I'll revert back to comitting `package-lock.json` so we stick with what we know works and we get automated PRs with failing tests for any such future cases...

**Comment by cossssmin** [comment]
Note: this was also breaking in case you had minification turned on, since both libraries use that dependency.

**Comment by cossssmin** [comment]
@sdelon fixed in [`v3.1.2`](https://github.com/maizzle/framework/releases/tag/v3.1.2), thanks for being so quick to report it 👍

**Comment by sdelon** [comment]
Hi Cosmin, Indeed if I set `removeUnusedCSS` to false, it builds perfectly ! Thanks for your quick reply again and thanks for this great email framework ;-)
