### ISSUE TITLE
Allow preview of non html extensions

### ISSUE THREAD

**Issue by khash** [maizzle/framework#403]
- Maizzle Version: 3.1.5
- Node.js Version: 12.18.4

When `templates.destination.extension` is set to something other than `html`, the preview UI doesn't show the preview but the browser tries to download the page. I guess this has something to do with the MIME encoding of the preview payload. A workaround is to use a browser to open the file but the experience is sub-optimal.

**Comment by cossssmin** [comment]
I don't think we can change that in Browsersync, but to fix it simply use `templates.destination.extension` only in your _production_ config (i.e. `config.production.js`), don't add it to the `config.js`.

**Comment by khash** [comment]
Thank you. That's a good approach and works.
