### ISSUE TITLE
Error: Framework not found

### ISSUE THREAD

**Issue by frederikagger** [maizzle/framework#404]
- Maizzle Version: 3.1.0
- Node.js Version: v12.18.2

Hi @cossssmin. 

When trying out the framework for the very first time I followed the installation guide in the docs. When I've scaffolded a project I and try to run the scripts in the package.json, none of them work for me.  I can see in node_modules that @maizzle is installed.
![image](https://user-images.githubusercontent.com/48592250/108385299-d0e7f000-720b-11eb-9d8d-95c7215c3bb2.png)

I get this error printed in the terminal:  
![image](https://user-images.githubusercontent.com/48592250/108384790-5c14b600-720b-11eb-9c14-4233939892a0.png)

Regards
Frederik

**Comment by cossssmin** [comment]
You need to run the `maizzle build` command(s) or `npm run ...` scripts while inside the root of your Maizzle project. 

This means that after you scaffold a project, you need to `cd` into its directory in your terminal; for example `cd maizzle` if you kept the default directory name to scaffold the project into.

**Comment by frederikagger** [comment]
I dont know what went wrong earlier. Its working now, so sorry for the issue opening!

**Comment by cossssmin** [comment]
No worries, glad you got it working :)

**Comment by val-samonte** [comment]
@cossssmin @frederikagger sorry i am definitely in correct directory but this one is still happening, would suggest to open this issue again.

tried both the plain and the custom starter and it still an issue, currently using Node v14.15.0

**Comment by cossssmin** [comment]
That error is also triggered if you don't have the NPM dependencies installed, make sure you ran `npm install` in the Maizzle project root and that `node_modules/@maizzle/framework` is there.

**Comment by val-samonte** [comment]
@cossssmin hi, thank you for your prompt response, yeah unfortunately i did make sure to npm install inside the newly created project 
![image](https://user-images.githubusercontent.com/767060/128052217-3b874dee-54e6-4d79-a0c4-0881f116e16c.png)

**Comment by cossssmin** [comment]
What does `npm list @maizzle/framework` say when you run it in the same place as you run the `maizzle build` command?

**Comment by val-samonte** [comment]
> What does `npm list @maizzle/framework` say when you run it in the same place as you run the `maizzle build` command?

Im getting this:
`-- @maizzle/framework@3.6.1

**Comment by cossssmin** [comment]
Can you share a repo reproducing the issue please?

It's definitely working, so there must be some path issue in your setup.

Might want to try removing node_modules and the package lock and re-installing everything again.

**Comment by val-samonte** [comment]
> Can you share a repo reproducing the issue please?

Sorry I am just starting and I just followed the getting started guide (both with the plain and custom starter)

> Might want to try removing node_modules and the package lock and re-installing everything again.

Sure, let me try this

**Comment by cossssmin** [comment]
Hold on, just managed to reproduce it...

**Comment by cossssmin** [comment]
Think I found the issue, `posthtml-fetch@2.1.0` is listing `is-url` under `devDependencies`; it should be under `dependencies`.

Will push a fix to that plugin in a moment...

**Comment by cossssmin** [comment]
cc @Scrum

**Comment by cossssmin** [comment]
Yup that was it, just published `posthtml-fetch@2.1.1` and it works now.

Re-install dependencies (remove node_modules and package lock first) and it should work now - thanks for catching this!
