### ISSUE TITLE
BrowserSync config

### ISSUE THREAD

**Issue by nathanforce** [maizzle/framework#405]
- Maizzle Version: 3.0.0

It looks like the option to pass BS config was reverted

https://github.com/maizzle/framework/commit/70742cbe7ca30c5a3ca868cd5e5d7f71493f1e6e#diff-bfe9874d239014961b1ae4e89875a6155667db834a410aaaa2ebe3cf89820556L51-L62

I'd like to be able to specify `port`. Is there another way?

**Comment by cossssmin** [comment]
It hasn’t been reverted, you can pass options as before (scroll down in that file you linked).

**Comment by nathanforce** [comment]
Hah! You are right. My mistake for being hasty.  My issue was that my `browsersync` options were not nested under `build`. Sorry for noise!
