### ISSUE TITLE
Unable to `Maizzle.render()` files that have includes

### ISSUE THREAD

**Issue by sharathprabhal** [maizzle/framework#42]
- Maizzle Version: 0.3.2
- Node.js Version: 11.4.0

### Description:

First off, you've done a great job with Maizzle. Exactly what I was looking for since I'm already a huge fan of tailwind. I want to use it server side inside my express app and here's the issue I'm running into.

Unable to `Maizzle.render()` the example file

### Steps To Reproduce:

Code
```
const str = fs.readFileSync(
  path.join(__dirname, 'src/templates/transactional.njk'),
  'utf8',
);

Maizzle.render(str, {
  tailwind: {
    config: require('./tailwind.config'),
    css:
      '@tailwind utilities; .myborder { @apply border border-solid border-gray-300; }',
  },
  maizzle: {
    config: require('./config.production'),
  },
})
  .then(console.log)
  .catch(console.error);
```

Receive the following error
```
{ Template render error: (unknown path)
  Error: template not found: src/partials/footer-links.njk
```

**Comment by genu** [comment]
Was this issue resolved? 

What is a workaround?

**Comment by cossssmin** [comment]
Nunjucks loads includes relative to where you execute the command, so your `{% include "..." %}` needs to specify the full path to that partial, _relative to the location you are executing the command from_. 

If you first `cd` into your project directory root and run that code from there, it works fine.

**Comment by cossssmin** [comment]
Reopening this based on maizzle/docs#17 - the `render()` method currently doesn't implement Nunjucks' `{% extends %}`, which makes it impossible to compile a template string that extends a layout.
