### ISSUE TITLE
<raw> tags are not escaping {{ }} variables

### ISSUE THREAD

**Issue by paambaati** [maizzle/framework#421]
- Maizzle Version: 3.2.0
- Node.js Version: 15.11.0

This is essentially https://github.com/maizzle/framework/issues/171 come back. If I downgrade to framework `3.1.6`, it works fine.

**Example**

This markup —

```html
<raw>
    <p>Hey {{ .Name }}!</p>
</raw>
```

is turned to —

```html
<p>Hey undefined!</p>
```

in framework `3.2.0`.

**Comment by cossssmin** [comment]
Looks like https://github.com/maizzle/framework/commit/394d0ae9bcb5b98ffb7fb200a60da52d02ea2f7f introduced this 🤦‍♂️ 

It's basically parsing expressions twice, so the second time it sees just `<p>Hey {{ .Name }}!</p>` without the `<raw>` tag and compiles it with the result you mentioned.

I'll have to revert that commit and try to tackle support for expressions in layout attributes right in [`posthtml-extend`](https://github.com/posthtml/posthtml-extend).

Thanks for spotting this!

**Comment by cossssmin** [comment]
(ugly) solution until I fix this:

```html
<raw>
    <p>Hey @{{ .Name }}!</p>
</raw>
```

**Comment by cossssmin** [comment]
I'm looking into removing this line in the `posthtml` generator, now since we also run it in the layouts plugin:

https://github.com/maizzle/framework/blob/adfdcd4ff60500f2eac12097a07bdd36ba3e0d9d/src/generators/posthtml.js#L57

I remember there was a reason why we needed to run the expressions plugin last, but I just can't remember. Need to test this more...

**Comment by cossssmin** [comment]
OK, so some of the reasons we evaluate expressions last were the `<fetch>` tag and possibly components.

Right now this also breaks the `<fetch>` tag functionality.

**Comment by cossssmin** [comment]
Released [v3.2.1](https://github.com/maizzle/framework/releases/tag/v3.2.1) which reverts the 'dynamic layouts' feature - sorry about that!

Working with the PostHTML team [here](https://github.com/posthtml/posthtml-extend/issues/35) on maybe introducing that feature in `posthtml-extend` itself.

**Comment by zaarheed** [comment]
@cossssmin Thanks for turning this around so quickly. I used maizzle for the first time earlier this week and only noticed this issue when trying to generate templates to use with SendGrid. Nice to see the bug has already been sorted.

What is the best way to upgrade to v3.2.1? Update the global CLI or the dependency in `package.json` or both?

**Comment by cossssmin** [comment]
> What is the best way to upgrade to v3.2.1? Update the global CLI or the dependency in package.json or both?

Bump the `@maizzle/framework` dependency version number in your `package.json`
