### ISSUE TITLE
Selective maizzle build (one specific template only)

### ISSUE THREAD

**Issue by holgerw** [maizzle/framework#423]
Command `maizzle watch` re-compiles only the one template that has been edited and saved, as to the documentation:

> Also, if you're editing a Template, Maizzle will only re-compile that Template, so changes are usually reflected in under a second. When making changes to files that have a global impact, like Layouts or Components, Maizzle will re-compile all Templates.

I would like to do similar file watching and selective compilation but applying the **production** config. Only command `maizzle build [env]` allows specifying the configuration to be applied.

My use case is compiling the maizzle templates to a different templating system (Elixir / Phoenix app). So on each save of a Maizzle template the corresponding Phoenix template should be updated.

Today as a workaround an external filesystem watcher can be used, running a `maizzle build [env]` when any file inside the maizzle folder is saved. But it is quite slow, as `maizzle build` compiles all templates, not only the edited one.

I see 2 possibilities to improve the described use case:

1) `maizzle build [env] template` accepts the name of a template to compile selectively.
2) `maizzle watch [env]` allows specifying a configuration to be applied on configuration.

Solution 2) would be better, as solution 1) pushes to the external filewatcher the complexity to classify if an edit/save was on a template or on global file, demanding recompilation of all templates. Ideal would be to allow solution 2) to even disable serving **browsersync**, understanding that the core of `maizzle watch` is compilation, and serving is an optional add on, desired for some use cases.

Do you think expanding `maizzle watch` with a configuration is viable and desired? Could I help to implement it?

**Comment by cossssmin** [comment]
Good idea, just tested it out and using an environment name with `maizzle watch` works well.

Right now, the `serve` method that `maizzle watch` uses, accepts a Maizzle `config` object (since [v1.3.0](https://github.com/maizzle/framework/releases/tag/v1.3.0)) so you could theoretically create your own script, `require(@maizzle/framework)`, and run `Maizzle.serve(config)` with your own configuration.

However I just noticed that is slow as hell, so this is a good opportunity to improve things.

> Could I help to implement it?

You already did, I'll push the commit shortly and later today will update both the framework and the CLI to accept a `[env]` name in the `maizzle watch` command 👍

By the way, you might also be interested in the [`render` method](https://maizzle.com/docs/nodejs/), in case you're looking to render a Maizzle template programmatically.

**Comment by cossssmin** [comment]
Released [`framework@3.3.0`](https://github.com/maizzle/framework/releases/tag/v3.3.0) and [`cli@1.4.0`](https://github.com/maizzle/cli/releases/tag/v1.4.0) that adds `[env]` name support to `maizzle serve`.

**Comment by holgerw** [comment]
This is a great solution for my use case. My template edits and saves are picked up by `maizzle serve` and recompiled in 500ms. But I observed a strange **bug** that the configured output file extension is lost. Is it possible `maizzle serve` outputs always `.html` and ignores the configuration value?

My config `config.production.js`:

`
module.exports = {
  build: {
    templates: {
      destination: {
        path: '../lib/vivento_job/templates/email',
        extension: 'html.eex',
      },
      assets: {
        source: 'src/assets/images',
        destination: '../../../../assets/email/images'
      }
    }
  },
  inlineCSS: true,
  removeUnusedCSS: true
}
`

And I run `./node_modules/.bin/maizzle serve production` from a script. Files are output to the correct location. Settings like inlineCSS and removeUnusedCSS are respected. But the extension is ignored seems to be ignored.

**Comment by cossssmin** [comment]
Ah right... The initial purpose of watching files was to be able to display them in a browser, that's why we don't do anything to the extension there. Now it would make sense to do it, thanks for bringing it up 👍

**Comment by holgerw** [comment]
@cossssmin Could hint at the code responsible for the extension? I would try a PR.

**Comment by cossssmin** [comment]
Fixed, will work in the next release.
