### ISSUE TITLE
`img` ignoring `<raw>`

### ISSUE THREAD

**Issue by jensenbox** [maizzle/framework#424]
- Maizzle Version: 3.3.0
- Node.js Version: 14.16.0

This issue might be best as 2 different issues but leaving them all in one so that the context of discovery might be linked:

I stumbled upon this when trying to get my root need satisfied: I am using Maizzle to generate django templates that will end up getting rendered when they are used and the image url is getting modified under all conditions.

When using the `baseImageURL` setting, both of these lines render with the image URL prepended.

```
<img src="logo.png" width="200">
<raw><img src="logo.png" width="200"></raw>
```

I would like to be able to have the image url untouched but still get all the other email compliant attributes so that I can use django tags within the src attribute:

Desired input:
```
<img src="{% static "email/logo.png" %}" width="200">
```

with an output of:

```
<img src="{% static "email/logo.png" %}" style="border: 0; line-height: 100%; max-width: 100%; vertical-align: middle">
```

I recognize that I can use `@` for tags so I tried:

```
<img src="@{% static "email/logo.png" %}" width="200">
```

but the output was nowhere near anything useable:
```
<img src="/static/email/@{% static " email="" logo.png"="" %}"="" width="200" style="border: 0; line-height: 100%; max-width: 100%; vertical-align: middle">
```

I fully recognize that the following is naive but I wanted to try it anyway:

```
<img src="<raw>{% static "email/logo.png" %}<raw>" width="200">
```

The output was even more comical:

```
<img src="/static/email/<raw>{% static " email="" logo.png"="" %}<raw="" style="border: 0; line-height: 100%; max-width: 100%; vertical-align: middle" alt="">" width="200">
```

Looking at the transformer implementation it appears that the transform is a "bull in a china shop" style grep replacement.

My request is:
Can we disable img src modification somehow? Ideally this would be able to use the `@` prefix but I understand there may be more to it. Perhaps if the src attributes first character is an `@` then skip all src url modification?

**Comment by cossssmin** [comment]
> Can we disable img src modification somehow?

Simply don't use the `baseImageURL` option.

> `<img src="{% static "email/logo.png" %}" width="200">`

Your problem comes from using double quotes inside double quoted attributes, which is invalid HTML. Change to:

```html
<img src="{% static 'email/logo.png' %}" width="200">
```

Ignoring with `@` in front of expressions or with `<raw>` is only for PostHTML expressions (see [docs](https://maizzle.com/docs/templates/#ignoring)), they do not have any effect on other templating languages, unless those also use `{{ }}` (so no effect on `{% %}`). 

> I fully recognize that the following is naive but I wanted to try it anyway:

`<raw>` is a tag, it can't be used inside attributes. For attribute values you have `@{{ }}`, which is not needed for your `{% %}` strings.

**Comment by cossssmin** [comment]
Feel ree to reopen 👍
