### ISSUE TITLE
Node render() doesn't seem to pick config data in page

### ISSUE THREAD

**Issue by jbtheard** [maizzle/framework#426]
- Maizzle Version: 3.3.0
- Node.js Version: 15.4.0

Probably not a bug but I cannot find my way to have my template generated programmatically via render() method.

On one side _maizzle serve production_ works as expected but whenever I use render() it seems that custom data passed to config object isn't picked at all.

- I add custom data to my config object at the _beforeRender_ step in both cases
- My pseudo html components access this data via _{{page.data.foo}}_ selector
- Config objects are similar when logged from the callback (the only difference being the presence of a _build.currentTemplates_ property in the _serve_ case )

... and yet the output html seems to have none of my _page.data_ data

I have narrowed down the issue to the _posthtml_ step of the render function but cannot explain why in one case it will work but not in the other

Any idea on how to debug would be highly appreciated.

**Comment by cossssmin** [comment]
Can you share or a repo that reproduces the issue?

**Comment by jbtheard** [comment]
> Can you share or a repo that reproduces the issue?

I'll work on isolating something later this week; thanks for picking up!

**Comment by jbtheard** [comment]
When isolated, issue doesn't reproduce so I guess I'll figure it out sooner or later. Closing issue for now.
