### ISSUE TITLE
How to prevent href encoding of handlebar tags in markdown links?

### ISSUE THREAD

**Issue by jbtheard** [maizzle/framework#427]
- Maizzle Version: 3.3.0
- Node.js Version: 15.4.0

I'm using Maizzle + Sendgrid.

when I declare my markdown content, I define links with escaped variable such as
`[my link](http://www.@{{variable}}.com)`

Expected:
`<a href="http://www.{{variable}}.com">my link</a>`

But markdown-it encode all links so the resulting html is 
`<a href="http://www.%7B%7Bvariable%7D%7D.com">my link</a>`

How would we ensure we keep original tags? Unfortunately [Transform Content](https://maizzle.com/docs/transform/) is not a solution... I looked into markdown-it config but could find where to set that... (how do we disable _normalizeLink_ rule perhaps?)

Happy to update the doc for some guidance as I guess it's quite a common case...

**Comment by jbtheard** [comment]
I managed to solved it myself using 
```
transform: {
    formatDate: str => str.replace(/&quot;/gm, '"')
  },
```

**Comment by cossssmin** [comment]
Can't find any way to disable href value encoding in markdown-it (don't think it's possible), so you can use `replaceStrings` in your Maizzle config instead:

```js
module.exports = {
  replaceStrings: {
    '%7B%7B': '{{',
    '%7D%7D': '}}'
  },
}
```

https://maizzle.com/docs/code-cleanup/#replacestrings
