### ISSUE TITLE
[TailwindCSS JIT] `maizzle serve` creates *.undefined files for templates on save

### ISSUE THREAD

**Issue by Xeevis** [maizzle/framework#435]
Maizzle Version: 3.4.0
TailwindCSS Version: 2.1.1
Node.js Version: 15.14.0

When running `maizzle serve` with TailwindCSS JIT mode, saving `src/templates/promotional.html` will generate `build_local/promotional.undefined` which contains the changes, but this won't update the page running on http://localhost:3000

```js
mode: process.env.NODE_ENV === 'local' ? 'jit' : 'aot',
  purge: [
    'src/**/*.html',
  ],
```

![image](https://user-images.githubusercontent.com/5835044/115083253-600d3d80-9f07-11eb-85d5-7f97e034e6e6.png)

**Comment by cossssmin** [comment]
Sorry about that, forgot to add a default extension when adding support for custom extensions in `maizzle serve`.

Fixed in `v3.4.1`.
