### ISSUE TITLE
How can I inject html via variable ?

### ISSUE THREAD

**Issue by jbtheard** [maizzle/framework#451]
Hi,

I'm trying to add to my template a html string passed as variable. 

Of course `<raw>{{page.data.myHtmlStringt}}</raw>` won't parse the variable and when within a block
```
<block name="template">{{page.data.myHtmlString}}</block>
```
it will be interpreted as string.

How could I do?

**Comment by cossssmin** [comment]
Output the unescaped string:

```html
<block name="template">
  {{{ page.data.myHtmlString }}}
</block>
```

Docs: https://maizzle.com/docs/templates/#unescaping-variables

**Comment by jbtheard** [comment]
So sorry I missed that! Thanks a lot it works as expected.
