### ISSUE TITLE
CSS is not applied correctly when running on node.js

### ISSUE THREAD

**Issue by yellow1912** [maizzle/framework#452]
- Maizzle Version: 3.5.0
- Node.js Version: 15.0.1

Hello,

Instead of using the CLI, I tried to run with node.js according to the document found here:

https://maizzle.com/docs/nodejs/

My HTML is a very basic html with tailwind classes, for the sake of testing lets try something like this:

```
<!DOCTYPE html>
<html>
        <body>
                <div class="text-xs m-5">test</div>
        </body>
</html>

```

My nodejs code looks like this (ES6):

```
import fs from 'fs';
import Maizzle from "@maizzle/framework";
import minimist from 'minimist';

var args = minimist(process.argv.slice(2));

if (args.hasOwnProperty('in-file')) {
  var inFiles = args['in-file'];

  if (typeof inFiles === 'string' || inFiles instanceof String) {
    inFiles = [inFiles];
  }

  inFiles.forEach(function (file) {
    var content = fs.readFileSync(file, "utf8");
    // var {html, config} = Maizzle.render(content);
    Maizzle.render(content, {
      maizzle: {
        env: 'production',
        inlineCSS: true,
        removeUnusedCSS: {
          removeHTMLComments: true
        },
        build: {
          templates: {
            destination: {
              path: 'build_production',
            },
          },
        },
      },
      tailwind: {
        css: '@tailwind utilities;',
        config: import('./tailwind.config.js'),
      }
    }).then(({html}) => console.log(html))
  })
}

```

My tailwind.config.js looks something like this: https://raw.githubusercontent.com/maizzle/starter-litmus/master/tailwind.config.js

When I run `node build.maizzle.mjs --in-file=test2.html` I get something like this:

```
<!DOCTYPE html>
<html>
        <body>
                <div>test</div>
        </body>
</html>
```

Seems like Maizzle stripped all classes and returns the bare html?

**Comment by cossssmin** [comment]
You are missing the CSS in the `<head>`, so there's nothing to inline and `removeUnusedCSS` will remove the classes from your HTML because they are not defined anywhere.

Update your HTML to either include the CSS like this:

```html
<!DOCTYPE html>
<html>
  <head>
    <if condition="page.css">
      <style>{{{ page.css }}}</style>
    </if>
  </head>
  <body>
    <div class="text-xs m-5">test</div>
  </body>
</html>
```

... or to extend a layout that includes it (such as [main.html](https://github.com/maizzle/maizzle/blob/master/src/layouts/main.html)), like shown in the [docs](https://maizzle.com/docs/nodejs/#example).

**Comment by yellow1912** [comment]
Lol, I thought page.css is a specific css file that you include only when you have it, didnt think of it as some kind of placeholder. Feeling so stupid now.

**Comment by cossssmin** [comment]
Not your fault, looking at it now I think we could do better in explaining that variable in the Node docs - i.e. show an example with the full layout, maybe separate from the one that uses `<extends>`.

**Comment by yellow1912** [comment]
I think Node.js document deserves some love :D. This way of using Maizzle is super useful when integrating with other platforms since we can have more control over the code. A few things that would be cool to have:

1. A version with ES6 (where require is not available)
2. If I set compiled string then the `css` config will not kick in at all right? (no compilation needed)

I didn't look much at the extend part (my fault) because I already generate the full html from another application and simply pass that string to maizzle for compilation.

**Comment by cossssmin** [comment]
`css` is the CSS to compile with Tailwind - this is where you use `@tailwind utilities` for example.

To skip Tailwind compilation, you can provide your own pre-compiled CSS under `tailwind.compiled` - in this case Maizzle will just use that, discarding anything in your `tailwind.css` key or in your `tailwind.config.js`.

See docs: https://maizzle.com/docs/nodejs/#tailwind

**Comment by cossssmin** [comment]
Updated the docs to make it clear that your template string needs to include the `{{{ page.css }}}` variable:

https://maizzle.com/docs/nodejs/#example

Feel free to reopen if you still encounter issues 👍
