### ISSUE TITLE
[Guidance] Best practice for code reuse in complex projects.

### ISSUE THREAD

**Issue by weenzeel** [maizzle/framework#453]
- Maizzle Version: 3.5.0
- Node.js Version: 14.15.1

I'm building an email template framework for my organization. And the documentation states that repetitive code should be extracted in to components.

@cossssmin Can you guide me on what is possible / best practice with Maizzle today for code reuse?

I've tried the approach ...

1. Use a base layout as a master for all templates.
2. Extend the base layout with a template per type of send out that we need.
3. Create a component hierarchy of nested components, e.g:

```xml
<component src="framework/wrapper.html">
    <component src="framework/card.html">
        <component src="project-a/card-content.html">
            <component src="framework/button.html">
            </component>
        </component>
    </component>
</component>
```

I'm having problems with the nested components. For the inner most component to be generic and reusable local data needs to be passed from card-content to the button. But this is failing to render in random ways when we pass local data to a component that is nested in another component (compilation sometimes fails to resolve a component to it's markup and just includes the component tag in the final markup). I've found other issues hinting that this is a bug caused by one of the dependencies of Maizzle.

So, using the hierarchy above as an example, the best we can do now is to nest components down to the first "stateful" component" and there reference global data from the layout (defined via a front matter or configuration file). Right?

Using the hierarchy above I would need to duplicate code for "button" to include it in different types of "card-content" with the correct reference to global data. Right?

Any hints on how to use the framework as intended for reusable abstractions is appreciated!

Thanks for making Maizzle available for us to try and use!

**Comment by cossssmin** [comment]
Can't offer much advice in this direction tbh, I've never done/needed to do such complex component nesting. 

I've used Maizzle in projects that compiled over 100 templates (many of them sharing multiple, sometimes identical, sections) but never needed to extract more than a header/footer/hero/button to components that I didn't have to nest. 

So my first concern here would be if I'm not perhaps doing premature abstractions - do you really need everything as a _nested_ component? From my experience I almost never had to nest components - just add them here and there throughout the template. Not saying you shouldn't do it, this is just my experience.

That being said, Components in Maizzle are not that advanced right now (see https://github.com/maizzle/framework/issues/397#issuecomment-770024798) - my advice is to think of them more like 'includes' and not like how you'd use them in something like Vue for example. Maybe I should have named them Modules, after [`posthtml-modules`](https://github.com/posthtml/posthtml-modules) which provides this functionality 🤔 

> But this is failing to render in random ways when we pass local data to a component

See #369

> And the documentation states that repetitive code should be extracted in to components.

We do say you can [extract _CSS_ components](https://maizzle.com/docs/tailwindcss/#components), but not that you should 🙂

P.S.: also have a look at [extending templates](https://maizzle.com/docs/templates/#extending-templates) - might be of use in your case.
