### ISSUE TITLE
[Question] Is it possible to use if condition based on the current build file extension?

### ISSUE THREAD

**Issue by seyfer** [maizzle/framework#454]
- Maizzle Version: #.#.#
latest ^3.5.0
- Node.js Version: #.#.#
v12.20.0

I have configured 2 build targets with different extensions for the output.

```
templates: [
      {
        source: 'src/templates/email',
        destination: {
          path: 'build_production',
        },
      },
      {
        source: 'src/templates/email',
        destination: {
          path: 'build_laravel',
          extension: 'blade.php'
        },
      },
    ],
```

The problem is that when I develop, I use fixtures variables as `{{ page.name }}` but for Laravel this should be `{{ $page['name'] }}`. Since JS also supports access by array, this approach {{ $page['name'] }} works in both HTML and blade.php extensions.
But then I faced another problem with assets. Let's say I have logo image. In HTML it will work just `href="images/logo.png"` and show it in preview.
For Laravel I need to wrap it in `href="{{ asset(images/logo.png) }}"`. I can put it in HTML, but then I will not have an image in the preview.

To solve it, I see only will be possible with something like
```
<if condition="page.build.extension == blade.php">
  // some
</if>
```

**Is it possible to achieve in any other way?**

I tried to create a custom config as `config.laravel.js` for that first to set a custom page variable only for `laravel` ENV.
`maizzle build laravel`
with config exactly as for `production`
But, the build was producing crazy nested `@media` queries in generated `<style>`. Like 5 nested media queries and empty inside. Even setting `NODE_ENV=production` did not help. I was able to fix it only by putting `blade.php` build in `production` config file. This is another bug btw.

**Comment by cossssmin** [comment]
You could use the (currently undocumented) `page.build.currentTemplates` object, which contains your `page.build.templates[x]` object for every iteration, when multiple `templates` sources are used.

With that you should be able to access the currently-being-built templates' extension through: 

```
{{ page.build.currentTemplates.destination.extension }}
```

Note that `page.build.currentTemplates` is only available to you inside a template, not in a config file.

However that might get tedious to write all the time, so I'd recommend using environment configs, as you suggested with `config.laravel.js`. You'd then write your HTML like this:

```html
<img src="{{ page.env === 'laravel' ? 'asset(images/logo.png)' : 'images/logo.png' }}">
```

Nested media queries shouldn't happen unless you've got something wrong in the layout - can you show your template and the layout it extends?
