### ISSUE TITLE
Questions about Components in Layouts

### ISSUE THREAD

**Issue by Blake32p** [maizzle/framework#457]
- Maizzle Version:3.5.0
- Node.js Version: v13.10.1

I have a queston about Components in Layouts. Previously I had code that would pull items like footers into a layout. `<component src="footer.html">
</component>`

I've noticed after upgrading to 3.5.0 that this is not working. If I copy the same code directly to my template it works, but I cant seem to get it to work in a layout?

**Comment by cossssmin** [comment]
Looks like a bug introduced in 3.5.0, specifically in https://github.com/maizzle/framework/commit/b800a99946b81f18a612225daf41ee59927ef0fc

Will fix it in the next release, thanks for reporting it 👍

**Comment by cossssmin** [comment]
Released [v3.5.1](https://github.com/maizzle/framework/releases/tag/v3.5.1) which includes a fix for this. Thanks again!
