### ISSUE TITLE
Ignoring raw indicator `@` in 3.5.1

### ISSUE THREAD

**Issue by jensenbox** [maizzle/framework#460]
- Maizzle Version: 3.5.1
- Node.js Version: 14

In 3.4.2 the following renders as expected:

```<html lang="@{{ language }}" xmlns:o="urn:schemas-microsoft-com:office:office">```

Which outputs:

```<html lang="{{ language }}" xmlns:o="urn:schemas-microsoft-com:office:office">```

However, in 3.5.1, the result is:

```<html lang="undefined" xmlns:o="urn:schemas-microsoft-com:office:office">```

**Comment by cossssmin** [comment]
Use [double escaping](https://maizzle.com/docs/components/#ignoring) like within Components:

```html
<html lang="@@{{ language }}" xmlns:o="urn:schemas-microsoft-com:office:office">
```

Will update the Layouts docs as well to mention this.
