### ISSUE TITLE
Prevent special symbols to be turned into html entities inside @{{ }}

### ISSUE THREAD

**Issue by seyfer** [maizzle/framework#461]
With this answer, I was able to generate Laravel compatible PHP template
https://github.com/maizzle/framework/issues/293#issuecomment-774433678

But seems like it works only for root-level variables, I cannot use structure access as an array or object.

I have only one problem - special symbols.

```
  "website_url": "@{{ $page->website_url }}",
```
turns into
```
<a href="{{ $page-&gt;website_url }}"
```

and 
```
  "website_url": "@{{ $page['website_url'] }}",
```
turns into
```
<a href="{{ $page[&#039;website_url&#039;] }}"
```

How can I prevent it?

_Originally posted by @seyfer in https://github.com/maizzle/framework/issues/293#issuecomment-834483051_

**Comment by cossssmin** [comment]
In your Maizzle config:

```js
// config.production.js
module.exports = {
  website_url: "@{{ $page['website_url'] }}",
}
```

In your template:

```html
<extends src="src/layouts/main.html">
  <block name="template">
    {{{ page.website_url }}}
  </block>
</extends>
```

**Comment by seyfer** [comment]
@cossssmin seems like I was very tired on Friday 😄  yeah sure it works!

**Comment by seyfer** [comment]
@cossssmin unfortunately, the page level variables are always staying escaped. I will create a new issue.
