### ISSUE TITLE
Google fonts have a new API

### ISSUE THREAD

**Issue by raphaelgoetter** [maizzle/framework#462]
- Maizzle Version: 3.5.1
- Node.js Version: 14.4.0

Hello,

Google Fonts has now a new API which isn't supported by Maizzle.

What [Maizzle doc](https://maizzle.com/docs/google-fonts/#google-fonts) says: 

```
googleFonts: "Prompt:200,400,700"
```

What [Google Fonts new API](https://fonts.google.com/specimen/Prompt?query=prompt) wants:

```
googleFonts: "Prompt:wght@200;400;700&display=swap"
```

If we try the latter, only the Regular version of the font is loaded.

**Comment by cossssmin** [comment]
For the new API, the URL in the Layout would need updating as well:

```diff
- <link href="https://fonts.googleapis.com/css?family={{ page.googleFonts }}" rel="stylesheet" media="screen">
+ <link href="https://fonts.googleapis.com/css2?family={{ page.googleFonts }}" rel="stylesheet" media="screen">
```

Right now both APIs work, so maybe we should just mention that in the docs until the old one is deprecated.

**Comment by raphaelgoetter** [comment]
Oh great thanks!

**Comment by cossssmin** [comment]
Actually went ahead and updated the docs and Starter to use the Google Fonts CSS API v2. Also added docs on how to use Google Fonts with `@font-face` - thanks for bringing this up 👍
