### ISSUE TITLE
Escape template level variables?

### ISSUE THREAD

**Issue by seyfer** [maizzle/framework#463]
- Maizzle Version: #.#.#
- latest
- Node.js Version: #.#.#
- v12 latest LTS

Given the setup we have discussed in #461 and #293 issues, I have this variable in `config.js` for Laravel
```
"fixtures": {
   "external_associate_invite": {
        "name": "@{{ $page['name'] }}",
    }
}
```

and this is how I output it in the template for unescaping
```
<h1>{{{ page.fixtures.external_associate_invite.name }}}</h1>
```

It works perfectly fine and produces
```
<h1>{{ $page['name'] }}</h1>
```

Then I wanted to do `title` in the same way. But `title` is a part of the `layout`.
In the Layout I have
```
<if condition="page.title">
    <title>{{{ page.title }}}</title>
  </if>
```

And I map this variable to my fixtures structure inside the template, on top of it
```
---
title: {{ page.fixtures.external_associate_invite.title }}
bodyClass: bg-gray-50
googleFonts: Barlow:wght@400;600;800
---
```

And it is not escaped. Okay, I tried to escape it like that
```
---
title: {{{ page.fixtures.external_associate_invite.title }}}
---
```

and I have an error in the console, when I build it
```
Failed to compile template: external_associate_invite.html
⚠ missed comma between flow collection entries at line 1, column 16:
    title: {{ $page['fixtures']['external_associate ...
```

What shall I do?

**Comment by seyfer** [comment]
What I did is that I abandoned usage of `layout` at all, leaving the main layout just with
```
<block name="raw-content"></block>
```

and then I moved all layout code to templates and there I can do
```
{{{ <title>{{{ page.fixtures.external_associate_invite.title }}}</title> }}}
```

But I am looking for a possibility to keep a layout, still being able to escape template level variables and not getting errors in the console. Any ideas?

**Comment by cossssmin** [comment]
Hey, sorry for the late reply, been very busy this month.

That sounds like a YAML error, try always wrapping expressions in double quotes:

```
---
title: "{{{ page.fixtures.external_associate_invite.title }}}"
---
```

Side note: in general, whenever stuff isn't escaped between Layouts and Templates (and shows as `undefined`), it's because PostHTML compiles Templates and Layouts individually, resulting in something like `@{{ var }}` being compiled to `{{ var }}`, which in the 'second' compilation step is evaluated to `undefined` if it's not in the `page` data object.
