### ISSUE TITLE
Documentation Enhancement Request

### ISSUE THREAD

**Issue by jensenbox** [maizzle/framework#466]
Hi,

I would be happy to write up docs on how to to internationalization but would prefer to get the "blessed" way to do it. The old-school `.po` files are great but all the cool kids appear to be using `i18next` - if there is an official stance on what to use, I can certainly take a stab at writing up how to do it.

Thanks!

**Comment by cossssmin** [comment]
This would have to be a [Guide](https://maizzle.com/guides/), so feel free to write one for the method you prefer. `i18next` does look good and I'd probably go with something like that since it's JavaScript 👍
