### ISSUE TITLE
Plaintext path is not a directory

### ISSUE THREAD

**Issue by aerni** [maizzle/framework#469]
I need to change the destination path and extension of my plaintext mails. The problem is, that the destination path expects a file name and not a directory. If you have multiple mails, you will end up with just one plaintext mail.

- Maizzle Version: 3.5.1
- Node.js Version: 16.0.0

**Comment by cossssmin** [comment]
I agree, we should allow using paths for plaintext - I'll work on this as part of moving the `plaintext` config key to under `build.templates` for config files (right now, if you use multiple template sources, you cannot individually opt-in for plaintext generation).
