### ISSUE TITLE
Can't configure conditionalTags

### ISSUE THREAD

**Issue by weenzeel** [maizzle/framework#470]
- Maizzle Version: 3.5.0
- Node.js Version: 14.15.1

Hello!

I'm including the following in my config.js file:

 ```javascript
 build: {
    posthtml: {
      expressions: {
        conditionalTags: ['when', 'ifnotthen', 'otherwise']
      }
    }
}
```

but still "when-, ifnotthen-, otherwise-tags" aren't recognized as conditional tags. Only if-tags work. Using anything else causes the actual conditional tags to be rendered in the markup.

Bug? Thanks!

**Comment by cossssmin** [comment]
Sounds like a bug, I'll look into it, thanks for reporting!

**Comment by cossssmin** [comment]
Just tested this in 3.5.2 and it all works fine:

```html
<when condition="page.env === 'production'">
  production
</when>
<otherwise>
  not in production
</otherwise>
```

Can you please update and test again?
