### ISSUE TITLE
Maizzle with tailwindcss@canary

### ISSUE THREAD

**Issue by holgerw** [maizzle/framework#473]
Should it be possible today to use maizzle (2.5.1) with tailwindcss@canary?

This would allow us to use the JIT correctly respecting disabled opacity plugins, without depending on a new maizzle release (https://github.com/tailwindlabs/tailwindcss/issues/4071).

I tried overwriting maizzle's tailwindcss dependency with npm-shrinkwrap, but it had no affect.

**Comment by cossssmin** [comment]
Maizzle needs to keep a tight check on the Tailwind version being used, since even feature releases can cause issues. New Tailwind version should be out soon though, I think - I'll add support right away once it does.

**Comment by cossssmin** [comment]
Released 3.5.2, JIT should work as expected now.
