### ISSUE TITLE
Maizzle ignores destination extension

### ISSUE THREAD

**Issue by richardhj** [maizzle/framework#485]
- Maizzle Version: 3.5.2
- Node.js Version: 16.3.0

In `src/`, I use templates with file suffix `.html.twig`. For production builds, I keep the original file suffix.

There was a prior version of maizzle where `.html.twig` suffixed did not work, but in the current version, this works fine for me. The contemporary issue is like the reverse issue of the old issue: I cannot override the `.html` suffix for serve and dev tasks:

### Setup

My config.js:
```js
module.exports = {
  build: {
    templates: {
      source: 'src/templates',
      filetypes: 'html.twig',
      destination: {
        path: 'build_local',
        extension: 'html',
      },
    },
  },
}
```

### Things to reproduce

1. Run `maizzle build` or `maizzle serve`
1a. ❌ The files inside `build_local` still have the `.html.twig` suffix and thus cannot be opened in the browser :-( 
2. Change `destination.extension` to something different, e.g., `txt` or `html5`.
2a. 🟡 The files get transformed to  `txt` or `html5` respectively correctly.
3. Change `destination.extension` to `.html` (contradicts to the documentation).
3a. ✅ The suffix now is `.html.twig..html`, which is working for me.

**Comment by richardhj** [comment]
Also, before running `maizzle buld production`, I have to remove the `destination.extension` config from `config.js`.
When setting `destination.extension` to `twig` inside `config.production.js`, it disables all transformers and bypasses whole posthtml processing.

### Steps to reproduce

config.js:
```js
module.exports = {
  build: {
    templates: {
      source: 'src/templates',
      filetypes: 'html.twig',
      destination: {
        path: 'build_local',
        extension: '.html',
      },
    },
  },
}
```
Files output under /build_local as `template.html.twig..html`.

#### Scenario 1

config.production.js:
```js
module.exports = {
  build: {
    templates: {
      destination: {
        path: '../templates/Email',
      },
    }
  },
}
```
❌  Outputs same files as in build_local

#### Scenario 2

config.production.js:
```js
module.exports = {
  build: {
    templates: {
      destination: {
        path: '../templates/Email',
        extension: 'html.twig'
      },
    }
  },
}
```

❌  Files have suffix `template.html.html.twig`

#### Scenario 3

```js
module.exports = {
  build: {
    templates: {
      destination: {
        path: '../templates/Email',
        extension: 'html.twig'
      },
    }
  },
}
```
❌  Files have suffix `template.html.html.twig` but posthtml is working

#### Scenario 4

config.production.js
```js
module.exports = {
  build: {
    templates: {
      destination: {
        path: '../templates/Email',
        extension: 'twig'
      },
    }
  },
}
```
❌  posthtml is not processing, raw output of source files (but destination file suffix is correct).

#### Scenario 5

✅ Solution: disable the `destionation.extension` from `config.js` prior to running prod build.

**Comment by cossssmin** [comment]
Will fix the `html` extension issue in local dev, that's a mistake. For the transformers not working I'll need to look into it and get back to you. Thanks for taking the time to write the detailed issue! :)

**Comment by cossssmin** [comment]
The PR linked above should fix this.

I've also tested Transformers and they also seem to work fine, make sure you only use the extension name (we're using `path.parse()`):

```js
module.exports = {
  build: {
    templates: {
      source: 'src/templates',
      filetypes: 'twig', // just 'twig' will do
      destination: {
        path: 'build_local',
        extension: 'html', // no dot before html
      },
    },
  },
}
```
