### ISSUE TITLE
Maizzle transforms HTML entities back to HTML.

### ISSUE THREAD

**Issue by socketopp** [maizzle/framework#486]
- Maizzle Version: ^0.4.4
- Node.js Version: 10.23.2

Hi, I have sanitised some user input from HTML injection and escaped the HTML code to their [entity name](https://www.w3schools.com/html/html_entities.asp). However when rendering with Maizzle, it transforms this back to HTML. Is it possible to just render the HTML entity? 

Example: 
`Cool link &lt;a href=&quot;https:&#x2F;&#x2F;google.com&quot;&gt;link text&lt;&#x2F;a&gt;`
Is transformed back to:
`Cool link <a href="https://google.com">link text</a>
`

I saw [this issue](https://github.com/maizzle/framework/issues/348) but it didn't do any difference unfortunately.
Is this due to config in postHTML? or something else?
Would appreciate any pointers or configs that would resolve this. 

EDIT:  Think I need to upgrade.

**Comment by cossssmin** [comment]
Yup, works fine in `3.5.2`. 

`0.x` was using Nunjucks (not PostHTML) and we no longer support it.
