### ISSUE TITLE
PostHTML renders `undefined` when no Front Matter value is specified

### ISSUE THREAD

**Issue by tylermmorton** [maizzle/framework#496]
- Maizzle Version: 3.0.0
- Node.js Version: 12.16.3

Hi all, firstly, thank you for building this wonderful tool chain. I love using Tailwind and when I saw Maizzle supported it out of the box I had to give it a try. 

I have a weird situation and I'm looking for suggestions on a workaround or fix. I'm trying to build some email templates that can be served from an application written in Go. There's a built in package in Go called `template/html` which parses HTML files-- It can replace tokens surrounded with `{{ }}` similar to how PostHTML and Front Matter seem to be working in Maizzle. 

The problem I'm running into is this: When I define tokens I want my Go application to replace in my template, IE `{{ .Name }}` -- PostHTML will attempt to replace this value with whatever is fed into it's config. In my case, I want the replacement to happen on the fly in Go so I haven't defined a value in Front Matter. The token ends up getting replaced with `undefined`. 

Example:
```
---
greeting: "Hello,"
---
<div>
  <p>{{ page.greeting }} {{ .Name }}</p>
</div>
```

Expected output:
```
<div>
  <p>Hello, {{ .Name }}</p>
</div>
```
Current output:
```
<div>
  <p>Hello, undefined</p>
</div>
```

Even the following still does not seem to work:
```
---
greeting: "Hello,"
nameToken: "{{ .Name }}"
---
<div>
  <p>{{ page.greeting }} {{ page.nameToken }}</p>
</div>
```

Is there a way to turn off this automatic replacement all together? Taking it a step further, does it seem possible to have PostHTML leave tokens that cannot be resolved untouched, instead of replacing them with `undefined`?

I apologize if this issue seems more specific to PostHTML. I figured I'd ask here before I move up the dependency chain. Any advice would be appreciated!

Thanks

**Comment by cossssmin** [comment]
You need to escape the curly braces if you want to output them, otherwise PostHTML will try to evaluate their contents as an expression.

Docs: https://maizzle.com/docs/templates/#ignoring

**Comment by tylermmorton** [comment]
You're a saint @cossssmin. I'm sad I didn't see that when looking through the docs. Thank you
