### ISSUE TITLE
posthtml-expression vertion updated, build results are not same as six month before

### ISSUE THREAD

**Issue by CaiyueDamowang** [maizzle/framework#502]
- Maizzle Version: 3.0.1
- Node.js Version: 14.17.2

posthtml-expression version: 1.62 -> 1.71

six month ago, run `maizzle build product`, i got good templates.

now, i run `yarn && maizzle build product`, the build results changed and i never change the origin templates.

i must run `npm ci` or fix the yarn-lock file, make posthtml-expression version 1.62 by myself.

Is there some resolution to fix it automantically ?

**Comment by cossssmin** [comment]
What has changed for you in the compiled HTML, that relates to posthtml-expressions?

You could probably use [npm shrinkwrap](https://nodejs.org/en/blog/npm/managing-node-js-dependencies-with-shrinkwrap/) to lock that dependency version.

**Comment by CaiyueDamowang** [comment]
nothing changed
I just run `npm install`, the version of posthtml-exporessions changed i got from git log.

thanks  for your reply, I lock the version by delete '^' in package.json

**Comment by cossssmin** [comment]
Ok, closing the issue then.
