### ISSUE TITLE
[HELP]  How can I use maizzle as ES module in TS app?

### ISSUE THREAD

**Issue by CaiyueDamowang** [maizzle/framework#508]
- Maizzle Version: 3.0.0
- Node.js Version: 14.17.2

I try to import @maizzle/framework, but i can't pass the progress of TS compile.

**Comment by CaiyueDamowang** [comment]
When I install @maizzle/framework, I got this and failed.
```shell
npm WARN deprecated debug@4.1.1: Debug versions >=3.2.0 <3.2.7 || >=4 <4.3.1 have a low-severity ReDos regression when used in a Node.js environment. It is recommended you upgrade to 3.2.7 or 4.3.1. (https://github.com/visionmedia/debug/issues/797)
npm ERR! code ETARGET
npm ERR! notarget No matching version found for posthtml-expressions@^1.7.1.
npm ERR! notarget In most cases you or one of your dependencies are requesting
npm ERR! notarget a package version that doesn't exist.
npm ERR! notarget 
npm ERR! notarget It was specified as a dependency of 'posthtml-modules'
npm ERR! notarget 
```

**Comment by cossssmin** [comment]
Sorry, don't have experience with TS, but it doesn't look like it's complaining about Maizzle itself. Have you tried a fresh install? (remove node_modules and the package lock file first)

@Scrum do you have any ideas about this dependency error in `posthtml-modules`? `posthtml-expressions@1.7.1` definitely exists, so not sure what's going on...

**Comment by Scrum** [comment]
@CaiyueDamowang Can you post in github / show code an example that reproduces your error?

**Comment by CaiyueDamowang** [comment]
it seems as private npm registry.
