### ISSUE TITLE
fetch & customised name tag for loop tag is not working

### ISSUE THREAD

**Issue by shivakantshukla55** [maizzle/framework#509]
- Framework Version: v3.6.0
-CLIVersion: v1.4.0
- Node Version: v14.15.0

Hello, Thankyou for the amazing framework. I am very much new to maizzle. I have a issue
1. fetch is not working
2. customised name tag for loop tag is not working

config.js
```
module.exports = {
  build: {
    templates: {
      source: "src/templates",
      destination: {
        path: "build_local",
      },
      assets: {
        source: "src/images",
        destination: "images",
      },
      posthtml: {
        expressions: {
          loopTags: ["for"],
        },
      },
    },
  },
  message: "Hello Template",
  fruits: ["apple", "mango", "orange"],
};
```
test.html(template file)
```
<extends src="src/layouts/main.html">
    <block name="template">
        <h2 class="text-yellow-600">{{page.message}}</h2>
    </block>
    <block name="temp">
        <h3>Hey Shiva</h3>
        <for loop="item, index in page.fruits">
            <p>{{ item }}, my index is {{index}}</p>
        </for>
        <fetch url="https://jsonplaceholder.typicode.com/users">
            <each loop="user in response">
              {{ user.name }}
            </each>
          </fetch>
    </block>
</extends>
```
1. fetch part is not working (i tried both each and for)
2. It is working with each tag but not with for

Please tell me what i am doing wrong, do i need to install any plugin if yes which one?

package.json
```
{
  "private": true,
  "scripts": {
    "local": "maizzle build",
    "production": "maizzle build production",
    "watch": "maizzle serve"
  },
  "dependencies": {
    "@maizzle/framework": "^3.0.0"
  }
}
```

**Comment by cossssmin** [comment]
You are adding the `posthtml` options in the wrong place, that must go under `build` not under `templates`:

https://maizzle.com/docs/templates/#options

**Comment by shivakantshukla55** [comment]
oops! Thanks a lot but fetch is still not working. Any workaround for that?

**Comment by cossssmin** [comment]
Hmm, looks like the [`posthtml-fetch`](https://github.com/posthtml/posthtml-fetch) plugin that provides that functionality is currently broken. 

We'll need to fix that one first, but in the meantime you can use the approach outlined in the WordPress API tutorial:

https://maizzle.com/guides/wordpress-api-posts-email-newsletter/

**Comment by cossssmin** [comment]
Should be fixed now, will publish a patch release shortly. Thanks for reporting it!

**Comment by shivakantshukla55** [comment]
Thankyou very much
