### ISSUE TITLE
baseImageURL not applied to srcset attribute

### ISSUE THREAD

**Issue by ahmed3hamdan** [maizzle/framework#510]
- Maizzle Version: 3.6.0
- Node.js Version: 14.17.3

### Description
baseImageURL is being applied to `src` attribute only. it should be applied to `srcset` attribute as well.

### Example
In `config.production.js`:
```js
module.exports = {
  inlineCSS: true,
  removeUnusedCSS: true,
  baseImageURL: "https://cdn.example.com/",
};
```

My template
```html
<img src="assets/logo.png" srcset="assets/logo.png 1x, assets/logo@2x.png 2x" alt="Logo" />
```

output generated by running `maizzle build production`:
```html
<img src="https://cdn.example.com/assets/logo.png" srcset="assets/logo.png 1x, assets/logo@2x.png 2x" alt="Logo" style="...">
```

**Comment by cossssmin** [comment]
Added support for this in c716483, will be available today in `3.7.0`.

It uses a regex that takes [these image formats](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/img#supported_image_formats) into account, so it's not future-proof.

Eventually we'll need to create a PostHTML plugin that looks at all these sources and applies the prefix.

**Comment by cossssmin** [comment]
Added in `3.7.0`

https://github.com/maizzle/framework/releases/tag/v3.7.0

**Comment by cossssmin** [comment]
`3.7.1` was released to include a fix for the regex used:

https://github.com/maizzle/framework/releases/tag/v3.7.1
