### ISSUE TITLE
Maizzle cli empty output

### ISSUE THREAD

**Issue by SKEPDIMI** [maizzle/framework#524]
- Maizzle Version: 
```
Framework v3.7.1
CLI v1.4.0
```

- Node.js Version: v11.15.0

# Issue Description
When I run `maizzle build` or `maizzle serve`, I expect them to generate a dist/build file, or serve them from localhost. However, the **actual** behaviour is that, upon running, Maizzle immediately stops running and outputs nothing. This happens without any interaction from me. No files are generated, nor is any server spun up. Here is me running Maizzle from scratch and trying to serve/build.

```sh
$ maizzle new
? Project directory name maizzle
? Do you want to use a custom Starter No
? Install NPM dependencies Yes
√ Cloned Git repository
√ Installed NPM dependencies
√ Maizzle project initialized
ℹ Now `cd maizzle` and start building your emails
$ cd maizzle/
$ maizzle serve
$
$ maizzle build
$
# proof no dist/build folder was generated:
$ ls
config.js  config.production.js  LICENSE  node_modules  package.json  package-lock.json  README.md  src  tailwind.config.js
# proof there are templates present:
$ ls src/templates
promotional.html  transactional.html
```

**Comment by cossssmin** [comment]
Your Bode version is not supported, you’ll need to upgrade to a newer one:

https://maizzle.com/docs/installation/#nodejs
