### ISSUE TITLE
Can't install!

### ISSUE THREAD

**Issue by zalexstudios** [maizzle/framework#540]
- Maizzle Version: #.#.#
- Node.js Version: #.#.#

D:\>maizzle new
? Project directory name _email_mazzle_starter
? Do you want to use a custom Starter No
? Install NPM dependencies Yes
- Crafting new Maizzle project in D:\_email_mazzle_starter...(node:9704) UnhandledPromiseRejectionWarning: Error: Command failed with exit code 1: git clone https://github.com/maizzle/maizzle.git _email_mazzle_starter --single-branch
"git" �� ���� ����७��� ��� ���譥�
��������, �ᯮ��塞�� �ணࠬ��� ��� ������ 䠩���.
    at makeError (C:\Users\Alex\AppData\Roaming\npm\node_modules\@maizzle\cli\node_modules\execa\lib\error.js:60:11)
    at handlePromise (C:\Users\Alex\AppData\Roaming\npm\node_modules\@maizzle\cli\node_modules\execa\index.js:118:26)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
(Use `node --trace-warnings ...` to show where the warning was created)
(node:9704) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:9704) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

**Comment by cossssmin** [comment]
Works fine, probably an issue with your Git setup or terminal. Does it always throw that error? (maybe it was a connectivity issue?)

Also what `@maizzle/cli` and Node version are you using?

**Comment by zalexstudios** [comment]
Maizzle Version: @maizzle/cli@1.4.0
Node.js Version: last
Connection normal.
Try install from VS Code and from command line (with admin rule)
See screenshot: https://prnt.sc/1st6idf

**Comment by cossssmin** [comment]
![image](https://user-images.githubusercontent.com/1656595/133924368-0f80a7f9-1456-408d-bc06-af091fef452f.png)

`d:\starter-litmus-master` is not a valid directory name, that will fail even when Git will work for you.

I've already checked on Windows, including in PowerShell, and it works fine.

![image](https://user-images.githubusercontent.com/1656595/133924498-058c0291-a79e-49b8-adeb-9d9bec1574b5.png)

You most likely have a Git problem, check that error message (which we can't see, maybe because it's in cyrillic):

![image](https://user-images.githubusercontent.com/1656595/133924552-265c9d5c-7bdb-4a15-8eab-4d17932d6f5f.png)

**Comment by zalexstudios** [comment]
I don't know! What's a problem...
https://prnt.sc/1stdozu

**Comment by cossssmin** [comment]
That error indicates an issue with using Git to clone a repo on your machine.

Can you `git clone https://github.com/maizzle/maizzle.git` ?

**Comment by zalexstudios** [comment]
Oh! git not installed on system...
https://prnt.sc/1sthoz3
How to get tailwind.css? (npm install -D tailwindcss@latest postcss@latest autoprefixer@latest) correct?

**Comment by cossssmin** [comment]
Please read the installation docs:

https://maizzle.com/docs/installation/

**Comment by zalexstudios** [comment]
Thank you!
