### ISSUE TITLE
I'm having problem when I rename the src folder

### ISSUE THREAD

**Issue by elfpileggi** [maizzle/framework#545]
- Maizzle Version: 3.7.2
- Node.js Version: 14.17.1

When I change the name of the src folder and then I update the references, tailwindcss stops working. Am I forgetting to update somewhere?
https://www.loom.com/share/938b040aa70446b286f74f3b52567af2

**Comment by cossssmin** [comment]
You need to update Tailwind's `purge` key to work with the new directory.

Add it to your `tailwind.config.js`:

```diff
module.exports = {
  mode: 'jit',
+  purge: {
+    content: [
+      'source/**/*.*',
+    ],
+  },
  // ...
}
```

I'll try to make it work somewhat out of the box by having Tailwind purge everything in your `build.templates.source` directory by default, right now it only looks inside `./src`. 

Will couple this with removing the [`purgeCSS` options](https://maizzle.com/docs/code-cleanup/#purgecss) (which you can now pass directly from your Tailwind config) - it'll be a breaking change, so expect it in Maizzle 4.0 together with Tailwind 3.0 support 👍

**Comment by styxlab** [comment]
Ran into exactly the same issue, but good to know there is a workaround.
