### ISSUE TITLE
baseImageURL is appended when src is not an image path

### ISSUE THREAD

**Issue by sherifsaleh** [maizzle/framework#546]
- Node.js Version: v14.15.3
- @maizzle/cli:  "@maizzle/cli": "^1.4.0",
- @maizzle/framework: "^3.7.2",
- fs-extra: "^10.0.0",

```
// config.production. 
npm run production
```

The base URL gets injected after Elixir variables. 

`<%= @artist_image_path %>https://domain.com/imgfolder/
`

Instead of the beginning 

`https://domain.com/imgfolder/<%= @artist_image_path %>
`

**Comment by cossssmin** [comment]
The reason it fails is the regex we use for prepending the URL. We should probably replace the current regex-based solution with a PostHTML plugin that prepends the `baseImageURL` in all possible sources.

**Comment by cossssmin** [comment]
Should be fixed in `v4.0.0-alpha.1`, feel free to reopen if it isn't 👍
