### ISSUE TITLE
Calling an asynchronous function in config.js throws an error

### ISSUE THREAD

**Issue by q-state** [maizzle/framework#549]
- Maizzle Version: 3.7.2
- Node.js Version: 14.16.1

I'm attempting to make an async request as per the [Functions](https://maizzle.com/docs/functions/) example but I'm getting the error:

```
Building emails...(node:34995) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'source' of undefined
    at /Projects/urt-maizzle/node_modules/@maizzle/framework/src/generators/output/to-disk.js:40:28
```

```
const axios = require("axios");

const articles = await axios.get("http://localhost:8082/data/latest.json");

module.exports = {
    articles,

    build: {
        templates: {
            source: 'src/templates',
            destination: {
                path: 'build_local',
            },
            assets: {
                source: 'src/images',
                destination: 'images',
            },
        },
    },
}
```

Hopefully I'm missing something obvious, but any help appreciated!

**Comment by cossssmin** [comment]
I think that example is wrong in the docs, see how to do it in the `beforeCreate` event instead:

https://github.com/maizzle/example-wordpress/blob/master/config.js

**Comment by cossssmin** [comment]
Added a better explanation in maizzle/docs@2d9bd9c

Updated docs: https://maizzle.com/docs/functions/
