### ISSUE TITLE
Feature Request: Nunjucks configuration

### ISSUE THREAD

**Issue by genu** [maizzle/framework#55]
Would you accept a PR that gives more control over Nunjucks config?

For example, Nunjucks has some builtin [filters](https://mozilla.github.io/nunjucks/templating.html#builtin-filters) but it also allows to add custom filters. So, if I have an email template that is for an invoice, I'd like to add a `currency` filter, which is implemented like:

```js
var env = new nunjucks.Environment();

env.addFilter('currency', function(str, count) {
    // return currency formatted currency
});
```

This would require maizzle to allow configuring the `nunjucks.Environment()` instance, which currently it does not.

One option, that is, perhaps, the least intrusive is to add a layer of lifecycle hooks to the `Maizzle.render()` function.

So it would be something like:
```js
Maizzle.render( str, {
   beforeRender: (config, nunjucksEnv) => {
       // gets called before nunjucks renders the template
   },
})
```

Any thoughts?

**Comment by cossssmin** [comment]
Oh, I would love to have something like that in Maizzle! Lifecycle hooks would be great, as not only are they less intrusive, but they give the opportunity to do other things too (like maybe altering the config... and even templates?).

**Comment by cossssmin** [comment]
Update: https://github.com/maizzle/framework/commit/7a5115744a4498723ea71fea1d4cc7c2e7a4e8c2 adds some initial lifecycle hooks, including a `beforeRender` one. 

Tested out with a Nunjucks filter and it works:

```js
const template = `<div>{{ 'Using Maizzle on the server' | shorten(15) }}</div>`

Maizzle.render(template, {
  // ... ,
  beforeRender(nunjucks, config) {
    nunjucks.addFilter('shorten', function(str, count) {
      return str.slice(0, count || 5);
    })
  },
})

// Using Maizzle o
```

You should now be able to add filters, extensions, and globals to Nunjucks.

And you can also use async/await:

```js
const axios = require('axios')

Maizzle.render(`---
  title: Using an async hook to further modify the config
  ---
  {% if page.preheader %}
    <div class="hidden text-0 leading-0">{{ page.preheader | shorten(20) }}</div>
  {% endif %}`, 
  {
    // ... ,
    async afterConfig(config) {
      const preheader = await axios('https://baconipsum.com/api/?type=all-meat&sentences=1&start-with-lorem=1')
      config.preheader = preheader.data[0]
    },
  }
)

// <div style="display: none; line-height: 0; font-size: 0;">Bacon ipsum dolor am</div>
```

Will publish a release soon...

**Comment by cossssmin** [comment]
Added in #71 - feel free to reopen if you spot any issues.

**Comment by genu** [comment]
Thanks, that looks good!

**Comment by genu** [comment]
Do we need to add this to the docs? I can work that PR if its not already in the works.

**Comment by cossssmin** [comment]
Working on docs right now, don't worry 👍
