### ISSUE TITLE
Double escaping in base layout getting evaluated

### ISSUE THREAD

**Issue by jensenbox** [maizzle/framework#571]
- Maizzle Version: 3.7.2
- Node.js Version: 16.10.0

I am successfully using double escaping `@@` in derived templates but whenever I use them in the base layout, it is getting evaluated to `undefined`

Of note, using `<raw>{{ thisisatest }}</raw>` also is getting evaluated in the base layout.

The steps to reproduce are quite easy:

1. Craft a template that uses a layout
2. In the layout, add `@@{{ testing}}`
3. build

You will see that where the double escaping occurred it will show a plain `undefined`

**Comment by jensenbox** [comment]
I went ahead and recorded an asciinema of the behavior from a vanilla install: https://asciinema.org/a/451614

**Comment by cossssmin** [comment]
Hey, sorry for the late reply and thanks for providing that asciinema.

It should work with `@@@{{ test }}` - I know it's weird, but it's needed because of how the layout is parsed with `posthtml-expressions`.

**Comment by jensenbox** [comment]
I will give it a shot today and report back.

Do I need to always use the triple or only in certain contexts? IOW, does
the triple replace the double or do we use each under different situations?

Not gunna lie, it is a bit weird 😂
