### ISSUE TITLE
<raw> or @ in layout/components

### ISSUE THREAD

**Issue by TomDeSmet** [maizzle/framework#582]
Framework v3.7.2
CLI v1.4.0
Node 12.x

Is it correct that `<raw>` and `@` do not work in layouts? They seem to work just fine in normal templates that don't get extended.
It also seems to error in components when I use `@@` or a combination of `<raw>` and `@`.

**Comment by arvindell** [comment]
I'm seeing this behavior too. Double braces inside `<raw>` are evaluated when they are not a `template/`

**Comment by cossssmin** [comment]
Hey, does this work for you?

https://github.com/maizzle/framework/issues/571#issuecomment-991649131
