### ISSUE TITLE
render super slow in production

### ISSUE THREAD

**Issue by klaaz0r** [maizzle/framework#585]
I have a weird problem running Maizzle in production,  locally Maizzle.render is pretty fast, it just takes 500ms to render a complete email. But in production suddenly it takes way longer and the process is even completely blocking the api

```
 inlineCSS: true,
 removeUnusedCSS: true,
 minify: false,

// tailwind.config 
  mode: "jit",
  purge: undefined,
```

Note: I tried without jit and minify true but nothing seems to impact the performance in production

- Maizzle Version: 3.7.2
- Node.js Version: 17.3.0

**Comment by cossssmin** [comment]
Can you please provide access to a repo that reproduces the issue? Hard to tell where it's coming from like that.

**Comment by cossssmin** [comment]
Just noticed you had `purge: undefined` which might have been causing it.

`v4.0.0-alpha.1` was just released, highly encourage you to test it out as it should be even faster - just mind the Tailwind configuration.
