### ISSUE TITLE
Component not consistently compiling.

### ISSUE THREAD

**Issue by TylerAPfledderer** [maizzle/framework#593]
Hello!

I am doing my first project with Maizzle where I am recreating a CodePen Spark Newsletter (the January 2022 one to be specific). 

Please see my current repo: https://github.com/TylerAPfledderer/codepen-newsletter-remake.git

I am currently experiencing an issue with the `articleItem` component whereby it does not always compile on save when I am running `maizzle watch`. 

In other words:
- Sometimes, no instance of the component compiles, and you see the `component` templates in the compiled HTML.
- Sometimes, only some of the instances compile.

I appreciate the additional pairs of eyes to verify that the implementation is on the right track, and if there is an explanation with this issue.

- Maizzle Version: 3.7.2
- Node.js Version: 14.15.1

Thank you!

**Comment by cossssmin** [comment]
Sounds like it's related to #369.

**Comment by TylerAPfledderer** [comment]
Hi @cossssmin!

Thank you for the reply. I will take a look at the issue you shared with me when I am able to today to confirm that it's related.

**Comment by TylerAPfledderer** [comment]
@cossssmin 

https://github.com/maizzle/framework/issues/369#issuecomment-726224861
> Hmm, actually I think this might be an issue with using `locals` when nesting components - modified the `posthtml-modules` test and I got it failing. Looks like nested modules fail to render when `locals` are used on their parent module.
> 
> Test by removing the parent `locals`:
> 
> ```diff
> <component
>   src="src/components/row.html"
> -  locals='{ "divider": "grey", "padTop": 32, "padBottom": 32 }'
> >
> ```
> 
> Will open an issue with the team and we can take it from there, thanks for spotting it.

I tried this, and it still will not compile.

What the component looks like when failed to compile to `build_local`:
```html
<component src="articleItem.html" locals='{"articleImage": "https://production-codepen-email-assets.s3-us-west-2.amazonaws.com/production/iKMZpOIbQ16fUtCBJtF1_DODX3915-600x600-A.jpg", "articleTag": "sponsor", "articleTitle": "DigitalOcean App Platform"}'>
  DigitalOcean App Platform is a Platform as a Service
  solution that helps you build modern, cloud-native apps
  for a lot less money. We’ll handle the infrastructure, app
  runtimes and dependencies, so that you can push code to
  production in just a few clicks.
</component>
```

And this is the component code:
```html
<!-- articleItem.html -->
<td>
  <table>
    <tr>
      <td class="p-12 bg-codepen-500 rounded">
        <table>
          <tr>
            <td>
              <img src="{{ articleImage }}" alt="" />
            </td>
          </tr>
          <tr>
            <td>
              <if condition="articleTag === 'sponsor'">
                <span
                  class="block font-body tracking-[2px] mt-12 text-xs uppercase leading-[1] text-yellow-300"
                >
                  {{ articleTag }}
                </span>
              </if>
              <else>
                <span
                  class="block font-thin font-body tracking-[2px] mt-12 text-xs uppercase leading-[1]"
                >
                  {{ articleTag }}
                </span>
              </else>
              <h2 class="font-heading text-lg text-link mt-4 mb-8">
                {{articleTitle}}
              </h2>
              <p class="block-text text-sm mb-0">
                <content></content>
              </p>
            </td>
          </tr>
        </table>
      </td>
    </tr>
    <!-- Separator between items in a single column -->
    <tr>
      <td role="separator" class="leading-48">&nbsp;</td>
    </tr>
  </table>
</td>
```

**Comment by TylerAPfledderer** [comment]
@cossssmin 

So the issue appears to come from the `sectionContainer` component, which is a parent of the `table` that is housing the `articleItem` components.

But my issue seems to be different than what is discussed in [#369](https://github.com/maizzle/framework/issues/369), as the `sectionContainer` is primitive and does not use `locals`:

```html
<td class="px-24 sm:px-16">
  <content></content>
</td>
```

But the `articleItem` component does use `locals`.

The best solution at this point is to not import the contents of the `sectionContainer` component, and hard code each planned instance in the template.
