### ISSUE TITLE
Rename output files but still render them

### ISSUE THREAD

**Issue by dewey** [maizzle/framework#595]
Hey—

Thanks for Maizzle, it works really well and makes the task of HTML mails massively less annoying that it usually would be. I have a more general question but I'm unsure if that's the responsibility of the framework or if it's better to write some kind of wrapper, so if it's not feel free to close this.

I'm using Maizzle to generate mail views that I'm using in Rails, is there a way to define that the output name of a file is a specific name but still just render it as HTML in the `maizzle serve` pipeline?

For example. I'm building a mail view in Maizzle that has Rails' ERB tags in there `<%= something %>. I don't mind that these are not rendered correctly but it would be nice if I could basically set the target for a view in Maizzle to be the app/view/mailers/myemail.hmtl.erb file in Rails so it would immediately preview / can be sent as a test mail in Rails too.

Any hints on what's the best way to integrate Maizzle with Rails in this case?

Thanks!

**Comment by cossssmin** [comment]
Hi there, thanks!

Check out the `build.templates` config, you can specify a custom destination path and what file names to output:

https://maizzle.com/docs/build-config/#templates

**Comment by dewey** [comment]
Oh that looks promising. I missed that section in the docs. I'll give it a shot and report back later today. Thanks!

**Comment by cossssmin** [comment]
Feel free to reopen if this is still an issue for you :)
