### ISSUE TITLE
Best practices for generating emails with non-generic variables?

### ISSUE THREAD

**Issue by jebax** [maizzle/framework#596]
Hi there,

Bit more of a question rather than an issue, although I think it would be great if the docs included a guide for this use case, as I can imagine it's a very popular one.

Let's say we'd like to generate a confirmation email when a user buys something, and we want that email to include the user's name, maybe fetched from a database. What would be the best way(s) of handling this with maizzle?

As far as I can tell from the docs, the only way to do this would be to use `Maizzle.render()`, defining a custom `beforeRender()` function and setting e.g. `page.user = { name: 'Foo' }` in there. Am I missing something, or is this the only way?

Thanks! :)

**Comment by cossssmin** [comment]
Hey, yeah that's how you'd do it - fetch data in `beforeRender()` (if it changes for each template) or in `beforeCreate()` (if you only need to get it once), set it in the config, and finally use it off the `page` object. Also check out the [RSS to email guide](https://maizzle.com/guides/rss-feed-to-email-newsletter/) in case you haven't 👍

**Comment by jebax** [comment]
thanks @cossssmin :)
