### ISSUE TITLE
Styles don't work on Windows 11

### ISSUE THREAD

**Issue by PostmanZero** [maizzle/framework#602]
- Maizzle Version: 3.7.2
- Node.js Version: 16.13.2

Hey, on windows 11 after using _maizzle serve_ in build local the HTML files don't have styles. Everything works on macOS.
**Below is the log with npm audit:**
```

# npm audit report

postcss  <8.2.13
Severity: moderate
Regular Expression Denial of Service in postcss - https://github.com/advisories/GHSA-566m-qj78-rww5
fix available via `npm audit fix --force`
Will install @maizzle/framework@0.9.1, which is a breaking change
node_modules/posthtml-postcss-merge-longhand/node_modules/postcss-merge-longhand/node_modules/postcss
node_modules/posthtml-postcss-merge-longhand/node_modules/stylehacks/node_modules/postcss
  postcss-merge-longhand  <=4.0.11
  Depends on vulnerable versions of postcss
  Depends on vulnerable versions of stylehacks
  node_modules/posthtml-postcss-merge-longhand/node_modules/postcss-merge-longhand
    posthtml-postcss-merge-longhand  *
    Depends on vulnerable versions of postcss-merge-longhand
    node_modules/posthtml-postcss-merge-longhand
      @maizzle/framework  >=1.0.0
      Depends on vulnerable versions of posthtml-postcss-merge-longhand
      node_modules/@maizzle/framework
  stylehacks  <=4.0.3
  Depends on vulnerable versions of postcss
  node_modules/posthtml-postcss-merge-longhand/node_modules/stylehacks

5 moderate severity vulnerabilities

```

**Comment by cossssmin** [comment]
I'm on Windows 10 and it works perfectly fine, could it be because something you've enabled/disabled on your machine? What NPM version are you using?

**Comment by PostmanZero** [comment]
I just don't know what could be turned off.
I'm using npm version 8.4.0. I have absolutely no idea how to solve this problem. I tried reinstalling node but it doesn't help.

**Comment by cossssmin** [comment]
> Will install @maizzle/framework@0.9.1, which is a breaking change

That doesn't sound right either. Tried removing `node_modules` and `package-lock.json`, and reinstalling dependencies?

**Comment by PostmanZero** [comment]
Yes, I even deleted the entire node and reinstalled. I think it's something from postcss, but I don't know what.

**Comment by cossssmin** [comment]
Hmm, I thought `postcss-merge-longhand` that is used in `posthtml-postcss-merge-longhand` is outdated and that might be triggering it, but in reality it's using `postcss^8.2.15` (see its deps [here](https://github.com/cssnano/cssnano/blob/master/packages/postcss-merge-longhand/package.json)).

The other culprit in that report is `stylehacks`, which also uses `postcss^8.2.15` ([source](https://github.com/cssnano/cssnano/blob/master/packages/stylehacks/package.json)).

I'm still on NPM 7 so I wonder if it's... stricter? 🤷‍♂️ 

Will update to both Windows 11 and NPM 8 these days and check, wanted to update soon anyway :)

**Comment by cossssmin** [comment]
Updated to latest NPM, still works fine. Will report back after upgrading to Windows 11.

**Comment by PostmanZero** [comment]
Thanks for your help, I am waiting for information when you update Windows.

**Comment by cossssmin** [comment]
Feel free to reopen if you can provide a repo that reproduces the issue ✌️
