### ISSUE TITLE
Node `render` not picking up maizzle config

### ISSUE THREAD

**Issue by jebax** [maizzle/framework#603]
- Maizzle Version: 3.7.2
- Node.js Version: 14.7.3

Hi there,

I'm trying to build my templates at runtime with node. I have a function at `src/api/routes/foo/index.js` that uses `Maizzle.render()` with a template. `render()` is picking up my tailwind config at `tailwind.config.js` (including custom colors etc.), but it isn't picking up my maizzle config at `config.js` (or ideally `config.production.js`). I'm having to manually import the right maizzle config depending on the node environment, and pass it as the `maizzle` option in `render()`. 

Surely my config should be picked up automatically? How come the tailwind config is picked up but not the maizzle config? Apologies if i'm missing anything obvious. Thanks!

**Comment by cossssmin** [comment]
Your Maizzle config is not automatically picked up, you need to specify it:

https://maizzle.com/docs/nodejs/

**Comment by jebax** [comment]
Ok sure. If the tailwind config is picked up, wouldn't it make sense if the maizzle config was picked up as well? 🤔

Just a bit annoying that this behaviour differs from the CLI behaviour. 

So i'm correct in thinking i need to do something like:
```js
import maizzleLocalConfig from '/config.js'
import maizzleProductionConfig from '/config.production.js'

const template = '<html></html>'
const { html } = await Maizzle.render(template, {
  maizzle: process.env.NODE_ENV === 'development' ? maizzleLocalConfig : maizzleProductionConfig
})
```
?

**Comment by cossssmin** [comment]
The Tailwind config is actually picked up automatically by Tailwind itself, but yes, it would be a nice convenience to pick up the Maizzle config as well 👍

**Comment by jebax** [comment]
> The Tailwind config is actually picked up automatically by Tailwind itself, but yes, it would be a nice convenience to pick up the Maizzle config as well 👍

Ah I see. Well yeah that would be handy! Thanks for your quick responses.

**Comment by cossssmin** [comment]
OK, I think I may have it working here:

https://github.com/maizzle/framework/pull/613

Will need to test some more to make sure, but it should work.

**Comment by jebax** [comment]
> OK, I think I may have it working in #613
> 
> Will need to test some more to make sure, but it should work.

amazing thanks!!

**Comment by cossssmin** [comment]
OK, so I tested some more and looks like it's working as expected.

A few notes (will add to the release notes and docs once updated):

1. Not specifying any `env` in will fall back to the `local` env and will try to use `config.js` at the current location; not having even a `config.js` at the current location will still set the `env` to `local`, and all Transformers and such will fall back to their default behavior based on that `env`.
1. Specifying an `env` for which there is no equivalent config file (i.e. `env: 'staging'` but there is no `config.staging.js`), will throw and exit the script.
1. Loading of config(s) (including Tailwind's) is done relative to the location you're executing the command from.
  
    So if you're using `render()` in, say, `render.js` at the root of a project (where you have config.production.js) and try to call it when you're inside `src` by doing `node ../render.js`, it'll exit the script because the config.production.js file can't be found. This also applies to Tailwind, so if you're not specifying a Maizzle env, it'll fall back to `local` and will work, just that it'll use the default Tailwind config (the one for web, with rem units etc), because it can't find it at the location you're running the script from. Hope that makes sense :)
