### ISSUE TITLE
Integration with existing framework, existing TailwindCSS setup

### ISSUE THREAD

**Issue by SHxKM** [maizzle/framework#62]
Hi,

First-off, this looks like the dream setup for me, as someone who doesn't know much about e-mail design and just loves working with Tailwind CSS. Thanks for your effort!

I have a few questions/concerns that some may be able to help with here: I want to integrate Maizzle in my Django web-app. This comes with two concerns for me:

1. Django uses Jinja, which Nunjucks is a superset of. Somewhat like we do with Nunjucks, in Django we pass context to the email template (an `.html` file), and this context is used to populate variables with values. But in `build production` Maizzle does the same to `{{ variable}}`s. What's my best option here? Right now I'm thinking of this workflow which seems dirty yet simple:

    1. Use `{% raw %}` tags to escape variables that should be populated by Django.
    2. When happy with the result, copy the production file contents to my Django mail template.

The problem with this is I'm never able to *truly* test the final outcome (not that this is possible with my current setup). For variables like `username` this isn't so bad, but what if I want to pass the `src` value of an `img`, or an array of `src`s like such?

2. The project already integrates Tailwind CSS. As I understand, Maizzle uses a "custom flavor" of Tailwind, so the two config files would be incompatible in my case. _I guess_ this can be solved by simply renaming the config file and have Maizzle look for the renamed config? or is this not supported? 

Any pointers are much appreciated!

**Comment by cossssmin** [comment]
Hi there, thanks for the kind words! :)

1. Your best bet is to use `{% raw %}` tags, unless you can somehow get the data from Django to populate the variables for Maizzle to use. If you _can_ do that, you could take advantage of build environments in Maizzle and only do it in development for previewing purposes, i.e. when running `maizzle build` or `maizzle serve` (both of which use the settings in `config.js`).

2. Yes, Maizzle includes a custom `tailwnd.config.js` that is optimized for HTML email development, but you can [change the path to your Tailwind config file](https://maizzle.com/docs/build-paths/#tailwind). Simply name it differently if you want to keep Maizzle's config for Tailwind, or you can use the config you're already using in your project (though I would really advise against using the  default Tailwind config for HTML emails).

Hope this helps!

**Comment by SHxKM** [comment]
@cossssmin - Thanks for taking the time to answer. 

1 still troubles me. Even if I'm able to populate variables in development for preview-purposes, I still have to maintain two files, right? one which wraps variables with `{% raw %}` tags, and one which doesn't. Am I missing something still?

**Comment by SHxKM** [comment]
Or maybe I can use some kind of env...?


```jinja
{% if build.production %}
    {% raw %}
        {{ username }}
    {% endraw %}
{% else %}
     {{ username }}
{% endif %}
```

The preview will use the interpolated values, and production files will be output with the raw values. Still not sure I'm thinking about this the right way...

**Comment by SHxKM** [comment]
I think the only way to make this work for me and for others who need to keep variables I escaped *and still be able to preview* for their workflow is to somehow allow for dynamically plucking out the the interpolation out of the build process. 

The way I see it: 

In templates: 

Define variables regularly, no raw tags. 

In dev: 

Build just renders said templates.

In production:

Like in dev, but leave nunjucks tags alone.

**Comment by cossssmin** [comment]
You could use the environment configs in Maizzle, and populate a variable in only one of them. 

So you could do this in `config.js`:

```js
module.exports = {
  // ...
  user: {}
}
```

`user` here can be an immediately invoked function that returns an object:

```js
module.exports = {
  user: function() {
    // return an object here, maybe fetch data from somewhere?
  }()
}
```

Since we place this only in `config.js`, it will only be available when doing `maizzle build` (no env specified) or `maizzle serve`. 

Then in your template you can use Nunjucks logic:

```nunjucks
{{ user.name or '{{ username }}' }}
```

So when you build for production, the string `{{ username }}` would be output. 

Haven’t tested yet (on my phone), but it should work, as far as Nunjucks is concerned that fallback is just a string, it shouldn’t try to parse it. 

Do let me know how it goes, I’ll give it a try Monday latest.

**Comment by SHxKM** [comment]
@cossssmin - this sounds like a plan. I wonder how can I deal with `for` loops this way but it should be better than what I’m trying now. Will try later tonight and report back. Appreciate the help!

**Comment by SHxKM** [comment]
This isn't really working.

`config.js`:

```python
 username: function () {
    return "Jason"
  }(),
```

`newsletter.njk`:

```nunjucks
<b>Hey {{ username or '{{ username }}' }}</b>
```

`npm run build production` shows `Hey Jason` in the final HTML file. (I do have a `config.production.js` file).

Is the trick here to call the variables differently? I wouldn't have thought it necessary.

**Comment by SHxKM** [comment]
OK, found my clue in the excellent docs:

> config.production.js will be merged _on top of_ config.js, so you only need to specify the config values that you are changing for the production build.

So `config.production.js` must also specify:

```js
username: null,
```

**Comment by SHxKM** [comment]
@cossssmin Are you open to the idea of offering an option like `nunjucks_render` in the config files? An on-by-default boolean that dictates whether nunjucks tags are parsed at all. This will make things so much easier and extensible for use-cases like mine, which I think as maizzlejs is discovered will not be rare at all.

**Comment by cossssmin** [comment]
Unfortunately something like that wouldn't be possible, Nunjucks must be rendered in order for Layouts and Templates to work. It's also needed to inject the compiled Tailwind CSS, as well as all the options from the config (like `title` or `doctype`).

For Nunjucks if/else I think the only solution is to use `{% raw %}` blocks.

**Comment by SHxKM** [comment]
Ahh, that's too bad. It's pretty much impossible to maintain two different versions.

I think what I will try next is to use regex to surround these Nunjucks blocks with `{% raw %}` blocks, and have production refer to a dynamically generated file.

**Comment by cossssmin** [comment]
The only issue I can foresee with it is that `{{ item_count }}` could be `undefined`? Maybe fallback to an empty string or something?

**Comment by SHxKM** [comment]
Thanks for your guidance @cossssmin.
