### ISSUE TITLE
Using tailwind syntax inside `<style postcss>` tag

### ISSUE THREAD

**Issue by jebax** [maizzle/framework#629]
- Maizzle Version: 3.7.2
- Node.js Version: 14.7.3

Hi,

I'm trying to include a gmail email client hack in my templates. I've added a `<style data-embed />` tag in the `head` in my layout, and I've added the related class to my `whitelist` in `removeUnusedCSS`.

The problem is I'd like to use tailwind syntax inside my CSS rule, so for example `@apply bg-red;` instead of `background-color: #{hex for my theme's red color};`. When I render the template with `Maizzle.render()`, it doesn't compile tailwind syntax to normal CSS - I just get `@apply bg-red;` inside my generated HTML, which obviously does nothing.

You used `@apply` in [this example](https://maizzle.com/docs/tailwindcss/#prevent-inlining), so I'm a bit confused why it isn't working for me.

Thanks!

**Comment by cossssmin** [comment]
Sounds like you're missing the `postcss` attribute on the style tag.

**Comment by jebax** [comment]
Hmm I tried that before - when using `postcss`, it seems to totally remove the CSS inside that tag from the outputted HTML, and also seems to include a load of other CSS that wouldn't be included otherwise?

**Comment by jebax** [comment]
FYI this happens even with the maizzle starter project. If you change a `<style data-embed />` tag to `<style postcss data-embed />`, then run `yarn run local`, you get a load more CSS in the outputted HTML, and the CSS inside the postcss tag is nowhere to be seen.

**Comment by jebax** [comment]
No worries thanks for sorting!

**Comment by cossssmin** [comment]
Published [v3.7.3](https://github.com/maizzle/framework/releases/tag/v3.7.3), should be fixed now 👍
