### ISSUE TITLE
Using Blank Template does not inline the css

### ISSUE THREAD

**Issue by roarkmccolgan** [maizzle/framework#63]
- Maizzle Version: 0.2.0
- Node.js Version: 6.9.0

### Description:
I'm using maizzle to build blade files in my laravel project, in an attempt to generate partial files that will be included at run time.
To do so I created a blank template that just has a block template in it:
```
// /layouts/blank.njk
{% block template %}{% endblock %}
```
and for my partial:
```
---
layout: src/layouts/blank.njk
---
{% block template %}
		<tr>
			<td class="px-4">
				<p class="font-bold">{% raw %}{{ $title }}{% endraw %}</p>
			</td>
		</tr>
{% endblock %}
```
### What I hoped would happen
I would expect Maizzle to process the file, convert classes to inline the styles etc
### What happens
The output file still is minimized but no processing of the css (inlining is done)
```
<tr><td class="px-4"><p class="font-bold">{{ $title }}</p></td></tr>
```
### Steps To Reproduce:
Described above

Any help with this would be greatly appreciated and thanks for a great tool!

**Comment by roarkmccolgan** [comment]
Ok so further testing got me to this point in my blank template:
```
{% if css %}<style>{{ css }}</style>{% endif %}
{% block template %}{% endblock %}
```
just including the css tag will still inline the styles but it also generates an unwanted style tag above the output code:
```
<style>@media screen{img{max-width:100%}}</style><tr><td class="px-4" style="padding-left:4px;padding-right:4px"><p class="font-bold" style="font-weight:700">{{ $title }}</p></td></tr>
```
Is it possible to force the compilation of classes without including the css tag {{ css }}

**Comment by cossssmin** [comment]
The way this works in Maizzle is that compiled Tailwind CSS is placed inside a `<style>` tag, and this is inlined on the HTML by the Juice library. It's not possible to do this without that style tag. Here's a detailed overview of the [build process in Maizzle](https://maizzle.com/docs/build-process/).

The unwanted tag you mentioned is there for responsive images, but if you want you can easily remove it from `src/assets/css/custom/reset.css` in your project.

**Comment by roarkmccolgan** [comment]
Great answer, thank you very much!
