### ISSUE TITLE
Error: could not load config.production.js

### ISSUE THREAD

**Issue by yellow1912** [maizzle/framework#633]
- Maizzle Version: 4.0.0-alpha.2
- Node.js Version: v14.17.0

I'm trying out v4 (for tailwind 3 support)

My node code to run maizzle look like this:

```
tailwind.config.purge = {
  enabled: true,
  content: [input],
};

var maizzleConfig = {
  maizzle: {
    env: 'production',
    inlineCSS: true,
    removeUnusedCSS: true,
    build: {
      templates: {
        destination: {
          path: 'build_production',
        },
      },
    },
  },
  tailwind: tailwind
}

async function render(args, content, maizzleConfig) {
  try {
    const {html} = await Maizzle.render(content, maizzleConfig);

    if (args.hasOwnProperty('out-file')) {
      try {
        fs.writeFileSync(args['out-file'], html);
      } catch (err) {
        console.error('There was an error while trying to write content to ' + args['out-file']);
        console.error(err);
        process.exit(1);
      }

    } else {
      console.log(html);
    }
  } catch(err) {
    console.error(err); // TypeError: failed to fetch
  }
}

render(args, content, maizzleConfig);
```

If I create an empty file then it seems to fix the error.

**Comment by cossssmin** [comment]
I'll look into it next week, but for now I can say the Tailwind config is wrong, for Tailwind CSS 3 the purging config is under the `content` key. In fact, it should actually just work when using the `render` method, you shouldn't need to define anything for Tailwind.

Also the `build` key in the Maizzle config isn't needed here, since the method returns the HTML string and it doesn't write out to a directory on its own.

Again, will have a look next week. And sorry for the lack of a proper upgrade guide, I just didn't have the time to finish that (working on it).

**Comment by cossssmin** [comment]
What is `[input]`?

**Comment by yellow1912** [comment]
Hello, the input is the path to the html file which looks like this:

https://gist.github.com/yellow1912/678875240f9b6903c9b688e818034229

**Comment by yellow1912** [comment]
I think I pinpointed the issue, in the tailwind.css I have:

https://maizzle.com/docs/nodejs/

`var tailwind = {config: {}, css: '@tailwind base; @tailwind components; @tailwind utilities;'};`

If I remove the @tailwind base then it will work.

**Comment by cossssmin** [comment]
Yeah, you shouldn't include `@tailwind base` anyway, since that is tailored to web development, it's not really suitable for email.

I'll have a look at it these days to cofirm, thanks 👍

**Comment by yellow1912** [comment]
I think this is a change in either maizzle 4 or tailwind 3 because base did not cause any issue in the previous version.

**Comment by cossssmin** [comment]
> Hello, the input is the path to the html file which looks like this:
> 
> [gist.github.com/yellow1912/678875240f9b6903c9b688e818034229](https://gist.github.com/yellow1912/678875240f9b6903c9b688e818034229)_ (too large to embed)_

Your HTML file to be rendered does not make use of the `{{{ page.css }}}` variable inside a `<style>` tag, so Maizzle doesn't output the compiled Tailwind CSS anywhere.

https://maizzle.com/docs/tailwindcss/

**Comment by cossssmin** [comment]
Created a test repo for this, check it out:

https://github.com/cossssmin/maizzle-node

The reason you were initially getting the error about it not being able to load the config was because of the `env` specified, but it does work fine without adding one 👍

**Comment by yellow1912** [comment]
> Created a test repo for this, check it out:
> 
> https://github.com/cossssmin/maizzle-node
> 
> The reason you were initially getting the error about it not being able to load the config was because of the `env` specified, but it does work fine without adding one 👍

Thank you. Can you try to use the following tailwind config inside maizzle to see if it works?

`var tailwind = {config: {}, css: '@tailwind base; @tailwind components; @tailwind utilities;'};
`

**Comment by yellow1912** [comment]
I see, I think the problem is that I have some custom applies. Can I just use the custom applies like this:

`var tailwind = {config: {}, css: '/*some custom applies code here*/'};
`
