### ISSUE TITLE
Move BrowserSync to dev-dependencies

### ISSUE THREAD

**Issue by anonrig** [maizzle/framework#635]
Since, browsersync only works on `watch` mode, I suggest moving it to dev-dependencies to reduce the size of the package for production environments.

**Comment by cossssmin** [comment]
BrowserSync is a production dependency in Maizzle, `maizzle serve` (or `npm run watch` in the Starter) cannot work with BrowserSync installed as a dev-dependency, because it won't find it. 

You might be confusing local email development with developing the Maizzle framework itself :)
