### ISSUE TITLE
PostHTML expressions escaping not working in layouts

### ISSUE THREAD

**Issue by simonc** [maizzle/framework#647]
- Maizzle Version: 3.7.3
- Maizzle CLI: 1.4.0
- Node.js Version: 14.18.1

Hi!

First of all, thank you for Maizzle, it's a great tool that's been life changing for us.

We're building a series of templates we want to use in Sendgrid. Pretty much everything is working well but for one thing.

We adding unsubscribe links at the end of the layout. Sendgrid looks for `{{unsubscribe}}` and `{{unsubscribe_preferences}}` so we used the `@{{ ... }}` syntax documented in posthtml-expressions but for some reason it doesn't seem to work in layouts.

It does work in templates themselves though 🤷 

Is there anything we're doing wrong?

Thanks! ❤️

**Comment by cossssmin** [comment]
Hey thanks! You're not doing anything wrong, this just needs better docs.

Can you have a look at https://github.com/maizzle/framework/issues/571 and let me know if it works for you?

**Comment by simonc** [comment]
Hey @cossssmin 👋 

Replacing `@{{unsubscribe}}` with `@@@{{unsubscribe}}` did work 🙂

Thanks!
