### ISSUE TITLE
Run maizzle producton using a custom configuration file

### ISSUE THREAD

**Issue by mfissehaye** [maizzle/framework#648]
- Maizzle Version: 3.6.3
- Node.js Version: 14.17.1

I want to be able to run maizzle production by providing a custom path to a config file. I think maizzle expects config.js right now. What if I want to load the config from maizzle.config.js because I am integrating maizzle to a bigger framework that uses other config files.

**Comment by cossssmin** [comment]
The CLI tool doesn't currently support passing in custom config file paths. When using the CLI commands such as `maizzle build production`, you need to name your Maizzle config file based on the environment you're building for - in this case, `config.production.js`.

If you want to be able to pass in a custom config, you can do it when using Maizzle programmatically:

https://maizzle.com/docs/nodejs/
