### ISSUE TITLE
PostHTML Expression Delimiter Option Only Applies to Templates, not Layouts

### ISSUE THREAD

**Issue by rmcauley** [maizzle/framework#665]
- Maizzle Version: Framework v3.7.3, CLI v1.4.0
- Node.js Version: 16.5.0

I'm trying to use Maizzle to output templates for an existing Java/Pebble system, similar to https://github.com/maizzle/framework/issues/346.

I wish to change my PostHTML Expressions delimiters in Pebble from `{{` to `[[` as documented on the Maizzle website: https://maizzle.com/docs/templates/#options

This is not currently working consistently between layout and template files, however.

This is my layout:

```
    <div class="border-0 border-solid border-t-2 mt-24 border-brandColor border-b-2">
      <p>Layout square brackets: [[ page.language ]]</p>
      <p>Layout curly braces: {{ page.language }}</p>
      <block name="template"></block>
    </div>
```

This is my template:
```
<extends src="src/layouts/main.html">
  <block name="template">
    <p>Template square brackets: [[ page.language ]]</p>
    <p>Template curly braces: {{ page.language }}</p>
  </block>
</extends>
```

This is my config:
```
module.exports = {
  build: {
    templates: {
      source: 'src/templates',
      destination: {
        path: 'build_local',
      },
      assets: {
        source: 'src/images',
        destination: 'images',
      },
    },
    posthtml: {
      expressions: {
        delimiters: ['[[', ']]'],
        unescapeDelimiters: ['[[[', ']]]'],
      }
    },
  },
}
```

And this is the rendered result:

![image](https://user-images.githubusercontent.com/341137/164745645-fc653402-aa66-454a-8a7e-4c383e74754f.png)

Ideally, I would like to be able to use `{{ }}` freely in Front Matter variables and template HTML with no issues.  It's important to me as well that other templating directives that our existing system uses (e.g. it has loops such as `{% for i in x %} {{ i }} {% endfor %}` can also be put into Maizzle with minimal friction for our existing developers. :)

**Comment by kevin-leeto** [comment]
The problem still persists inside a component. The custom delimiter is not used.

**Comment by kevinpainchaud** [comment]
The problem still persists inside a component. The custom delimiter is not used.

**Comment by cossssmin** [comment]
@kevinpainchaud this was fixed for 4.x, are you configuring components to use custom delimiters as well? If yes, can you please provide a repo that reproduces the issue?

**Comment by kevinpainchaud** [comment]
I specified a custom delimiter such as:

```
module.exports = {
  build: {
    posthtml: {
      expressions: {
        delimiters: ['[[', ']]'],
        unescapeDelimiters: ['[[[', ']]]'],
      }
    },
  },
}
```

It works fine in a layout or in a template.
However, in a component, the delimiter that works remains is this one: "{{ }}".

I will try to provide a repo soon.

**Comment by cossssmin** [comment]
You’ll need to customize it for the components as well:

```
build: {
    components: {
      expressions: {
        // delimiters etc.
      }
    }
  }
  ```

**Comment by kevinpainchaud** [comment]
Indeed, that solved my problem. I was not aware of this option. Thank you! 🙏
