### ISSUE TITLE
Tags adjacent to blocks in layout HTML are not rendered

### ISSUE THREAD

**Issue by rmcauley** [maizzle/framework#669]
- Maizzle Version: Framework v3.7.3, CLI v1.4.0
- Node.js Version: 16.5.0

`layout.html`:

```
<div>
  <block name="content" />
  <span>Hello</span>
</div>
```

`template.html`:

```
<block name="content">Foo</block>
```

The resulting rendered HTML will not have the `span` or even the bareword "Hello" for me.

The workaround for now, which renders as I expected:

```
<div>
  <span><block name="content" /></span>
  <span>Hello</span>
</div>
```

**Comment by cossssmin** [comment]
Using self-closing tags for PostHTML tags like `<block>` or `<component>` is not supported, everything that comes after will not be output as expected.

**Comment by rmcauley** [comment]
Ohhh, thank you, I will add that to our internal documentation to make that clear when using Maizzle!

I took a quick run through of the Maizzle documentation again, and I couldn't find this caveat mentioned.  Maybe mentioning it here might be good? https://maizzle.com/docs/templates/#blocks

I will close out this issue.

**Comment by cossssmin** [comment]
Yeah, it's a PostHTML parser thing, and I totally get how one would assume it works, especially when coming from frameworks like Vue/React. I'll add it to the docs, thanks! :)
