### ISSUE TITLE
how to change port 

### ISSUE THREAD

**Issue by productdevbook** [maizzle/framework#670]
how to change custom maizzle serve port ?

**Comment by productdevbook** [comment]
hmm this problem

```
mail:dev: Make sure to run this command in your Maizzle project root, with dependencies installed.
``` 
iam used monorepo install but dont serve working

**Comment by cossssmin** [comment]
You need to run the command in the project folder, it errors out because it can't find the executable.

Alternatively you may pass the path to the executable:

```
maizzle serve --bin path/to/node_modules/@maizzle/framework/src
```

I think this isn't yet documented, will add it to the list.

**Comment by productdevbook** [comment]
Thank you fixed
