### ISSUE TITLE
1 high severity vulnerability with async package

### ISSUE THREAD

**Issue by rohanharikr** [maizzle/framework#680]
- Maizzle Version: 3.7.3
- Node.js Version: 14.19.1

1 high severity vulnerability:
Path: @maizzle/framework > browser-sync > portscanner > async
More info: https://snyk.io/test/npm/@maizzle/framework/4.0.0-alpha.4

**Comment by cossssmin** [comment]
Need to wait for `browser-sync` to update it:

https://github.com/BrowserSync/browser-sync/issues/1959
