### ISSUE TITLE
Maizzle ignores first Tailwind layer's statement on production build

### ISSUE THREAD

**Issue by rmcauley** [maizzle/framework#681]
- Maizzle Version: 3.7.3
- Node.js Version: 16.5.0

It is easier to see the result than try to describe the bug, oddly.

Step 1: Make a new Maizzle project with `maizzle new` with default starter.

Step 2: Add a component layer with Tailwind:

`src/css/utilities.css`
```css
@layer components {
  .one {
    @apply bg-black;
  }

  .two {
    @apply bg-red-500;
  }
}
```

Step 3: Add two divs with the above classnames to the `transactional.html` template:

```html
<extends src="src/layouts/main.html">
  <block name="template">
    <div class="one">one</div>
    <div class="two">two</div>
```

Step 4: `npm run local && npm run production`

The results as seen in the browser:

Local:
![image](https://user-images.githubusercontent.com/341137/167645787-4e532213-d723-423b-be79-06fd3ab7b5dd.png)

Production:
![image](https://user-images.githubusercontent.com/341137/167645902-c80cb63a-f9eb-46d7-bc83-a3537902479c.png)

Step 5: Swap the order of `.one` and `.two` classes in the Tailwind layer and re-run `npm run production`:

![image](https://user-images.githubusercontent.com/341137/167646158-ba2ab624-6dcc-42de-9513-dfbff1d7d083.png)

Workaround: Don't use multiple layers in Tailwind.

**Comment by cossssmin** [comment]
Hey, thanks for taking the time to report this. You're right, it is an issue in `3.7.3`. Not sure why, might be related to the fallback CSS we provide when compiling Tailwind.

It's fixed in `4.x` though, just tested it with inlining enabled and this is the diff:

```diff
- <div>3.7.3</div>
<div style="background-color: #ef4444;">3.7.3</div>
+ <div style="background-color: #000">4.0.0-alpha.8</div>
<div style="background-color: #ef4444">4.0.0-alpha.8</div>
```
