### ISSUE TITLE
Only the first VML path is prefixed by baseURL

### ISSUE THREAD

**Issue by hteumeuleu** [maizzle/framework#684]
- Maizzle Version: 4.0.0-alpha.8
- Node.js Version: 15.14.0

Hey there! I think I found a bug related to VML images and the use of the `baseURL` config. It looks like under Maizzle 4, only the first VML path is prefixed by baseURL. (I checked and this doesn't seem to appear under Maizzle 3.) Here’s how you can reproduce it:

1. Create a new Maizzle project (`maizzle new`).
2. On the `package.json`, change Maizzle version from `^3.0.0` to `next`.
3. `npm i` to install everything.
4. In `config.js`, add `baseURL: 'https://example.com/foo/'`.
5. In the `src/templates.promotional.html` template, add the following code at the start of the `<block name="template">` block. You can also change the `src:` variable passed to the `vmlbg` component to a local image like `foobarbaz.jpg`.

```html
<!--[if mso]>
<v:image src="foo.jpg" />
<v:image src="bar.jpg" />
<v:image src="baz.jpg" />
<![endif]-->
```

6. Run `maizzle serve` or `maizzle build production`.

## Expected result

Every image in the email should have its path prefixed by `https://example.com/foo/`.

```html
<!--[if mso]>
<v:image src="https://example.com/foo/foo.jpg" />
<v:image src="https://example.com/foo/bar.jpg" />
<v:image src="https://example.com/foo/baz.jpg" />
<![endif]-->
…
<!--[if mso]>
<v:image src="https://example.com/foo/foobarbaz.jpg" xmlns:v="urn:schemas-microsoft-com:vml" style="width:600px;height:400px;" />
…
<![endif]-->
```

## Actual result

Only the very first image within the entire email has its path prefixed by the `baseURL` value.

```html
<!--[if mso]>
<v:image src="https://example.com/foo/foo.jpg" />
<v:image src="bar.jpg" />
<v:image src="baz.jpg" />
<![endif]-->
…
<!--[if mso]>
<v:image src="foobarbaz.jpg" xmlns:v="urn:schemas-microsoft-com:vml" style="width:600px;height:400px;" />
…
<![endif]-->
```

**Comment by hteumeuleu** [comment]
This looks great! There's also a `<v:imagedata>` element in VML, although I've never used it or seen it used in the wild. https://docs.microsoft.com/en-us/windows/win32/vml/msdn-online-vml-imagedata-element

**Comment by cossssmin** [comment]
Thanks for reviewing. And yeah, never seen `<v:imagedata>` actually used either, let's hold off on that for now👍

**Comment by cossssmin** [comment]
Now available in alpha9:

https://github.com/maizzle/framework/releases/tag/v4.0.0-alpha.9
