### ISSUE TITLE
Ability to create custom components as tags

### ISSUE THREAD

**Issue by StErMi** [maizzle/framework#694]
- Maizzle Version: Framework v3.7.3
- Maizzle Version: CLI v1.4.0
- Node.js Version: v16.13.

I didn't see anything specific in the documentation. Would it be possible to create components as tags?

And be able to use those in code like `<button>`

**Comment by cossssmin** [comment]
This is not currently possible. We might explore it in the future through a custom PostHTML plugin, but right now you can't do that, not unless you write your own PostHTML plugin.
