### ISSUE TITLE
transform is not working correctly

### ISSUE THREAD

**Issue by StErMi** [maizzle/framework#697]
Maizzle Version: Framework 4.0.0-alpha.9
Maizzle Version: CLI v1.4.0
Node.js Version: v16.13.

I've defined a new transform in `config.js` like in the docs

I've tried to both define a new function and replace the `uppercase` one but

1) if I replace the uppercase one with a stupid `return "test"` it will still perform the "old" uppercase
2) if I define a new function called `test` and try to use it like in the example, it gets ignored

It seems like the `trasnform` from config is not picked up by the `serve` and it has some pre-defined function like `uppercase`?

**Comment by StErMi** [comment]
I think that I found an issue with `filters` and a specific case (let me know if I need to open a separate issue)

In case where I have

```ts
  filters: {
    applyAFilter: (str) => {
      return str;
    },
  },
```

and the HTML like this

```
---
title: 'Lorem ipsum <span class="text-red-700">dolor</span> sit'
---

<span applyAFilter>{{{page.title}}}</span>

```

I get this error

```
✖ Failed to compile template: test.html
⚠ Cannot set properties of undefined (setting 'content')
✔ Re-built 0 templates in 0.106s
```

In this specific case `str` is not a `string` but `{ tag: 'span', attrs: { class: 'text-red-700' }, content: [ 'dolor' ] }`. What should it return?

**Comment by cossssmin** [comment]
Tags are not yet supported, see the release notes:

https://github.com/maizzle/framework/releases/tag/v4.0.0-alpha.9

**Comment by sgarbesi** [comment]
@cossssmin Nice library, but the docs are stale, and I wasted a lot of time coming to this same conclusion trying to use `transform` when it's been deprecated.

**Comment by cossssmin** [comment]
@sgarbesi both the [release notes](https://github.com/maizzle/framework/releases/tag/v4.0.0#breaking-changes-4.0) here on GitHub and the [upgrade guide](https://maizzle.com/docs/upgrade-guide#update-transform) in the docs site mention this breaking change, you just need to read it 👍

**Comment by sgarbesi** [comment]
I'm a newcomer, not upgrading.

Someone goes to your homepage https://maizzle.com/
They scroll down and see [Transformer](https://maizzle.com/docs/transformers) and click the link.
...

Just trying to be helpful, good luck.

**Comment by cossssmin** [comment]
I'm sorry, maybe I misunderstood, do you mean this link in the "Maizzle Features" section?

<img width="326" alt="image" src="https://user-images.githubusercontent.com/1656595/210774236-36a03c74-2433-46f8-ad0f-96588b024db1.png">

That goes to the correct page, so not sure I understand. Maybe there was some confusion between "Transformers" as a name for a collection of tools vs. "Transform" which was one of the Transformers? (that's one reason we had it renamed to "Filters").

If that's not it either, I'd appreciate your help in clearing any confusion or issue that resulted in a waste of time🙏
