### ISSUE TITLE
global (`page`) or `locals` variables are not passed down correctly if they contain HTML

### ISSUE THREAD

**Issue by StErMi** [maizzle/framework#698]
- Maizzle Version: Framework 4.0.0-alpha.9
- Maizzle Version: CLI v1.4.0
- Node.js Version: v16.13.

Example:

```
---
title: 'Lorem ipsum <span class="text-red-700">dolor</span> sit'
---

<component src="src/components/textbox.html" locals='{"text": "{{page.title}}"}'></component>
```

and the `textbox` is like this:

```
<!-- src/components/textbox.html -->
<table class="w-full sm:w-full border border-solid border-gray-200 rounded-lg">
  <tr>
    <td class="bg-white p-16 rounded-lg">
      <span class="text-base leading-16 text-gray-800 font-normal"
        >{{{text}}}</span
      >
    </td>
  </tr>
</table>
```

the page will be rendered with `undefined` inside the `table`. I `title` is without HTML it works correctly. Is there a way to fix it?

**Comment by cossssmin** [comment]
Expressions aren't supported in the `locals=''` attribute, use attribute locals instead:

```html
<component 
  src="src/components/textbox.html" 
  text="{{{ page.title }}}"
></component>
```

**Comment by StErMi** [comment]
What's the main difference between `locals` and `attribute locals`? really like the `react` like usage :D

**Comment by cossssmin** [comment]
They're just easier to write and will support expressions, that's all :)

See here: https://github.com/posthtml/posthtml-modules#attributeaslocals-1

P.S.: don't think of components in Maizzle as equivalent to those in frontend frameworks; they're much simpler and limited in scope.
