### ISSUE TITLE
Unable to run package.json scripts using yarn

### ISSUE THREAD

**Issue by jebax** [maizzle/framework#703]
- Maizzle Version: 4.0.0
- Node.js Version: 16.5.3

Hi,

As of maizzle 4.0.0 there's a problem executing package.json scripts that use the `maizzle` command, IF you're using `yarn` instead of `npm`:
```
yarn run v1.22.10
$ maizzle build production
env: node\r: No such file or directory
error Command failed with exit code 127.
```

To reproduce:
1. Create a new starter project: `maizzle new`
2. Delete `package-lock.json` and run `yarn install`
3. Run `yarn dev` or `yarn build`

Thanks!

**Comment by cossssmin** [comment]
Sounds like a yarn problem, have you tried doing `npm install` first?

**Comment by cossssmin** [comment]
I meant to say yarn may be caching some stuff, not really sure since I don't use it. There's nothing special that we do for npm and since yarn uses npm there must be something that we'd need to do for it instead, just don't know what 🤔

**Comment by jebax** [comment]
> I meant to say yarn may be caching some stuff, not really sure since I don't use it. There's nothing special that we do for npm and since yarn uses npm there must be something that we'd need to do for it instead, just don't know what 🤔

I've tried deleting node_modules and running `yarn cache clean` and still get the same problem, so doesn't seem like it's a problem specific to my machine / setup

**Comment by gyto** [comment]
+1 Having the same issue with serving via yarn and npm
```
npm run dev

> dev
> maizzle serve

env: node\r: No such file or directory
```

```
yarn dev     
yarn run v1.22.17
$ maizzle serve
env: node\r: No such file or directory
error Command failed with exit code 127.
```

**Comment by cossssmin** [comment]
@gyto and @jebax what operating system are you using?

I wonder if it could be because of line endings 🤔

**Comment by cossssmin** [comment]
Also, do you have the Maizzle CLI installed globally?

Just tested on a Mac that didn't have anything Maizzle-related installed and both scripts are working as expected.

**Comment by cossssmin** [comment]
Think I may found the issue, but will need your help to confirm.

Can you please open `node_modules/@maizzle/framework/bin/maizzle` in your editor and try to save it so that it has `LF` line endings?

For example, in VS Code it shows it in the bottom status bar, on the right side:

<img src="https://user-images.githubusercontent.com/1656595/173021829-2b0722ca-3351-44ae-8e1a-a5d441cf9ce7.png">

That's the executable used when running the npm scripts, and I see it had `CRLF` line endings, so that might be the culprit. Just need to confirm since I can't reproduce it on my end, thanks!

**Comment by cossssmin** [comment]
OK, we're getting there :)

You don't need `@maizzle/cli` in your `devDependencies`, it now comes included with the framework. Try uninstalling it and running the script again. If you have the CLI also installed globally, try uninstalling it from there too with `npm uninstall -g @maizzle/cli` (you can reinstall it later if you need to).

**Comment by jebax** [comment]
> OK, we're getting there :)
> 
> You don't need `@maizzle/cli` in your `devDependencies`, it now comes included with the framework. Try uninstalling it and running the script again. If you have the CLI also installed globally, try uninstalling it from there too with `npm uninstall -g @maizzle/cli` (you can reinstall it later if you need to).

Tried this but it hasn't helped unfortunately. Have uninstalled maizzle globally, deleted node modules, cleared the yarn cache, and installed again.

Can only get the commands to work by replacing `require('@maizzle/cli')` with `require('../../cli/bin/maizzle')`

**Comment by cossssmin** [comment]
Have you also removed  `package-lock.json` and/or `yarn.lock`? Without that it would just reinstall the same dependencies in the same way. It's complaining about a missing dependency, which shouldn't be the case.

**Comment by cossssmin** [comment]
Hmm no other ideas for now, except to blame yarn 🙈 

Need to check this with more users to ensure it's not some strange edge case and find out what's causing it...

**Comment by cossssmin** [comment]
@jebax what npm version are you using?

Could you try updating to latest with `npm install npm@latest -g` and testing again?

**Comment by JoeyEamigh** [comment]
Getting the same issue using a yarn-based turborepo monorepo on Linux. Let me know if there is any info I can provide to help debug this!

**Comment by mzgajner** [comment]
Can confirm the issue, my reproduction flow:
- `maizzle` **wasn't** installed globally
- Followed the [getting started guide](https://github.com/maizzle/maizzle), everything works as expected using `npm`.
- Once I install packages with `yarn`, errors start occurring when running `npm run dev`.
- Errors don't go away even if I delete `yarn.lock` and run `npm install`.
- Only thing that fixes it is deleting `node_modules` and reinstalling with `npm install`.

Versions:
- yarn 1.22.19
- npm 8.5.5
- node 16.15.0

**Comment by v1k45** [comment]
I am seeing the same issue after upgrading to 4.0.0. 

```
yarn run v1.22.18
$ maizzle serve
env: node\r: No such file or directory
error Command failed with exit code 127.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

I also tried deleting node_modules, it didn't work.

**Comment by cossssmin** [comment]
Hmm, I wonder if this is also an issue with yarn 2 - I see everyone reporting it is running v1.x

**Comment by cossssmin** [comment]
OK so I just gave yarn `1.22.15` a try and I was able to reproduce the issue where it failed to find the `maizzle` executable. Didn't get the line ending error though.

I then removed `package-lock.json` and reinstalled dependencies with `npm install` (so not through yarn), and was able to get `yarn dev` running perfectly fine. I'm on Windows 11, Node `16.13.2`, npm `8.4.0`.

**Comment by jebax** [comment]
> OK so I just gave yarn `1.22.15` a try and I was able to reproduce the issue where it failed to find the `maizzle` executable. Didn't get the line ending error though.
> 
> I then removed `package-lock.json` and reinstalled dependencies with `npm install` (so not through yarn), and was able to get `yarn dev` running perfectly fine. I'm on Windows 11, Node `16.13.2`, npm `8.4.0`.

this works for me, however the problem is that I want to manage my dependencies with `yarn`, not just execute the scripts. I guess there must be something about the `require('@maizzle/cli')` line that seems to be incompatible with `yarn` (aside from the line endings bug, which i'm assuming you aren't getting because you're on windows).

**Comment by cossssmin** [comment]
Yeah, not sure what we can do about that, I kinda doubt it's because of that require. I'll leave this open for now in case anyone comes up with a solution 👍

**Comment by v1k45** [comment]
> I then removed package-lock.json and reinstalled dependencies with npm install (so not through yarn), and was able to get yarn dev running perfectly fine. I'm on Windows 11, Node 16.13.2, npm 8.4.0.

Using npm worked for me. I am on Mac, Node 14, npm 6.


> You don't need @maizzle/cli in your devDependencies, it now comes included with the framework.

For some reason the `framework` dependency on its own didn't work. Had to manually install `@maizzle/cli` to make it work.

**Comment by dzcpy** [comment]
Same problem here. After installing with yarn there is an error running `yarn dev`
```
$ yarn dev // or npm run dev

> dev
> maizzle serve

node:internal/modules/cjs/loader:936
  throw err;
  ^

Error: Cannot find module '@maizzle/cli'
Require stack:
- /srv/node_modules/@maizzle/framework/bin/maizzle
    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:933:15)
    at Function.Module._load (node:internal/modules/cjs/loader:778:27)
    at Module.require (node:internal/modules/cjs/loader:1005:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at Object.<anonymous> (/srv/node_modules/@maizzle/framework/bin/maizzle:3:1)
    at Module._compile (node:internal/modules/cjs/loader:1101:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1153:10)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:81:12) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/srv/node_modules/@maizzle/framework/bi/maizzle'
  ]
}
```

**Comment by dzcpy** [comment]
One possible reason is that in `@maizzle/cli` there is no `""main"` attribute, so even you requires it, node.js doesn't know what to execute.

**Comment by cossssmin** [comment]
Released `v4.0.2`, let me know if it's working for you now 👍

**Comment by jebax** [comment]
works! thanks 🙏

**Comment by cossssmin** [comment]
Cool, thanks for confirming 👍
