### ISSUE TITLE
Preserving tags to avoid 'undefined' in production builds

### ISSUE THREAD

**Issue by llspalex** [maizzle/framework#710]
- Maizzle Version: 4.0.1
- Node.js Version: 14.18.0

To work with certain SendGrid features, I add tags like {{weblink}} or {{unsubscrib}} as the destination for an `<a>` tag, like this:
`<a href="{{Weblink}}" class="text-sm text-slate-500 underline">View in browser</a>`

When building for production, the tag is replaced with `undefined`, like this:
`<a href="undefined" target="_blank" style="color: #64748b; text-decoration-line: underline">Unsubscribe</a>`

Is there a way to tell Maizzle to preserve these tags when building, so that I don't have to manually re-add them in the SendGrid html editor?

**Comment by cossssmin** [comment]
https://maizzle.com/docs/templates#ignoring-expressions

**Comment by llspalex** [comment]
Mulţumesc, Cosmin! That works perfectly. Such a great repo, thanks for all your work.

**Comment by didiraja** [comment]
@cossssmin is there any way that i render variable on development but on prod, outputs as the tag?

Example:
- *Data*: `{ "user_name": "John Doe"}`
- *Development*: `Hello,  John Doe`
- *Production*: `Hello, {{page.user_name}}`

This is the last step to have a perfect workflow.

**Comment by cossssmin** [comment]
Starting with `v4.8.1` (released today) Maizzle will output undefined vars as-is, so try to set the `data` to be `undefined` in `config.production.js`. 

This way it compiles when developing locally (`config.js` is used), but the actual `{{ }}` curly braces are output when doing `maizzle build production`.

**Comment by didiraja** [comment]
@cossssmin great timing, huh? hahaha Gonna try that, thank you
