### ISSUE TITLE
`env: node\r: No such file or directory` (.bin/maizzle CRLF)

### ISSUE THREAD

**Issue by DaanVanVugt** [maizzle/framework#711]
- Maizzle Version: 3.7.3
- Node.js Version: 18.0.0 (and 16.15.0, npm 8.5.5)

It seems that node_modules/.bin/maizzle executable ends up in DOS mode.

Maizzle versions affected:
@maizzle/cli:
- 1.5.1
(1.5.0 and 1.4.0 seem to work, did not test below that)

**Comment by productdevbook** [comment]
```  "@maizzle/framework": "4.0.2"```

```
$ maizzle serve --bin ../../node_modules/@maizzle/framework/src
/usr/bin/env: ‘node\r’: No such file or directory
error Command failed with exit code 127.
```

some problem

**Comment by cossssmin** [comment]
Are you using yarn by any chance? Line endings are automatically handled by npm, but not by yarn.

Related #703

**Comment by productdevbook** [comment]
Yes, iam used yarn, how to fixed with yarn ?

**Comment by cossssmin** [comment]
I don't know if yarn can do this, but you can change the line endings with something like [dos2unix-cli](https://www.npmjs.com/package/dos2unix-cli):

```
npm install -g dos2unix-cli

dos2unix path/to/the/maizzle/bin
```

**Comment by productdevbook** [comment]
![image](https://user-images.githubusercontent.com/38668796/175485692-0f8e6dbc-9ed9-41b7-b68c-00d0eab2d643.png)


![image](https://user-images.githubusercontent.com/38668796/175485729-99b84b12-1bac-4a71-a4d5-25f3a0b38c7b.png)

**Comment by cossssmin** [comment]
Think it's how your Git is checking out those files, as you can see above they're both `LF` in the repo. You could also check if `autocrlf` is set to `false`: `git config core.autocrlf`.

**Comment by productdevbook** [comment]
If you look at the pictures, you will see that there is no lf. Look at the first picture.
