### ISSUE TITLE
Nested components sometimes don't load CSS

### ISSUE THREAD

**Issue by dg10mcdos** [maizzle/framework#714]
- Maizzle Version: 3.7.3
- Node.js Version: 16.14.2

Hi there!

I am having an issue with building emails with nested components. The CSS attached to the nested components don't seem to build properly. I have attached the relevant files below. Please let me know if I need to add anything else!
The files have been changed to .txt to allow attaching to this issue

[templates/componentised.html](https://github.com/maizzle/framework/files/8993163/componentised.-.Copy.txt)
[components/container2.txt](https://github.com/maizzle/framework/files/8993180/container2.txt)
[components/title.txt](https://github.com/maizzle/framework/files/8993187/title.txt)

<img width="390" alt="image" src="https://user-images.githubusercontent.com/19717408/175974511-9d8ac6ba-909a-480b-84fe-81271a34a402.png">

As you can see here, the top level title component displays just fine, but when nested within our container component the applied CSS is not recognised properly.

**Comment by cossssmin** [comment]
Please provide a link to a public repository that reproduces the issue and I'll look into it.
