### ISSUE TITLE
Custom single tag has its closing / removed

### ISSUE THREAD

**Issue by rfoost** [maizzle/framework#715]
- Maizzle Version: ^3.7.3
- Node.js Version: v16.9.1

I have a custom tracker tag that needs to be left alone. Currently, the compiler is taking the /> and removing it. When the tag is placed inside of a raw tag the '/>' is still replaced with '>' and a custom closing tag is added.  Any help would be greatly appreciated. Thank you!

Input:
`<raw>
	<custom name="opencounter" type="tracking" />
</raw>
<custom name="usermatch" type="tracking" />`
![input](https://user-images.githubusercontent.com/7066661/176305959-4e1155e2-c963-42a5-a581-d4179bd40260.png)

Output:
`<custom name="opencounter" type="tracking"></custom>
<custom name="usermatch" type="tracking">`
![output](https://user-images.githubusercontent.com/7066661/176305966-3653f7dc-e0b8-44e1-950d-dea5784a6d2a.png)

My config.production.js:
`  build: {
		posthtml: {
			options: {
				closingSingleTag: 'slash'
			}
		},`

![config](https://user-images.githubusercontent.com/7066661/176305991-3fece153-4263-4575-bdd2-c5267a35b7be.png)

**Comment by cossssmin** [comment]
Hey, thanks for bringing this up, it's one of those small things that should be documented :)

So you're halfway there, you just need to tell the compiler which tags are to be considered 'custom' so that it leaves them alone:

```js
module.exports = {
  build: {
    posthtml: {
      options: {
        closingSingleTag: 'slash', // should work without this too
        singleTags: ['custom']
      },
    },
  },
}
```

Then you can simply write `<custom />` without wrapping it in a `<raw>`.

**Comment by rfoost** [comment]
This worked! Thank you for the additional insight into how this behaves. It was difficult to find info related to 'closingSingleTag' in postHTML and in the Maizzle docs like you mentioned.  So it's great having a strong community to reach out to with questions. Thank you so much.

**Comment by cossssmin** [comment]
Cool, happy to help :)

**Comment by cossssmin** [comment]
Added to docs:

https://maizzle.com/docs/configuration/posthtml#singletags
