### ISSUE TITLE
Usage in Node

### ISSUE THREAD

**Issue by genu** [maizzle/framework#72]
The section on using on server side isn't very clear. I wasn't actually able to get it to work and there doesn't seem to be any other examples.

I think it needs to be more elaborate, or at least provide a full example so that someone can actually write up a good guide in the docs on how to set it up.

**Comment by cossssmin** [comment]
Sorry for the delay with this, https://github.com/maizzle/framework/commit/c7f89c8b528a906b27e7a3d41bbe9f6369a77822 should fix it.

Decided to go with an option in the config after all, as it made more sense after https://github.com/maizzle/framework/commit/e10f4cfc6ba3fb2edea191663147c8f2bb44a2b6 + I'd like to expose some of Nunjucks' options, like [tags](https://mozilla.github.io/nunjucks/api.html#customizing-syntax).

**Comment by cossssmin** [comment]
Added in [v0.6.0](https://github.com/maizzle/framework/releases/tag/v0.6.0), feel free to reopen if you spot any issues. Thanks!

**Comment by schhogyel** [comment]
I stumbled on this thread while trying to integrate with nodejs server side. The example link above is dead and there is no documentation on the website. Is this no longer officially supported? It would be nice to find an example.

**Comment by cossssmin** [comment]
https://maizzle.com/docs/nodejs/

**Comment by schhogyel** [comment]
Thanks @cossssmin, css styles were not appearing in my mails so I thought I might have missed some configurations. I turned on the `inclineCSS: true` and it is working super. Thanks again for this lovely email framework.

**Comment by digitalmaster** [comment]
Does this still work? Or has the ability to set a base path been removed?

The docs seem to suggest that this is no longer possible:
![image](https://user-images.githubusercontent.com/1279335/151084629-3005e688-51c7-4c76-9dd6-213e642592c6.png)


Thanks 🙏
