### ISSUE TITLE
Default layout not loaded

### ISSUE THREAD

**Issue by lowv-developer** [maizzle/framework#73]
- Maizzle Version: Framework v0.5.0 / CLI v0.3.0
- Node.js Version: v12.13.1

### Description:

If the layout var is not declared inside template, the default layout is not exported.

### Steps To Reproduce:

Default installation

### Solution:

$ @maizzle/framework/src/generators/output/toString.js

    //html = hasLayout ? `{% extends "${hasLayout}" %}\n${html}` : html
    html = layoutPath ? `{% extends "${layoutPath}" %}\n${html}` : html

**Comment by cossssmin** [comment]
The code you mentioned has been added in `v0.5.0` for template inheritance to work properly.

I'm currently investigating, but I think I'm going to roll back the template inheritance feature until we get it right.

**Comment by cossssmin** [comment]
Rolled it back for now, releasing a hotfix...

**Comment by lowv-developer** [comment]
I've made the tests, the const hasLayout seems to me unnecessary in general. i think that you use it only in this place.

**Comment by cossssmin** [comment]
It was so that you could extend a template from another template - see #69 

Obviously it didn't work as expected, resulting in no layout when `serve`ing and the same layout for all templates otherwise (even if you had specified a custom layout in Front Matter).

Released `v.0.5.1` as a hotfix 👍
