### ISSUE TITLE
API render not including Tailwind styles for components and layouts.

### ISSUE THREAD

**Issue by shripadk** [maizzle/framework#737]
Related issue: #565 

- Maizzle Version: 4.0.2
- Node.js Version: v14.19.3 (in Codesandbox) and v16.14.1 (in my Dev Machine)
- [Reproducible Repo](https://codesandbox.io/s/maizzle-repro-x5j5to?file=/README.md)

Firstly, thank you for making this framework. It makes developing email templates a breeze.

The issue I am reporting is similar to #565 (most likely the same). After going through that issue I realized that no one provided a reproducible repository for it. So have provided the same below.

The gist/summary of #565 issue (so you don't have to go through that entire thread all over again):

1. Tailwind styles are output correctly in page.css placeholder in Dev server running through `maizzle serve`.
2. Tailwind styles are not output correctly in page.css placeholder when using API. And it affects only Layouts and Components. Tailwind styles are correctly applied to Templates.

To reproduce this issue, please open the Codesandbox Sandbox I have created [here](https://codesandbox.io/s/maizzle-repro-x5j5to?file=/README.md). I have linked directly to the README so you will be able to follow the instructions there.

Have also attached screenshots of the steps involved in getting the Sandbox up and running for your convenience (if you get stuck anywhere please don't hesitate to holler at me):

1. By default, the Node sandbox server runs whatever is preconfigured with the Template itself. Ignore that port.
2. Open two new terminal tabs in the Codesandbox environment like so:

![SCR-20220807-3xc](https://user-images.githubusercontent.com/189344/183266436-994a1a87-b3e0-413a-967d-44c783aca054.png)

3. In the first Terminal tab, navigate to the "maizzle" sub-directory and install NPM dependencies. Run the following commands:

```bash
$ cd maizzle
$ npm i
```

As shown below:

<img width="1091" alt="image" src="https://user-images.githubusercontent.com/189344/183266535-1a94a805-7ddb-4e23-a915-66582c9518bc.png">

4. Then run the dev server from within the "maizzle" sub-directory. You will be prompted with a popup asking your permission to open a new browser tab pointing to Port 4000. Please confirm.

```bash
$ npm run dev
```

Shown below:

<img width="1094" alt="image" src="https://user-images.githubusercontent.com/189344/183266575-34893145-619b-496c-b1b8-fae78d662ff5.png">

5. New browser tab opens within the Sandbox which presents you with the file browser UI. Please click on confirm-user.html link. It should load the template perfectly as shown below:

<img width="1093" alt="image" src="https://user-images.githubusercontent.com/189344/183266630-e203728f-0c78-4a19-91d9-54cff7b6caed.png">

6. Now click on the second terminal and run the following command:

```bash
$ node maizzle-test.js
```

<img width="1087" alt="image" src="https://user-images.githubusercontent.com/189344/183266682-8ba67bd3-eb46-43d7-9924-70dcd7c421c5.png">

7. It should prompt you to open a new browser pane. Please confirm.

<img width="1091" alt="image" src="https://user-images.githubusercontent.com/189344/183266864-54a367c0-37d4-421c-bb25-5192dd374d1c.png">

8. The browser pane should open automatically and you should be presented with the output from API service. As you can see, the styles do not render for both "layouts", "components". Essentially anything that is extended/imported.

<img width="1091" alt="image" src="https://user-images.githubusercontent.com/189344/183267035-31df39aa-ef45-439a-beb0-96e230051c83.png">

9. Inspecting the Frame source, these are the only styles from Tailwind that are applied (note that all of them only belong to the classnames of elements defined within the "Template". They do not include any classnames from either the "layout" or the "component".

<img width="852" alt="image" src="https://user-images.githubusercontent.com/189344/183267086-5e9cc37c-dcfe-4ef4-9bf2-94d33fbd6e9e.png">

This makes me wonder if the Tailwind styles are being applied only for the Template string that is passed to the "render" API and is not waiting for the final HTML to be rendered (after fetching "layout" and "component" HTML and merging it with the "template").

I haven't dug into the source. But first wanted to provide a reproducible repo and log the issue.

**Comment by shripadk** [comment]
Okay I feel I know where the problem is. You are compiling Tailwind and generating CSS too early: https://github.com/maizzle/framework/blob/master/src/generators/output/to-string.js#L36

But PostHTML processing happens after this line ^ and ends here: https://github.com/maizzle/framework/blob/master/src/generators/output/to-string.js#L61

IMHO, the Tailwind compilation step should be after the final HTML has been generated.

Am I correct in my understanding? This is just from cursory glance at the code so I am not sure if this is the right solution.

**Comment by shripadk** [comment]
Also, just a side note (not related to the issue). Is it better to also provide a way to compile all Tailwind classes (for `tailwind.compiled`) so as to generate all the styles beforehand and remove unused styles later? That way, we can completely skip the Tailwind compilation step on every `render()` and speed things up drastically. For production environments, there is no reason to dynamically compile Tailwind classes for every render pass IMHO as the styles don't change between passes. It is a good option for development environment though.

**Comment by shripadk** [comment]
Can confirm that moving the block of code from [L36](https://github.com/maizzle/framework/blob/master/src/generators/output/to-string.js#L36) to [L47](https://github.com/maizzle/framework/blob/master/src/generators/output/to-string.js#L47) solves both issues.

Comparing both outputs:

```diff
@tailwind components; @tailwind utilities; .m-0{ margin: 0 !important
+ } .mt-2{ margin-top: 8px !important
+ } .mb-0{ margin-bottom: 0 !important
} .mb-6{ margin-bottom: 24px !important
} .mb-4{ margin-bottom: 16px !important
+ } .mb-2{ margin-bottom: 8px !important
} .block{ display: block !important
} .inline-block{ display: inline-block !important
} .table{ display: table !important
+ } .hidden{ display: none !important
} .h-px{ height: 1px !important
} .h-8{ height: 32px !important
} .w-full{ width: 100% !important
} .w-150{ width: 600px !important
+ } .max-w-full{ max-width: 100% !important
+ } .cursor-default{ cursor: default !important
} .rounded-lg{ border-radius: 8px !important
} .rounded{ border-radius: 4px !important
} .bg-slate-300{ background-color: #cbd5e1 !important
} .bg-white{ background-color: #fff !important
} .bg-indigo-700{ background-color: #4338ca !important
} .bg-slate-200{ background-color: #e2e8f0 !important
+ } .p-0{ padding: 0 !important
+ } .p-12{ padding: 48px !important
} .py-2{ padding-top: 8px !important; padding-bottom: 8px !important
} .px-6{ padding-left: 24px !important; padding-right: 24px !important
} .py-3\.5{ padding-top: 14px !important; padding-bottom: 14px !important
} .px-4{ padding-left: 16px !important; padding-right: 16px !important
} .py-3{ padding-top: 12px !important; padding-bottom: 12px !important
} .py-8{ padding-top: 32px !important; padding-bottom: 32px !important
+ } .pb-8{ padding-bottom: 32px !important
} .text-left{ text-align: left !important
} .text-center{ text-align: center !important
+ } .align-middle{ vertical-align: middle !important
} .font-sans{ font-family: ui-sans-serif, system-ui, -apple-system, "Segoe UI", sans-serif !important
+ } .text-3xl{ font-size: 30px !important
} .text-base{ font-size: 16px !important
+ } .text-2xl{ font-size: 24px !important
+ } .text-xs{ font-size: 12px !important
+ } .font-semibold{ font-weight: 600 !important
+ } .leading-6{ line-height: 24px !important
+ } .leading-full{ line-height: 100% !important
+ } .leading-px{ line-height: 1px !important
+ } .tracking-6{ letter-spacing: 24px !important
+ } .text-slate-700{ color: #334155 !important
+ } .text-black{ color: #000 !important
+ } .text-white{ color: #fff !important
+ } .text-slate-500{ color: #64748b !important
+ } .text-indigo-700{ color: #4338ca !important
+ } .mso-text-raise-4{ mso-text-raise: 16px
+ } .mso-text-raise-7{ mso-text-raise: 28px
+ } .mso-font-width-full{ mso-font-width: 100%
+ } .-mso-font-width-full{ mso-font-width: -100%
+ } .mso-text-raise-7\.5{ mso-text-raise: 30px
+ } .shadow{ box-shadow: 0 1px 3px 0 rgba(0, 0, 0, 0.1), 0 1px 2px -1px rgba(0, 0, 0, 0.1) !important
+ } .\[word-break\:break-word\]{ word-break: break-word
+ } .\[-webkit-font-smoothing\:antialiased\]{ -webkit-font-smoothing: antialiased
+ } .\[border\:0\]{ border: 0
+ } .\[text-decoration\:none\]{ text-decoration: none
+ } .hover\:bg-indigo-600:hover{ background-color: #4f46e5 !important
+ } .hover\:text-slate-900:hover{ color: #0f172a !important
+ } .hover\:\[text-decoration\:underline\]:hover{ text-decoration: underline
+ } @media (max-width: 600px){ .sm\:w-full{ width: 100% !important
+     } .sm\:py-8{ padding-top: 32px !important; padding-bottom: 32px !important
+     } .sm\:px-6{ padding-left: 24px !important; padding-right: 24px !important
+     } .sm\:py-2{ padding-top: 8px !important; padding-bottom: 8px !important
+     } .sm\:pb-4{ padding-bottom: 16px !important
+     } .sm\:text-center{ text-align: center !important
+     } .sm\:text-2xl{ font-size: 24px !important
+     } .sm\:leading-8{ line-height: 32px !important
+     }
+ }
```

Will open a pull request with the changes soon.

**Comment by shripadk** [comment]
More complicated than I initially thought. Seems like the `page.css` expression is being replaced in `posthtml.js` through the `posthtml-extend` plugin. I am thinking of just adding a placeholder in `config.css` by assigning it to `html{}`. Then wait for the PostHTML to finish processing, and in the end do a simple string replacement of `html{}` with the Tailwind styles.

Something like this (in `src/generators/output/to-string.js` function. *Truncated unconnected code*):

```diff
  if (options && typeof options.beforeRender === 'function') {
    html = await options.beforeRender(html, config)
  }

  if (typeof get(options, 'tailwind.compiled') === 'string') {
    config.css = options.tailwind.compiled
  } else {
-    config.css = await Tailwind.compile(cssString, html, tailwindConfig, config)
+    config.css = "html{}"
  }

  html = await posthtml(html, config)

  while (Object.keys(fm(html).attributes).length > 0) {
    html = fm(html).body
  }

  if (options && typeof options.afterRender === 'function') {
    html = await options.afterRender(html, config)
  }

  if (config.applyTransformers) {
    html = await Transformers.process(html, config)
  }

  if (options && typeof options.afterTransformers === 'function') {
    html = await options.afterTransformers(html, config)
  }

  html = await posthtmlMSO(html, config)
+  html = html.replace("html{}", await Tailwind.compile(cssString, html, tailwindConfig, config))


  return {
    html,
    config
  }
```

What do you suggest @cossssmin?

**Comment by shripadk** [comment]
Currently I have decided to simply scan all the files in the `src` directory, extracting the Tailwind classes into one big compiled CSS file (through await Maizzle.tailwindcss.compile). Then feed it into the API through `tailwind.compiled` config attribute and also enable `removeUnusedCSS` to remove unused styles from the generated template. Renders in under 30ms compared to 450-500ms it would take otherwise. Same output as before but with much faster render times.

Maybe will even add a watcher for good measure to watch for directory changes and rebuild the compiled CSS file.

I would prefer if something like this was built into the library itself.

**Comment by cossssmin** [comment]
Hey thanks for the detailed report :)

You need to tell Tailwind to scan your layouts and components directories - when using the API, these are not pre-set like they are with the CLI command.

<img width="327" alt="image" src="https://user-images.githubusercontent.com/1656595/183584751-45536028-87e0-4f19-ba94-5358f352cb76.png">

**Comment by shripadk** [comment]
Woah you are right! I was pretty sure I read the documentation thoroughly (multiple times even) but did not come across this anywhere. Is this documented anywhere that I missed?

**Comment by Jank1310** [comment]
Had the same problem as @shripadk. It would be great if some notice regarding this could be added to the "gotchas" section in https://maizzle.com/docs/api 👀
