### ISSUE TITLE
Trailings slashes  in URLs get Replaced by -

### ISSUE THREAD

**Issue by j-mori** [maizzle/framework#76]
- Maizzle Version: 0.5.2
- Node.js Version: v12.13.1

### Description:
Trailings slashes  in URLs get replaced by `-` if preceded by another `-` in the same URL
For ex: `https://test.test/my-docs/help`
become
`https://test.test/my-docs-help`

The issue is caused by new feature "Escaped class names" 
2e4395df3eb21d2cac4d3f6856f7369a82b09b5f

**Comment by cossssmin** [comment]
Thanks for reporting, looks like we need a better regex...

**Comment by cossssmin** [comment]
This might do the job : `(\w+)(\/)(?<!\..+)`

Just tested it on regexr, and it catches all classes in this HTML, but not the URL:

```js
const regex = /(\w+)(\/)(?<!\..+)/g
const string = `<div class="w-1/2 sm-w-1/4 dark-something/nothing">
    <a href="https://example.com/slug-url/test">test</a>
  </div>`

string.match(regex) // ["1/", "1/", "something/"]
```

**Comment by cossssmin** [comment]
The regex above assumes a URL contains a dot character, so it would fail with a url like this:

`https://localhost:8080/some-page/page`

Need to look into avoiding any URL no matter where it shows up...

**Comment by cossssmin** [comment]
This works better:

`(\w+)(\/)(?<!(?:href|src|url).+)`

![image](https://user-images.githubusercontent.com/1656595/71000227-981e2980-20e3-11ea-97e3-1090ac37bdcc.png)

**Comment by j-mori** [comment]
> This works better:
> 
> `(\w+)(\/)(?<!(?:href|src|url).+)`


Yeah definitely better to look for the tag! maybe add the assignment character as well?
`(\w+)(\/)(?<!(?:href(\s+)?\=|src(\s+)?\=|url(\s+)?\:|background(\s+)?\:).+)`

**Comment by cossssmin** [comment]
Nah, not needed (+ it fails like that). I'll try to publish a release today. Thanks again!

**Comment by j-mori** [comment]
Mmmh, i m using it right now and it seems work pratty fine but maybe i m missing something. 
Without assignment char some class like `background-teal/orange` (could happen?) won't be translated.

![regexTest](https://user-images.githubusercontent.com/58422318/71006690-082daf00-20e6-11ea-9b6d-9e8d889ccb7e.png)

**Comment by cossssmin** [comment]
My bad, had an extra character in there. Yeah, this is better, didn't think of classes starting with `background-` (_could_ happen).

Btw the downside is that your `class=""` needs to be before those negated attributes:

![image](https://user-images.githubusercontent.com/1656595/71007514-cc97e280-20ef-11ea-9e62-d7f6319d4f4f.png)

**Comment by j-mori** [comment]
> My bad, had an extra character in there. Yeah, this is better, didn't think of classes starting with `background-` (_could_ happen).
> 
> Btw the downside is that your `class=""` needs to be before those negated attributes:
> 
> ![image](https://user-images.githubusercontent.com/1656595/71007514-cc97e280-20ef-11ea-9e62-d7f6319d4f4f.png)

you are right, checking for attribute enclosure should fix the problem
`(\w+)(\/)(?<!(?:href\s*\=|src\s*\=|url\s*\(|background\s*\=).+"|'|\>)`

**Comment by cossssmin** [comment]
Yeah, seeing that catching the URLs again :)

**Comment by j-mori** [comment]
what about check for the `class` attribute?
`class=\"[^"]*(\/)[^"]*\"`

**Comment by cossssmin** [comment]
Not really, that matches the entire class attribute.

Think I'll go with this for now, and mention that the `class=""`  attribute must be first:

`(\w+)(\/)(?<!(?:href\=|src\=|background[:=]).+)`

**Comment by cossssmin** [comment]
Adding a `-` in front would obviously fix it:

`(-\w+)(\/)(?<!(?:href\=|src\=|background[:=]).+)`

**Comment by cossssmin** [comment]
☝ added in [v0.5.3](https://github.com/maizzle/framework/releases/tag/v0.5.3). 

Keeping this open until we find a better solution, that doesn't require writing the `class=""` attribute before `href=""`, `src=""`, and `background=""` attributes.

**Comment by j-mori** [comment]
> Not really, that matches the entire class attribute.

This seems work pretty fine 

```
    html = html
      // replace \/ in class names from head
      .replace(/(\..+-)(\w+)(\\\/)/g, '$1$2-')
      // replace / in class names from body
      .replace(/class=["'][^"']*[/:_][^"']*["']/g,function(par1){
        return par1.replace(/\/|_|:/g,'-');
      })
      // replace \: in class names from head
      .replace(/(\.\w+)(\\:)/g, '$1-')
      // replace : in class names from body
      .replace(/(\w)(\s\w+)(:)(\w)/g, '$1$2-$4')
```

**Comment by cossssmin** [comment]
Yup, looks like it works pretty well 👍

Other regexes: I'm listening.

**Comment by cossssmin** [comment]
So with this we can remove all other replacements and have only:

```js
html = html
      // replace \/ in class names from head
      .replace(/(\..+-)(\w+)(\\\/)/g, '$1$2-')
      // replace \: in class names from head
      .replace(/(\.\w+)(\\:)/g, '$1-')
      // replace special characters in class names from body
      .replace(/class\s*=\s*["'][^"']*[/:][^"']*["']/g, (group) => {
        return group.replace(/\/|:/g, '-')
      })
```

I'll go ahead with this, but I'm open to suggestions regarding the first two replacements above 👍

**Comment by cossssmin** [comment]
Ended up using this in https://github.com/maizzle/framework/commit/d204ad7f77e2706be6b5ed0145e47c827781ee58:

https://github.com/maizzle/framework/blob/49a2faa896745a060445f5c60349581bcdfef811/src/generators/output/toString.js#L70-L72

Feel free to reopen if you spot any issues or think we can improve it ✌
