### ISSUE TITLE
TypeError: Cannot read property 'tags' of undefined

### ISSUE THREAD

**Issue by Blake32p** [maizzle/framework#77]
- Maizzle Version: 0.6.0
- Node.js Version: 6.13.0

### Description:
When attempting Maizzle Serve on a project I get the following error.

> ✖ Build failed
> TypeError: Cannot read property 'tags' of undefined
>     at Object.module.exports.init (/node_modules/@maizzle/framework/src/nunjucks/index.js:7:23)
>     at module.exports (/node_modules/@maizzle/framework/src/generators/output/toString.js:62:48)
>     at asyncForEach (/node_modules/@maizzle/framework/src/generators/output/toDisk.js:49:18)

### Steps To Reproduce:
Originally I started getting this error today on a project I had been working on for a while, but I tried creating a new project and continue to get the error. I tried using different node versions but I still get the same error. I also tried on two different Mac computers and get the same error.

**Comment by cossssmin** [comment]
Checking, I might have screwed something up in https://github.com/maizzle/framework/commit/6beb37aaec37c2fce63a438b88137d73ef07e220

Thanks for reporting!

**Comment by cossssmin** [comment]
Yeah... wanted to not have a breaking change, but forgot to check if `build.nunjucks` actually exists in your config, and fallback if it doesn't 🤦‍♂️

Will tag 0.6.1 right away, sorry about that!

**Comment by cossssmin** [comment]
Published [v0.6.1](https://github.com/maizzle/framework/releases/tag/v0.6.1), please update. And again, sorry for the trouble!

**Comment by Blake32p** [comment]
Thanks for fixing this so quickly!
