### ISSUE TITLE
Force include dynamic tailwind classes?

### ISSUE THREAD

**Issue by tettoffensive** [maizzle/framework#798]
If I have something like this:

```html
<template type="amp-mustache">
 <div class="day col-start-{{col}}">
```
The problem is that none of the tailwind classes will be included in the compiled html. I wonder if there might be a way to force include certain tailwind classes I need?

**Comment by cossssmin** [comment]
As mentioned in the Tailwind CSS [documentation](https://tailwindcss.com/docs/content-configuration#dynamic-class-names), this is not possible. You need to write the class name in full, i.e. `col-start-1`.

Also if you have `removeUnusedCSS: true` in your Maizzle `config.*.js` file (default when building for production), you'll need to [safelist templating language delimiters](https://maizzle.com/docs/transformers/remove-unused-css#backend), as mentioned in #797.
