### ISSUE TITLE
Variable being translated to ASCII during build from config.js

### ISSUE THREAD

**Issue by wildernessfamily** [maizzle/framework#828]
- Maizzle Version: 4.3.0
- Node.js Version: 7.21.0

Hi, first I just want to say that Maizzle is awesome! I found Maizzle framework just a few days ago. It makes creating and designing emails so simple! Thank you to all the developers!

I'm having a problem converting a variable in the `config.js` file. I have read the documentation multiple times but can not find what I'm doing wrong.

In my `config.js` I have the following:
```
locals: {
    email: {
          user: "@{{ _fsdomain('%(first_name)';, first_name=user.first_name) }}",
    }
}
```

In my `welcome.html` I have:
```
<p> Hello, {{ email:user }} </p>
```

When Maizzle builds the `welcome.html` email, it changes the previous line to:
```
Hello {{ _fsdomain(&#039;%(first_name)&#039;;, first_name=user.first_name) }}
```
The build changes the apostrophe from `'` to the ASCII version of `&#039;`. I'm using this email in Flask with Jinja2 and I need to keep it in its raw form.

If I don't use config.js and add the string right in the HTML, it does not change the apostrophe.
**Pre-Build** - `welcome.html`
```
<p> Hello "@{{ _fsdomain('%(first_name)';, first_name=user.first_name) }}",</p>
```

**Post-Build** - `welcome.html`
```
<p> Hello "{{ _fsdomain('%(first_name)';, first_name=user.first_name) }}", </p>
```

If I add the variable to the page, it does the same thing as the config.js.
**Pre-Build** - `welcome.html`
```
---
user: "@{{ _fsdomain('%(first_name)';, first_name=user.first_name) }}"
---
<p>Hello {{ page.user }} </p>
```
**Post-Build**
```
Hello {{ _fsdomain(&#039;%(first_name)&#039;;, first_name=user.first_name) }}
```

I have tried every way I can think of escaping the apostrophe. I've also tried adding filters like `safe` and `jsononly`. I tried the filter as stated in the manual `<p url-decode> {{ email.user }}` but url-decode dosn't seem to work. During the build I receive an error stating I need to save the prebuild `welcome.html`. However, I did save the file. I tried several times saving the file but each time I do the build it states that the pre-build `welcome.html` was not saved and does not build.

I'm not sure what I'm doing wrong. Any guidance would greatly appreciate!

Again, thank you to all the developers/contributors on Maizzle!

**Comment by cossssmin** [comment]
Hi, use `{{{ }}}` triple curly braces to unescape strings in expressions:

https://maizzle.com/docs/templates#unescaping-variables

**Comment by wildernessfamily** [comment]
Hi @cossssmin thanks for responding.
Lack of sleep from this project I'm doing was the problem. I actually tried the triple curly braces last night. Just for anyone else that might be a little sleep-deprived, here is how to do it.
In `config.js` I did the `{{{ }}}`but that did not work. ex.
`user: "@{{{ _fsdomain('%(first_name)';, first_name=user.first_name) }}}",`
What I should have done was:
`config.js`
`user: "@{{ _fsdomain('%(first_name)';, first_name=user.first_name) }}",`
and in `welcome.html` and the triple curly braces `{{{ }}}`
`<p>Hellp {{{ email.user }}}`

Thanks again @cossssmin
