### ISSUE TITLE
Can I programatically build html from tailwindcss html?

### ISSUE THREAD

**Issue by karolis-stulgys-allhuman** [maizzle/framework#840]
As I understand, the way `maizzle` framework works is that I first code html with `tailwindcss` utilities then I run a `build` command and it outputs another html (the one I can use sending an email).

Is there a way to run that build programmatically? 
Imagine a website where I can paste tailwindcss html, click `generate` and it will show me generated html. Is that possible? How should I implement this if I'm building this kind of website?

**Comment by cossssmin** [comment]
Hi there, take a look at the API docs:

https://maizzle.com/docs/api
