### ISSUE TITLE
How to output  <table class="container">

### ISSUE THREAD

**Issue by boskakke** [maizzle/framework#864]
- Maizzle Version: 4.3.1
- Node.js Version: 18

Hi 
I'm doing some edits on some markup that a previous developer did. And I wanted to run my code through Maizzle (what a fantastic tool)  

Because I dont want to change the overall template in the project, I need my html to render this:
`<table class="container">` 

I've tried the following:
```
<table class="container">
<table class="{container}">
<table class="{{container}}">
<table class="{{{container}}}">
<table class="@{{container}}">
<table class="@{{{container}}}">
```
Is it possible?

**Comment by cossssmin** [comment]
For anyone else looking to do this, see the solution in the discussion: https://github.com/maizzle/framework/discussions/865
