### ISSUE TITLE
Yarn 3.3.1 doesn't work with Maizzle

### ISSUE THREAD

**Issue by caelinsutch** [maizzle/framework#870]
- Maizzle Version: latest
- Node.js Version: 16.16.0
 
Getting error:
```
Error: Framework not found

Make sure to run this command in your Maizzle project root, with dependencies installed.
```

If I install dependencies using `yarn` and run `yarn dev`, this error will appear. If installing via `npm i` and run `npm run dev` it works fine.

Probably an issue with how the newest version of `yarn` resolves deps.

**Comment by caelinsutch** [comment]
I ran an install with `npm`, then with `yarn`, and it works fine now. Pretty odd

**Comment by cossssmin** [comment]
> Probably an issue with how the newest version of `yarn` resolves deps.

Sounds very likely. I have no experience with `yarn` so I'd appreciate any help with this 👍
