### ISSUE TITLE
Inliner will not inline styles in of classes inside a component if they do not exist in index.html

### ISSUE THREAD

**Issue by rfoost** [maizzle/framework#874]
Hi,

I'd like to report an interesting bug. As the title explains I have classes inside my component that do not exist anywhere else in the email.

`<component src="/src/sections/footer.html"></component>`

Example:
I have a footer component that has td's with a class of "legal" which specifies a font-size. Currently, by default, the class of "legal" is removed in the build but the font-size is not inlined. However, if I use the class "legal" in the index.html anywhere above or below the component then the component will receive the inline style properly.

Even more interesting is during my testing, I applied a commented-out line of code containing the classes after the component and it then properly inlined the styles in the component. The reason I find it interesting is that in the build, since the line is commented out, the inliner ignores that anyway and the class is not removed:

`<component src="/src/sections/02-signoff.html"></component>
`

node v18.12.1
maizzle CLI: v1.5.1

**Comment by cossssmin** [comment]
Just to make sure I understand, you have some HTML that is commented, i.e.

```html
<!-- <tr><td class="legal"></td></tr> -->
```

Is that correct?

If so, commented HTML is not actual HTML (i.e. with DOM nodes etc.), it's just a string of text. The inliner will not inline CSS on strings, it only works with HTML elements.

**Comment by cossssmin** [comment]
Just tried this in `v3.7.3` and works fine, if I'm misunderstanding or you have a different setup please provide a repo that reproduces the issue and I'll reopen if necessary 🙏

Component:

```html
<div class="legal">
  <content></content>
</div>
```

`utilities.css`:

```postcss
@layer utilities {
  .legal {
    font-size: 0.75rem;
  }
}
```

`src/templates/example.html`:

```html
<extends src="src/layouts/main.html">
  <block name="template">
    <component src="src/components/test.html">
      Legal footer text.
    </component>
  </block>
</extends>
```

Running `npm run build` we get this in `build_production/example.html`:

```html
<div style="font-size: 0.75rem"> Legal footer text.</div>
```
