### ISSUE TITLE
Correct 4.4.0-beta.1 release example

### ISSUE THREAD

**Issue by jsbrain** [maizzle/framework#884]
[Here](https://github.com/maizzle/framework/releases#:~:text=template%3E%3C/block%3E%0A%2B-,%3Cfill%3Atemplate%3E%3C/fill%3Atemplate%3E,-src/templates/example) in the `layout` code blocks is a typo, it should be `<slot:template></slot:template>` not `<fill:template></fill:template>`.

If possible this should be changed or otherwise [the link](https://maizzle.com/guides/markdown-emails#:~:text=%F0%9F%A7%A9%20Maizzle%204.4.0%20Beta%3A%20try%20out%20the%20new%20Laravel%20Blade%2Dlike%20components%20system%20%E2%86%92) on the website should be changed so it doesn't lead one to an invalid example.

Did trip me up for quite a while until I figured out why nothing is working, so hopefully this prevents others from running into it.

**Comment by cossssmin** [comment]
Fixed it now, thanks for noticing 👍
