### ISSUE TITLE
Frontmatter expression ignorance is not working

### ISSUE THREAD

**Issue by asaf** [maizzle/framework#888]
Ignoring expressions in front matter as described here https://maizzle.com/docs/templates#ignoring-expressions-in-front-matter
is not working,

The result is:
```
title: "Weekly newsletter no. @{{ edition_count }}"
```

yields:

```
Weekly newsletter no. undefined
```

 Versions:
- Maizzle Version: 4.3.1
- Node.js Version: 18.13.0

**Comment by cossssmin** [comment]
It works fine in templates, where are you outputting it? In layouts or components you'll need to also ignore it there besides ignoring it in front matter, for example:

```html
<component src="src/components/test.html">
  @{{ page.title }}
</component>
```

**Comment by asaf** [comment]
Weird, it's not working in templates for me,

I just took the default `transactional.html` file with the following front-matter metadata:

```
---
title: "Hello @{{ .someVar }} example"
preheader: "Hello"
bodyClass: bg-white
---
```

The result in `build_production` folder is:

```html
      <title>Hello undefined example</title>
```

**Comment by cossssmin** [comment]
Yup, that's why I asked, `<title>` is in a layout (`src/layouts/main.html` by default).

So to use ignored expressions from front matter there you need to escape `page.title` in that file. 

Change it to:

```html
<title>@{{ page.title }}</title>
```

**Comment by asaf** [comment]
Got it! thanks, closing.
