### ISSUE TITLE
base URL not applied to background-image: url

### ISSUE THREAD

**Issue by carldegs** [maizzle/framework#893]
- Maizzle Version: 4.3.1
- Node.js Version: 16.14.2

I have a `<td>` with an image background

```html
<td style="background-image: url('images/test-image.png'); border-radius: 4px; background-color: #220A39; background-size: cover; background-position: top; background-repeat: no-repeat; text-align: left"></>
```

and a config with `baseURL`
```javascript
module.exports = {
  baseURL: {
    url: "https://************.net/",
    tags: ["img", "td"],
  },
  build: {
    templates: {
      destination: {
        path: 'rendered/dev',
      },
    },
  },
  inlineCSS: true,
  removeUnusedCSS: true,
}
```

The issue is that when built, the url image path used for the background image does not include the `baseURL`.
```html
        <td style="background-image: url('images/test-image.png'); border-radius: 4px; background-color: #220A39; background-size: cover; background-position: top; background-repeat: no-repeat; text-align: left">
```

Is there additional configuration that I should set for this to work? Thanks!

**Comment by cossssmin** [comment]
Hi there, yes, when configured as an object you currently need to explicitly enable it for inline or embedded styles, separately.

In your case:

```js
module.exports = {
  baseURL: {
    url: 'https://cdn.example.com/',
    tags: ['img'],
    inlineCss: true,
  },
}
```

This will be handled automatically in `v4.4.0` so the way you currently have it will just work then.
