### ISSUE TITLE
Locals returns undefined

### ISSUE THREAD

**Issue by cantutar** [maizzle/framework#904]
- Maizzle Version: 4.3.1
- Node.js Version: v16.15.0

The main issue is i was following the what docs said so the command that i used the create project is this:
`npx degit maizzle/maizzle my-project`

config.js file
```
module.exports = {
  build: {
    templates: {
      source: "src/templates",
      destination: {
        path: "build_local",
      },
      assets: {
        source: "src/images",
        destination: "images",
      },
    },
    locals: {
      year: 2023,
      company: {
        name: "PLAYERSE, Inc.",
        slogan: "ALL IN ONE PLACE FOR PLAYERS.",
        slogan2: "We believe that gaming is a social experience.",
      },
      approveText: "Here is your login approval code: ",
    },
  },
};
```
code snippet that returns undefined:
```html
<td class="text-center text-xs text-neutral-600">
                    <span>© {{year}} {{company.name}}-{{company.slogan}}</span>
                  </td>
```
![image](https://user-images.githubusercontent.com/43760169/219357454-98da6e28-6bfb-4f50-9f59-7b7c39e1b07f.png)

**Comment by cossssmin** [comment]
Hi there,

You're nesting `locals` under `build`, that's why it doesn't work :)

It needs to be a top-level key in the export, as shown in the [docs](https://maizzle.com/docs/environments#top-level-variables):

```js
module.exports = {
  build: {
    // ...
  },
  locals: {
    year: 2023,
    company: {
      name: "PLAYERSE, Inc.",
      slogan: "ALL IN ONE PLACE FOR PLAYERS.",
      slogan2: "We believe that gaming is a social experience.",
    },
    approveText: "Here is your login approval code: ",
  },
};
```

**Comment by cantutar** [comment]
@cossssmin helped out that locale needs to be outside of build, thanks for the help and point out.
