### ISSUE TITLE
Loop over object not working

### ISSUE THREAD

**Issue by lowbits** [maizzle/framework#916]
- Maizzle Version: 4.3.1
- Node.js Version: v18.13.0

Im trying to loop over on object like `{annual_revenue: 3000, employees: 3}`, but when i do

```ts
<each loop="key, value in {annual_revenue: 3000, employees: 3}">
   <p class="mt-2 mb-3 text-slate-500">{{ key }}: {{ value }}</p>
</each>
```

The generated HTML is empty, when I loop over an array it is working. 

But is it also possible to loop over a parameter coming from context, for example, with handlebars .hbs?

**Comment by cossssmin** [comment]
Can confirm, it won't work if you pass the object inline. Looks like this is actually how `posthtml-expressions` currently works, I've opened a PR to replicate the issue and see what could be done about it: https://github.com/posthtml/posthtml-expressions/pull/146

In Maizzle you can either set that data in the `config.js` or in the template's Front Matter, and use it off the `page` object.

Here's how you'd do it with FM:

```html
---
obj:
  annual_revenue: 3000
  employees: 3
---

<each loop='key, value in page.obj'>
  {{ key }}: {{ value }}
</each>
```

You'd use `page.obj` the same way if you added the data to `config.js`:

```js
module.exports = {
  obj: {
    annual_revenue: 3000,
    employees: 3
  },
  build: { ... },
}
```

**Comment by lowbits** [comment]
Thank you for your reply, currently, I adjust this in the created `.hbs`.
So every time I adjust the template, in maizzle I need to adjust it. For now, it's okay.
