### ISSUE TITLE
Tailwindcss important: false does not overwrite 'base' config.

### ISSUE THREAD

**Issue by quddoss** [maizzle/framework#919]
- Maizzle Version: 4.4.0-beta.10
- Node.js Version: 16.19.0

I am trying to disable the option `important: false` in tailwind.config.js for enable `preserveImportant ` in inlineCSS, but the base config overwrites this setting. And as a result, in the final file, everywhere is added `!important`.

**Comment by cossssmin** [comment]
Hi there, here's what I tested and it works as expected - hope I understood what you're trying to achieve:

```js
// tailwind.config.js

module.exports = {
  important: false,
  // theme, plugins etc.
}
```

```js
// config.production.js

module.exports = {
  inlineCSS: {
    preserveImportant: true,
  },
  // ... build, prettify etc.
}
```

src/templates/example.html:

```html
<x-main>
  <fill:template>
    <p class="!mt-2 text-slate-500">
      This paragraph uses `!important` for the `margin-top` CSS.
    </p>
  </fill:template>
</x-main>
```

Running `npm run build` or `maizzle build production` outputs `build_production/example.html` (showing just the paragraph for brevity):

```html
<p style="color: #64748b; margin-top: 8px !important">
  This paragraph uses `!important` for the `margin-top` CSS.
</p>
```

If that's not what you're trying to do, can you give me a simplified example of what you expect the HTML output to be, and what is actually output for you? I'll assume the config files are as in the examples above.

**Comment by quddoss** [comment]
Yeah , config is same , but for all the classes in the file, !important is added ... 

Example part:

``` html
<table class="w-full">
  <tr>
    <td class="p-12 text-center" align="center" valign="top" attributes>
      <content></content>
    </td>
  </tr>
</table>
```

Result:

``` html
<table style="width: 100% !important;" border="0" cellpadding="0" cellspacing="0" role="presentation">
  <tbody>
    <tr>
      <td align="center" valign="top" style="padding: 48px !important; text-align: center !important"></td>
    </tr>
  </tbody>
</table>
```

``` js
// config.production.js
module.exports = {
    baseURL: {
        url: 'images/',
        tags: ['img', 'source'],
    },
    build: {
        templates: {
            destination: {
                path: 'dist',
            },
        }
    },
    inlineCSS: {
        preserveImportant: true,
    },
    shorthandCSS: true,
    removeUnusedCSS: true,
    minify: {
        lineLengthLimit: 500,
        removeIndentations: true,
        removeCSSComments: true,
        removeLineBreaks: true,
        breakToTheLeftOf: []
    },
}
```

**Comment by quddoss** [comment]
For the test, I just rewrote in the base config from important: true to false , and everything work fine, but this is only test and not solution ... :)

**Comment by cossssmin** [comment]
You are adding `important: true` in the wrong place, see my example again :)

**Comment by quddoss** [comment]
I spent two days... for my mistake , thx a lot !

**Comment by cossssmin** [comment]
Happy to help! 😊
