### ISSUE TITLE
Default config.production.js is missing minify

### ISSUE THREAD

**Issue by Uninen** [maizzle/framework#96]
- Maizzle Version: 0.7.3

### Description:

In `config.js` comments reads "Enable and configure minifier options. Enable for production builds." but minify is missing from the default `config.production.js`. Would it be good to have good defaults and best practices encouraged in the default configuration or is there some reason minify is omitted?

I can do a PR for adding at least the very basic minify configuration (`enabled: true`) or maybe a better default configuration if someone more experienced could say what it would be.

**Comment by cossssmin** [comment]
Yup, this was done on purpose in https://github.com/maizzle/maizzle/commit/f12843dc860d5775f3fed185eef171c5928d133e, where I've simplified the setup.

Minification isn't a best practice for HTML emails - actually, if you're not careful it can even cause issues. Most of the time, you don't need to minify HTML email code, it's an extra step for exceptional cases where your HTML is too heavy and you want to avoid things like [Gmail's clipping limit](https://github.com/hteumeuleu/email-bugs/issues/41).

Thanks for offering to PR, but it won't be necessary - I'll look into maybe rephrasing the docs 👍

**Comment by Uninen** [comment]
Ok, good to know! Your reply would indeed be good addition to the docs, as well as removing the request to "Enable for production builds." in the config.js minify settings 👍
