### ISSUE TITLE
Optional component properties containing dashes

### ISSUE THREAD

**Issue by priithansen** [maizzle/framework#963]
- Maizzle Version: 4.4.4
- Node.js Version: 18.13.0

Seems there might be a little inconsistency of how Maizzle components handle properties depending if they contain dashes or not.

Example button component

```html
# button.html
<script props>
  module.exports = {
    href: props.href,
    dataPmNoTrack: props.dataPmNoTrack,
  }
</script>
<div>
  <a href="{{ href }}" data-pm-no-track="{{ dataPmNoTrack }}">
    <content></content>
  </a>
</div>
```

Now depending if the `dataPmNoTrack` prop is included the final result has `data-pm-no-track` on the `<a>` element just as one would expect. 

```html
<x-button href="https://maizzle.com" dataPmNoTrack>X</x-button>

# results in

<div>
  <a href="https://app.koos.io/" data-pm-no-track>
    X
  </a>
</div>

# and when not using the property
 
<x-button href="https://maizzle.com">X</x-button>

# result is without added attribute as expected, so far so good.

<div>
  <a href="https://maizzle.com">
    X
  </a>
</div>
```

Now while trying to define a property name that includes dashes the system behaves a little differently while using said custom property.

```html
# button.html
<script props>
  module.exports = {
    href: props.href,
    dataPmNoTrack: props['data-pm-no-track'],
  }
</script>
<div>
  <a href="{{ href }}" data-pm-no-track="{{ dataPmNoTrack }}">
    <content></content>
  </a>
</div>
```

Now while using the component with the property included I get the same attribute added to both `<div>` and `<a>`.

```html
<x-button href="https://maizzle.com" data-pm-no-track>X</x-button>

# results in

<div data-pm-no-track>
  <a href="https://maizzle.com" data-pm-no-track>
    X
  </a>
</div>
```

Not sure if it's a limitation of `module.exports` or something that could be improved in the library but it sure would be useful to add custom properties that include dashes.

I know there is also the `attributes` keyword to use inside components but I would like to keep outside `class` & `style` being applied to the root element.

Hope I was clear describing the issue and happy to further elaborate on my predicament.
Thank You for the awesome framework!

**Comment by cossssmin** [comment]
Attributes starting with `data-` and `aria-` [are safelisted and considered 'valid'](https://github.com/thewebartisan7/posthtml-components/blob/1775153783f79511c5f61f3e440db7e026acee12/src/valid-attributes.js#L3549-L3556) in the `posthtml-component` library that we're using, which means they get added to the root node of your component. That's why the attribute shows in two places for you.

A way around this in your case is to use the [`attributes`](https://maizzle.com/docs/components#attributes) attribute to define where the valid HTML attributes that are passed to the component should be rendered:

```html
<!-- button.html -->
<script props>
  module.exports = {
    href: props.href,
    dataPmNoTrack: props['data-pm-no-track'],
  }
</script>
<div>
  <a href="{{ href }}" data-pm-no-track="{{ dataPmNoTrack }}" attributes>
    <content />
  </a>
</div>
```

**Comment by priithansen** [comment]
Thank's for taking the time to look into this. What I would like to achieve is to have the "attributes" still apply to the root element mainly so I can add margin classes from outside while using the component.

With this new info I tried to override the `build.component` `safelistAttributes` and `blacklistAttributes` with no luck. Using either or both still results in "data-pm-no-track" being added to both the root element and  to the inner one.

````js
// config.js
build: {
  components: {
    blacklistAttributes: ['data-pm-no-track'],
    safelistAttributes: [],
  },
  ...
}
````

With this specific case I can live with the duplicate attribute or rename the component prop to something different eg: "no-track" and resolve the issue but just wanted to let You know if maybe there is a bug here or are opportunity to clarify the documentation.

**Comment by cossssmin** [comment]
`safelistAttributes` / `blacklistAttributes` attributes that you define are merged with the defaults, they do not overwrite them.
