### ISSUE TITLE
error to build in production an using npm workspace

### ISSUE THREAD

**Issue by freezer71** [maizzle/framework#974]
- Maizzle Version: latest
- Node.js Version: 18.15.0
![image](https://user-images.githubusercontent.com/68165179/231562115-a8d92f55-ae30-4cd6-8196-777350a7052f.png)
I have a problem with the cli on line 53, i use npm workspace for my project and I put the bin correctly but for line 53 it not using the path of the correct dir
![image](https://user-images.githubusercontent.com/68165179/231563014-4e56357b-814b-4c10-9a0f-e85464932324.png)

**Comment by cossssmin** [comment]
What Maizzle CLI version are you using? We screwed up in 1.5.3 and reverted in 1.5.4 🫣

**Comment by cossssmin** [comment]
Ah no, sorry, different issue, 1.5.3 might actually work for you. Will add the try/catch back, think that was what lead us to the change from 1.5.2 to 1.5.3…

**Comment by cossssmin** [comment]
See the discussion in maizzle/cli#198, think the same thing is affecting you too.

**Comment by cossssmin** [comment]
Try CLI 1.5.6, should be fine now for monorepos 

https://github.com/maizzle/cli/releases/tag/v1.5.6

Closing this, let's keep it in #985 please, thank you!
