### ISSUE TITLE
Bug: else statement fails when comment precede

### ISSUE THREAD

**Issue by vkovic** [maizzle/framework#982]
- Maizzle Version: 4.4.4
- Node.js Version: 14.20.0

Consider the code:
```
<if condition="1">
    Foo
</if>
<!-- Comment -->
<elseif condition="0">
    Bar
</elseif>
```

It should display "Foo", but instead it displays "Foo Bar".
When HTML comment is removed it works as expected.

**Comment by cossssmin** [comment]
This is how `posthtml-expressions` works right now. It'd be a nice improvement to it for sure (skip any comment nodes until next else/elseif) but for now you'll need to move your HTML comment inside that `elseif`.

**Comment by vkovic** [comment]
Ok, thank you for the clarification.

I'm closing this right now.

**Comment by Scrum** [comment]
@cossssmin Hello, if it is possible to move the task to the package `posthtml-expressions`
