### ISSUE TITLE
Bug on some chars when passing props down to child components

### ISSUE THREAD

**Issue by schirliuradu** [maizzle/framework#993]
Hi @cossssmin,

Sorry for the delay of my answer. I was trying the solution above, and it works. It seems to be fine.

There is only a small issue, if there is a string containing the `'` in the object you pass down to the children component. It seems that it does some transformations during that step which truncates all the part of the string which, the part after the `'` char. Do you have any ideas on that? 

This one could be an example:

```
const items = [
  {
    title: "lorem ipsum dol'or sit amet",
  }
]
```

_Originally posted by @schirliuradu in https://github.com/maizzle/framework/issues/397#issuecomment-1536422247_

**Comment by cossssmin** [comment]
Hey, looks like it might be an issue in [`posthtml-components`](https://github.com/thewebartisan7/posthtml-components).

@thewebartisan7 this test fails (notice the `'` in `My P'age`), it renders `Default title` instead of `My P'age'`:

```js
test('Props with single quotes in values', async t => {
  const actual = `<component src="layouts/base-locals.html" props='{ "title": "My P\'age" }'><div>Content</div><fill:footer>Footer</fill:footer></component>`;
  const expected = `<html><head><title>My P'age</title></head><body><main><div>Content</div></main><footer>Footer</footer></body></html>`;

  const html = await posthtml([plugin({root: './test/templates', tag: 'component'})]).process(actual).then(result => clean(result.html));

  t.is(html, expected);
});
```

**Comment by cossssmin** [comment]
@schirliuradu for now a way around it is to use `&#039;` for single quotes if possible. 

Or you could pass the actual value instead of the entire object to the component, I see it's an issue only when an object is passed.

**Comment by schirliuradu** [comment]
> @schirliuradu for now a way around it is to use `&#039;` for single quotes if possible.
> 
> Or you could pass the actual value instead of the entire object to the component, I see it's an issue only when an object is passed.

Yes, both could be good solutions. 

The first one is ok.

For the second one,  in my case, i have nested components on at least 3 levels: wrapper, listing, single item. For that reason, i can't pass all item properties down to listing component which i use inside the wrapper.

I hope this issue will be fixed in a minor version of posthtml-components, so that we can bump it's version and fix the issue, to have this working in a "natural" way. 

Thanks @cossssmin.

**Comment by thewebartisan7** [comment]
@cossssmin  @schirliuradu  I am afraid that it's not something that can be fixed on plugin side because it's how HTML attributes works.

Take this example:

```html
<div attr="This 'works'!" />
<div attr='This "works" too' />
<div attr="This does NOT \"work\"" />
<label attr='This does NOT \'work\'' />
<div attr="And this is &quot;OK&quot;, too" />
```

You can use single quotes inside double quotes or double quotes inside single quotes. If you want to use single quotes inside single quotes or double quotes inside double quotes, you have to HTML encode them, like @cossssmin  suggested.

Since we need to use single quote for JSON we can't use single quotes inside values, and we can't use double quotes when using JSON:

```js
props='{ "title": "This works" }'
props='{ "title": "This  don\'t works" }'
```

Because this is how is parsed:

```js
  console.log({...node.attrs});
 { props: '{ "title": "My P\\', 'age"': '', "}'": '' }
```

You will get the same problem with posthtml-expressions.

**Comment by schirliuradu** [comment]
@thewebartisan7 ok, thanks.

The fact is that there are some languages using this char very often, in a lot of words/phrases, like the italian language. 
I'll stick with the `&#039;` solution, even though is not the most natural one.

Thank you both @cossssmin @thewebartisan7.

**Comment by schirliuradu** [comment]
@cossssmin The other solution would be to insert an extra check in the framework core to check if there is this char in the given component/global data and replace it with `&#039;`, before passing everything to posthtml engine. 

This is an extra layer of logic but in this way it'll be hidden to the final user, and the final user will stick with the "natural" way of doing that: using `'` char. We could also threat it as an extra "transformer" to activate/deactivate, to avoid doing it everytime, even when people don't need this replacement.

Don't know what do you think about this, let me know maybe. 
Thanks @cossssmin.

**Comment by thewebartisan7** [comment]
> @thewebartisan7 ok, thanks.
> 
> The fact is that there are some languages using this char very often, in a lot of words/phrases, like the italian language. I'll stick with the `&#039;` solution, even though is not the most natural one.
> 
> Thank you both @cossssmin @thewebartisan7.

Yes I know, I speak italian :)

HTML special chars are there for such scenario, see complete list https://www.html.am/reference/html-special-characters.cfm

As you said, it must be escaped before passed to the attributes, for example `props.replace(/'/g,"\\'")`

**Comment by cossssmin** [comment]
> The other solution would be to insert an extra check in the framework core

Unfortunately this could only be done "globally" for the entire HTML, and it could lead to unexpected results for others. Even if we were to convert all `'` to `&#39;` and then back to `'` after PostHTML renders the HTML, it could still be unexpected for some users that actually want `&#39;` in their compiled HTML.

Best is to just encode the strings you need to pass to components, I'll make a note to add this gotcha to the docs.

**Comment by cossssmin** [comment]
https://maizzle.com/docs/components#encoding-props-data
